uktrade/data-workspace-frontend

dataworkspace/dataworkspace/apps/applications/management/commands/push_tool_monitoring_dashboard_datasets.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/settings/base.py, infra/ecs_main_admin.tf
This PR adds a celery task which gets a few ECS task stats and pushes them to geckboard:
Related terraform-data-workspace PR: https://gitlab.ci.uktrade.digital/data-infrastructure/terraform-data-workspace/-/merge_requests/35
=> feature: add celery task to push tool usage datasets to geckoboard

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py
Do not use query name in cursor as it can cause syntax errors if certain chars are used.
=> fix: use source type and query id as cursor name

dataworkspace/proxy.py
workaround the clash between data workspace and superset api paths by checking if the request is for superset _before_ checking if it's for a dataset
=> fix: check api path is not for superset

infra/security_groups.tf
Suspect that if it goes does right now, it won't be able to come back up
=> fix: open up the ECR API for the healthcheck service to be able to pull its Docker image

docker-compose-superset-dev.yml, superset/Dockerfile, superset/monkey-patch-requests.js
Overrides `fetch()` and `Worker.postMessage()` to inject our map tiles into the mapbox and deck.gl superset charts.
=> fix: replace requests to mapbox with our own mirror

dataworkspace/dataworkspace/apps/datasets/management/commands/disable_customdatasetquery_datagrid.py, dataworkspace/dataworkspace/apps/datasets/management/commands/enable_customdatasetquery_datagrid.py
A django management command to enable and disable ag-grid for CustomQueryDatasets.
To enable
`python3 manage.py enable_customdatasetquery_datagrid`
To disable
`python3 manage.py disable_customdatasetquery_datagrid`
=> commands to enable and disable all datagrids against CustomDataSetQueries

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/static/data-grid.js
- Escape `%` in custom dataset queries before running. 
- Fix js issue that broke the page if no columns were returned
=> fix: replace % with %% for data grid queries

dataworkspace/dataworkspace/settings/base.py, dataworkspace/proxy.py
Turn off ecs log formatting in django and the proxy when running locally
=> fix: do not use ecs logging formatter locally

rstudio/rstudio-start.sh
When connecting to the database, suspect in R was calling Sys.timezone(), which in turn was calling, timedatectl which output the warning:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
Warning message:
In system("timedatectl", intern = TRUE) :
running command 'timedatectl' had status 1
```
Manually setting the timezone seems to avoid this.
=> feat: avoid warning in RStudio about timedatectl and systemd

dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/apps/dw_admin/views.py, dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/tests/test_admin.py, dataworkspace/dataworkspace/tests/your_files/test_utils.py
Ensure "your files" table creation and the reference dataset uploader can handle csvs with byte order mark
=> fix: allow for bom in uploaded csvs

dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/query_results.html
This PR is to fix the broken font after adding `pre` tag to preserve white spaces
=> font needs fixing after adding <pre> tag to preserve white spaces

dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/tests/your_files/test_utils.py
Use the csv module to read in the first 100 bytes from an uploaded file to allow for newlines and or incomplete last lines
=> fix: ensure newlines don't break data type inference

dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
Added back the GDS phase banner against visualisation previews on master dataset catalogue page
=> Adding GDS phase name banner to visualisation preview

dataworkspace/dataworkspace/apps/core/templatetags/core_tags.py, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/proxy.py
- Pass the user agent header through to the django application from the proxy
- Adds a new template tag to determine if a user agent matches ie11 or below
- Do not show master dataset visualisations if the user is using internet explorer
=> feat: do not show vega visualisations to ie11 users

dataworkspace/dataworkspace/apps/datasets/utils.py
Ensure python snippets with multi-line sql queries run in tools
=> fix: surround sql queries with triple quotes

infra/rds_admin.tf
AWS upgrades the engine version automatically so this should be ignored in terraform
=> infra: ignore engine version for admin db instance

.envs/test.env, dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/main.tf
This works in a similar way to the existing update_quicksight_visualisations_last_updated_date task, it calls the Superset API to get the datasets for each dashboard. It then extracts tables from each dataset's sql query and links the datasets / datacuts to the visualisation catalogue item accordingly.
Related infra changes are on https://gitlab.ci.uktrade.digital/data-infrastructure/terraform-data-workspace/-/merge_requests/40
=> feature: add celery task to link datasets to superset dashboards

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR is to escape both Python and R code snippets, so that the code can be run without any errors in JupyterLab and RStudio.
=> Esacape python r code snippets

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/apps/request_access/forms.py, dataworkspace/dataworkspace/apps/request_access/urls.py, dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/design_system/file.html, dataworkspace/dataworkspace/templates/eligibility_criteria.html, dataworkspace/dataworkspace/templates/request_access/dataset.html, dataworkspace/dataworkspace/templates/request_access/partials/summary-list-row.html, dataworkspace/dataworkspace/templates/request_access/summary.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/request_access/factories.py, dataworkspace/dataworkspace/tests/request_access/test_views.py
Show a summary page before creating/confirming an access request.
- Adds functionality "continue" an access request from the dataset eligibility/access request start pages
- Also includes a small bug fix for hiding code snippets from unauthorised users
- And a fix to stop showing snippets for reference datasets that are not published to the datasets db
This branch is live on dev now for testing
=> feat: add a summary page before submitting zendesk ticket

dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html
Data cuts are not limited to 5,000 rows so do not say they are on the download button.
=> fix: do not show download limit for data cuts

dataworkspace/dataworkspace/tests/datasets/test_views.py
Set external database to `my_database` to workaround the multiple database in tests issue for reference datasets.
=> fix: use `my_database` for external db testing

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/finder/index.html, dataworkspace/dataworkspace/tests/finder/test_views.py, test/test_application.py
- Adds a link to the dataset finder from the search form
- Updates to content and addition of a link from the dataset finder to the main search page
- Adds a link to request access if user doesn't have perms for a search result
=> feat: dataset finder content updates

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
Related visualisations was duplicated on the datacuts page. In the sidebar and also at the bottom of the page (from the previous design).
Fix - Remove visualisations from bottom of page
Fix - Format related visuals in sidebar to use <nav> 
=> removed duplicate related visuals and formatted sidebar

dataworkspace/dataworkspace/apps/finder/utils.py, dataworkspace/dataworkspace/apps/finder/views.py, dataworkspace/dataworkspace/templates/finder/index.html, dataworkspace/dataworkspace/tests/finder/test_views.py
Check user's access to a dataset via the `user_has_access` method when showing finder results....
1. Fixes a bug where sometimes the user was shown the "request access" link when they already had access
2. The previous way of checking access does not work for allowed email domains
=> fix: use table perm checker in finder results

dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
The csrf cookie doesn't exist until a user has seen the `{% csrf_token %}` at least once (or visited an admin form). To workaround this, don't use the cookie, get the token from the form element itself.
=> fix: get csrf token from from element to fix missing cookie issue

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/partials/related_data_link.html
Added a new css class for related dashboard links from catalogue pages `related-dashboard`. To be used by performance analytics.
Changed `Related visuals` to `Related dashboards` on datacut catalogue template. This makes it consistent with Master dataset.
~* [ ] Have tests been added to cover any changes? No!~
=> add css class for related dashboard link and make headings consistent

dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py
This stops users from accessing other user's access request data by changing the id in the url
=> fix: prevent users from seeing other user's access request details

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_column_details.html, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/partials/column_list.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Adds a page to show all columns for a data cut custom query.
=> fix: add column details page for datacut queries

tools/jupyterlab-python/start.sh, tools/theia/Dockerfile, tools/theia/start.sh
This is to get pyspark working, which uses Java under the hood, which raises an exception if $HOSTNAME is not resolvable, which is the case in tools
=> fix: avoid exception in Java programs when hostname is not resolvable

dataworkspace/dataworkspace/apps/core/templatetags/core_filters.py, dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/static/gtm-support.js, dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/datasets/scrolling_filter.html, dataworkspace/dataworkspace/templates/datasets/scrolling_filter_option.html
- Changed source list on search page to a scrolling container.
- Fix to GTM client side dataLayer pushes. No longer sends the `(2)` part of the filter labels
=> feat: scrolling display of source filter checkboxes

requirements-dev.txt, requirements.txt
minor version update to psycopg2-binary. Doing this in advance of making changes to containers and packages for Apple M1 compatibility 
=> fix: bump psycopg2 in anticipation of M1 compatible changes

dataworkspace/dataworkspace/apps/core/utils.py
It is suspected that ALTER TABLE inside a team schema blocks REVOKE, which in turn, blocks _all_ users on Data Workspace from regenerating credentials.
=> feat: avoid unnecessary REVOKEs on team schema tables

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html
add sso user id to google analytics. This is to track new users of data workspace and the actions they complete, so we can track value for money for the comms and engagement campaign.
=> feature:add sso user id to google analytics

dataworkspace/dataworkspace/apps/datasets/management/commands/_create_utils.py, dataworkspace/dataworkspace/apps/datasets/management/commands/create_fake_dataset.py, dataworkspace/dataworkspace/apps/datasets/management/commands/create_fake_tag.py
2 new management commands for use with local development
`create_fake_dataset` will create a dataset using fake data
`create_fake_tag` creates a tag. Again with fake data
Use the `--help` command line option to see usage.
=> feat: new management commands to create datasets and tags for local dev

tools/jupyterlab-python/Dockerfile
No longer adding buster-cran35 to sources.list for this container. Not needed.
=> fix: remove cran from sources.list

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py
=> fix: pass datetime object in isoformat to send_email function

dataworkspace/proxy.py
We already allow unsafe-inline, so I don't think this meaningfully decreases security. And the main purpose the the CSP for tools and visualisations is to forbid connections to external sites, which this doesn't make any more possible.
=> feat: allow data-uris for scripts and styles in tools and visualisations

dataworkspace/dataworkspace/apps/accounts/utils.py, dataworkspace/dataworkspace/templates/datasets/index.html
- Updated catalogue index page to use the correct case for `SSO_USER_ID`
=> fix: incorrect case for SSO_USER_ID on catalogue index page

requirements-dev.txt, requirements.txt
Just bumps up the cryptography package from cryptography==3.3.2 to cryptography==3.4.8
This is because some M1 users were having difficulties installing requirements with the older cryptography version
=> bumps up cryptography version to help M1 mac users

tools/theia/Dockerfile, tools/theia/yarn.lock
- requires installation of libsecret in the docker container due to an upgrade of node-gyp
Running on dev currently
=> fix: upgrade theia to 1.20.0 to fix CVE-2021-41038

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/finder/views.py, dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/finder/results.html, dataworkspace/dataworkspace/tests/finder/test_views.py
https://trello.com/c/q8oVdl0X/2261-dataset-finder-open-in-data-explorer-button-removed-and-download-option-added
=> feature:replace finder results data explorer button with download csv

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/datasets/source_changelog.html, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py
- Adds a new celery task to save data and structure changes to the metadata table for reference datasets
- Adds a new changelog page to reference datasets to match master/datacuts
=> feat: add structure and data metadata to reference datasets

superset/superset_config.py
Two small fixes for the issue where a public user would be denied access to a visualisation when they first logged in
1. Get the redirect url from the request if it exists and redirect to it after logging in
2. Clear any "access denied" flash messages on successful login
=> fix: redirect to correct page after login

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py
Cast all reference dataset records to str before json serialising and hashing
=> fix: cast ref dataset records to string when calculating hash

dataworkspace/dataworkspace/apps/datasets/models.py
Remove unnecessary ordering when hashing a reference dataset table
=> fix: no need to reorder records returned by get_records()

dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/dataworkspace/tests/test_datasets_db.py, test/test_application.py
This ensures that tables uploaded via Data Uploader always have a last updated date set
=> feat:return dataflow_swapped_tables when source_date_modified is null

superset/superset_config.py
Add a check that supersets' `_flashes` session list exists before attempting to clear it
=> fix: ensure flash message list exists on session before clearing

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_models.py
Grid and downloads were broken when a reference dataset had linked to two or more datasets with the same field name.
=> fix: ensure ref dataset grid columns have unique names

test/test_application.py
Fix failing integration test caused by missing `data_type` column in metadata db
=> fix: add data_type to metadata test table

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/datasets/test_models.py
cloned master datasets now get their published_at date at the time of cloning rather than inheriting it from the previous dataset
=> changes published date for cloned master datasets to time of cloning

tools/theia/package.json, tools/theia/yarn.lock
=> fix: upgrade markdown-it npm package to fix CVE-2022-21670

dataworkspace/proxy_session.py
Browsers now won't attempt to use the cookie after 30 minutes it was initially set, so it looks you have 30 minutes to make a request to Data Workspace without getting redirected to SSO and back.
However, sessions would are really only 25 minutes long: they are removed from Redis after 25 minutes. This is...
- Consistent with existing behaviour in terms of deleting from Redis _before_ the expiry from the browser's point of view.
- To make really sure the session is _definitely_ less than 30 minutes. Say we have a check to see if someone can use what "should" be an expired session. They should never be able to do this. Don't want a pen test to say "we used a session cookie that was 30 minutes and 2 seconds old".
- To make sure that things work fine if the browser sends a cookie that is no …
=> feat: shorter session timeout for security reasons

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/proxy.py, test/echo_server.py, test/test_application.py
- Add generic `filter_headers()` function to replace `without_transfer_encoding`
- Set cookie headers to an empty string before forwarding requests to visualisations
- Filter out `Cookie` and `Set-Cookie` headers received from visualisations
=> feat: filter cookies to and from visualisations

dataworkspace/dataworkspace/settings/base.py, dataworkspace/proxy.py, dataworkspace/proxy_session.py
This prevents vulnerabilities mostly related to before a user has visited the site on HTTPS, and they initially get to an attacker's HTTP site
Potentially down the line "__Host-" should be used, but that might need more testing and even work on SSO's side to allow a range of domains that can be redirected to.
=> feat: use prefixed cookies

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py, dataworkspace/dataworkspace/apps/datasets/pipelines/utils.py, dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/pipelines/delete.html, dataworkspace/dataworkspace/templates/datasets/pipelines/list.html
- use the correct url for the data flow api
- Do not save the pipeline if the airflow api call fails on put or post
- clean up template wording
- allow underscores in schema/tables
=> fix: update form and cleanup templates for pipelines

dataworkspace/dataworkspace/apps/your_files/utils.py
Data type name should be "numeric" rather than "number" when mapping postgres data types to sqlalchemy
=> fix: add numeric to your files data types map

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py
Fix the issue where deleting a pipeline failed if it didn't exist on data-flow. We should allow this incase the two systems get out of sync.
=> fix: ensure pipeline is deleted if dag doesn't exist on data-flow

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/proxy.py, test/echo_server.py, test/test_application.py
This reverts commit c1453aef837dbb5cf5c8a2cc4403d2aa4479055a.
This is slightly speculative - there are disconnections from tools happening, some of them giving websocket-related errors, and this change touched that code. However, looking at the change, no mechanism at how it could have broken things is known.
=> Revert "feat: filter cookies to and from visualisations (#1757)"

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py
- Changelog message changed from 'N/A' to 'Records in the dataset changed' for reference datasets, datacuts and master datasets when there is a data change. 
- Test updated in``` test_utils.py```
=> fix: change data update message in changelog

dataworkspace/dataworkspace/apps/datasets/utils.py
Use the related name as the column name for reference dataset linked fields when storing table structure metadata
=> fix: ensure the correct name is used for related fields

dataworkspace/proxy_session.py
This reverts commit 6511d8f0e32cbb989a15b609ec6e9e2d6d4e2b6d.
We've had the ok to bump up the session length - for both CSP and CORS reasons, redirects to SSO and and back essentially don't work for Ajax and Websockets requests from tools.
=> Revert "feat: shorter session timeout for security reasons"

docker-compose-dev.yml
There is a conflict of ports for minio when running data-flow and data-workspace simultaneously.
This fix changes the host ports for data-workspace.
=> fix: change host ports for minio to avoid overlap with data-flow

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/utils.py
This ensures db creds aren't shown in the Sentry stack trace variables
=> fix: don't use _ variable when loading db name as creds end up in _

dataworkspace/dataworkspace/apps/core/utils.py
Grant read/write access to all team members in a when another team member creates a table in that teams schema.
=> fix: grant default privileges to team members on table creation

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/related_visualisations.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
- ```RelatedVisualisationsSortForm``` added to ```forms.py```
- ```RelatedVisualisationsView``` added to ```views.py```
- Changes made to ```master_dataset.html``` and ```data_cut_dataset.html``` to limit number of displayed dashboards 
- Separate page made for full list of related dashboards at ```related_visualisations.html```
- Tests added to ```test_views.py```
=> feat: limit number of displayed related dashboards and link to separate page

mirrors-sync/mirrors-sync.py
PyPi seems to be slower than expected, and there are some incorrect escape characters characters in file names in the XML. There is a chance the package with this character won't be correctly mirrored, but I think it's unlikely to be one that will be used in Data Workspace.
=> fix: pypi import - bump timeout and remove bad characters

dataworkspace/dataworkspace/apps/core/utils.py
There seems to be a race condition finding permissions for a user in the `get_new_credentials` method. The potential race condition happens if a table gets deleted in between selecting all tables and checking if the user has privileges on each table. In order to prevent this, temp tables and swap tables can be excluded when getting the list of all tables.
Sentry error:
https://sentry.ci.uktrade.digital/organizations/dit/issues/56207
=> fix: exclude data flow temp and swap tables when finding permissions

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_admin.py
Fixes issue where files created by data flow could potentially be deleted by users via the admin pages. 
This fix ensures only files uploaded via the admin site are able to be deleted via the admin site.
=> fix: ensure only files prefixed with sourcelink are deleted from s3

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/your_files/views.py, dataworkspace/dataworkspace/templates/your_files/create-table-confirm-name.html, dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
Originally discovered as a bug meaning admin users were unable to select a schema unless they were in a team but decided this should apply to all users to make it very clear where the table was going to end up from the start.
=> feat: always show list of schemas when creating table via your files

dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/tests/applications/test_views.py
This is the recommended way to avoid users having to enter their email address when they first access QuickSight. It also avoids a race condition that can happen when a new user launches QuickSight via tools and doesn't complete the sign up: 
https://sentry.ci.uktrade.digital/organizations/dit/issues/53864
=> feat: pre-register QuickSight users when they launch QuickSight

dataworkspace/dataworkspace/templates/partials/messages.html
- ```messages.html``` updated to reflect difference in 'success' and 'error' messages, and use different template
=> feat: add error handling to message template

dataworkspace/dataworkspace/apps/explorer/schema.py
Hide tables ending with `_swap` and `_idx` from users in data explorer
=> fix: ignore swap tables when generating user schemas

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/context_processors.py, dataworkspace/dataworkspace/static/gtm-support.js, dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/explorer/_base.html, dataworkspace/dataworkspace/templates/partials/gtm_body.html, dataworkspace/dataworkspace/templates/partials/gtm_dataset_link.html, dataworkspace/dataworkspace/templates/partials/gtm_head.html
Added a new javascript handler to send a custom `searchResultClick` event to GA via GTM.
Changed how the GTM tag is added to html by adding a new context variable `GTM_ENABLED`. This moves the logic to the backend instead of the inconsistent `if` statements in the templates. This is easier to change for local dev
=> feat: add searchResultClick event to Google tag manager

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/gtm-support.js, dataworkspace/dataworkspace/templates/datasets/index.html
Make `searchType` depend on whether the user has typed a search term on the datasets page
Removed console.log from javascript
=> fix: gtm searchType should depend on whether user has entered a query

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
Ensure a derived query runs before sending to airflow. We need to validate on the data workspace side as the derived pipeline api airflow plugin does not have a connection to the datasets db to validate it itself.
=> feat: run query with limit 0 before saving

Dockerfile
Unpin openssl version from apt-get install in Dockerfile. 
This is to address the issue building containers.
=> fix: unpin openssl from apt-get install

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py
https://trello.com/c/tPQap2hk/2440-notifications-master-dataset-and-data-cuts-updates
This adds a celery task that iterates over metadata records inserted by dataflow and sets their data_ids to the SourceTable object ids.
This required changing the dataflow.metadata data_id column to text array in order to handle multiple source tables with the same schema and table name.
Related DataFlow PR: https://github.com/uktrade/data-flow/pull/1224
=> feature: send notifications when source tables get renamed

dataworkspace/dataworkspace/apps/core/admin.py
For every user in a team the admin page displays a select element with ~3000 options. Which makes the page very slow to render. Remedy this by making the user selectors autocomplete.
=> fix: speed up team admin page by making user field autocomplete

dataworkspace/dataworkspace/templates/finder/index.html
Fix to use the parent loop when adding search rank to dataset finder items.
=> fix: use parent loop for search rank

dataworkspace/dataworkspace/datasets_db.py
When a table is renamed this is not currently resulting in notifications because the condition that generates the changelog items doesn't compare table names.
=> fix: compare table names when generating changelog for notifications

dataworkspace/dataworkspace/apps/explorer/templates/explorer/share.html
Removed the import of apps-tabs.css to fix error on sharing query page for Data Explorer
=> fix: remove import of apps-tabs-css for data explorer

dataworkspace/dataworkspace/templates/request_access/tools_1.html
- GDPR ihasco course requirement removed from ```tools_1.html```
- To only be merged and deployed on **April 1st 2022**
=> fix: remove gdpr training for tools access

dataworkspace/dataworkspace/apps/core/boto3_client.py, dataworkspace/dataworkspace/apps/core/storage.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/apps/dw_admin/views.py, dataworkspace/dataworkspace/apps/your_files/forms.py, dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py, dataworkspace/dataworkspace/tests/applications/test_views.py, dataworkspace/dataworkspace/tests/core/test_storage.py, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/tests/datasets/test_download_views.py, dataworkspace/dataworkspace/tests/datasets/test_models.py, dataworkspace/dataworkspace/tests/datasets/test_preview_views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py, dataworkspace/dataworkspace/tests/test_admin.py, dataworkspace/dataworkspace/tests/test_models.py, dataworkspace/dataworkspace/tests/your_files/test_utils.py, dataworkspace/dataworkspace/tests/your_files/test_views.py
Move all calls to create S3 client to a helper function to allow easier proxying of AWS endpoints for local development.
=> refactor: consolidate boto3 s3 calls to enable local endpoints

dataworkspace/dataworkspace/static/gtm-support.js, dataworkspace/dataworkspace/static/search-v2.js
Fix selector for filters and GTM datalayer.
Add try/catch to GTM datapush so it doesn't block updating of history
=> fix: correct selector for filters and try catch if gtm fails

dataworkspace/dataworkspace/apps/datasets/utils.py
Now that credentials are populated using libpq-compatible environment variables, credentials don't need to be passed explicitly for code that uses libpq.
=> feat: don't explicitly set creds for Python snippets

dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/explorer/tasks.py, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/start-celery.sh
Slightly speculative changes to try to address problems that seem to stem from Celery tasks not running/getting blocked when starting tools and running Data Explorer queries.
Might need to go through things a bit more thoroughly later / enforce things in code to not hold multiple db connections open at the same time.
=> feat: limit prefetching and close admin db connection where possible in celery

dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
Added back two missing closing `div` tags from the `govuk-warning-text` container. This was causing the entire page to be indented.
=> fix: add 2 closing div tags to draft reference dataset message

dataworkspace/dataworkspace/templates/about.html
Add missing `govuk-link` css class for links on about page
=> fix: add govuk-link class to links on about.html

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Added Authorized email domains to the `has_access` field in search results for MasterDataset, DataCutDataset and VisualisationDataset. 
N/A for ReferenceDatasets
=> fix: add authorized domains to has_access logic in search results

dataworkspace/dataworkspace/apps/applications/utils_tools.py, dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/share_email.txt, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html, dataworkspace/dataworkspace/templates/partials/code_snippets.html, dataworkspace/dataworkspace/templates/request_access/you_have_access.html, dataworkspace/dataworkspace/templates/request_data/index.html
_The Data Workspace article Help Centre has been restructured, and so some hard-coded links are showing error messages and do not work anymore_ 
- Links updated for relevant pages where links are broken
=> fix: correct article links following Help Centre restructure

Dockerfile
This also unpins Debian packages, but pins a more specific Docker tag. These isn't exactly equivalent, but I'm more and more suspecting that pinning Debian package versions doesn't give much - it's extremely rare that there are backwards incompatible changes in the same major Debian version. Also, transitive dependencies were not pinned anyway, so it gave a bit of a false sense of security.
=> build(deps): bump Debian

dataworkspace/proxy.py, dataworkspace/proxy_session.py, test/test_application.py
This is to mitigate the risk of session hijacking.
Ideally, we would tie sessions to a single IP, but we can't prevent users coming from multiple IP addresses in some cases. Specifically for subdomains, so for tools and visualisations, users can consistently come from a different IP to the root domain. This causes problems for the SSO flow on a subdomain, since it involves a redirection to the root domain which needs the session to be consistent between it and the subdomain to complete the flow securely.
This deliberately supports both APPLICATION_IP_WHITELIST and IP_ALLOWLIST_GROUPS for now for a rollout without breaking anything, although APPLICATION_IP_WHITELIST will be removed later.
=> feat: tie sessions to group of ips

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py
psqlparse can't seem to handle queries containing `UNION` (it returns a single column `None`). So as we are already running the query, this moves the duplicate column check to make use of `cursor.description`.
=> fix: check for duplicate columns in cursor description

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/query_results.html, dataworkspace/dataworkspace/static/explorer_async.js
There were 2 issues:
- Duplicate `id="query-results"` in the page
- The tests were waiting for an element with `id="query-results"`, but that element was in the page from the get-go, and so the waiting didn't wait long enough.
=> fix: flakey Data Explorer tests

dataworkspace/dataworkspace/datasets_db.py
The `store_custom_dataset_query_metadata` celery task is failing multiple times in live. 
This change should help diagnose why
=> fix: handle error in store_custom_dataset_query_metadata task 

dataworkspace/dataworkspace/apps/datasets/views.py
This matches how we log these events elsewhere on the system and ensures they show up on the usage history pages.
=> fix: log query download events at the dataset level.

dataworkspace/dataworkspace/apps/datasets/management/commands/delete_temporary_tables.py, dataworkspace/start-test.sh
Especially locally when running multiple tests, the tables wouldn't get cleaned up and would result in errors like `relation "_data_explorer_tmp_query_6" already exists` when trying to run a query in Data Explorer
=> tests: more robust tests by cleaning up temporary tables

dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/tests/test_security.py, dataworkspace/proxy.py
This is so we now have a CSP for both GA4 and Universal Analytics. Should be able to remove the ones for Universal Analytics when the migration to GA4 is complete, hopefully not too far in the future..
The directives are from https://developers.google.com/tag-platform/tag-manager/web/csp#google_analytics_4_google_analytics
=> feat: update CSP for GA4

dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py
"Viewed visualisation" events were not included in the related object serialiser and hence not visible in the datasets db. This PR ensures VisualisationCatalogueItems are serialised in the same way other datasets are.
=> fix: ensure related visualisations are in eventlog api response

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
A good amount of the performance issues came from joining datasets with _all_ user permissions, subscriptions, and bookmarks - essentially a "combinatorial explosion". These are then collapsed down to one row per dataset by a GROUP BY (annotation).
However, most of these rows do not contribute to the results - they are rows for users other than the current. So this PR uses FilteredRelation to filter out the these rows in the JOIN itself, to hopefully greatly reduce the combinatorial explosion.
Quite a lot of refactoring is done in order to support this. Specifically to a) reduce duplicated code, and b) be able to have the related code for each annotation together for the different dataset types. Hopefully this supports the upcoming work to improve search results ordering as well.
From a …
=> perf: faster search - main query runs in around 1% of the time in some cases

dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/data_dictionary.html
- dictionary link in ```data_cut_source_detail``` only displayed for source datasets to fix error message on data cuts
- column width reduced for data type on dictionaries to allow more space for definitions when very long field names are present (e.g. Export Wins). 
=> fix: data cut preview link and data type column width for data directionaries

dataworkspace/dataworkspace/apps/datasets/manager/urls.py, dataworkspace/dataworkspace/apps/datasets/urls.py
Remove a load of django warnings about urls
```
data-workspace-data-workspace-1  | ?: (urls.W002) Your URL pattern '/<uuid:source_uuid>' [name='manage-source-table'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), e
data-workspace-data-workspace-1  | ?: (urls.W002) Your URL pattern '/<uuid:source_uuid>/columns' [name='manage-source-table-column-config'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targe
data-workspace-data-workspace-1  | ?: (urls.W002) Your URL pattern '/<uuid:source_uuid>/restore-table/<int:version_id>/failed' [name='restore-failed'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this patte
data-workspace-data-workspace-1  | …
```
=> fix: remove leading slash to prevent django warnings

dataworkspace/dataworkspace/apps/datasets/utils.py
If no tables can be extracted from a query do not attempt to store metadata.
=> fix: if no tables were extracted from query do not store metadata

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/datasets/test_utils.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/test_datasets_db.py
Most of the request time on the front page appears to be due from having a high number of queries per search result. This PR merges the queries, using prefetch_related, as well as some more "manual" prefetch related techniques. Specifically the number of queries for finding model instances and for finding the last update date should be reduced.
However, for Reference datasets, suspect it might be too tricky to group the queries for last update date, so leaving this for now. Also I've not actually seen the queries for finding the last updated dates for reference datasets in APM for prod, so it might not actually be much of a problem to solve.
=> perf: reduce N+1 queries

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/cel.py
This is a slightly speculative change since something is causing things to stop in the Celery workers. The change to the download view may just be due to the test environment - it was causing errors in tests:
> execute cannot be used while an asynchronous query is underway
At most as I can tell, it was something to do with the fact that there was a connection to the admin db from inside the manually spawned greenlet that also queries the datsets db. This felt slightly messy anyway, so I think it's a step forward to only query the datasets db from the greenlet, and only query the admin db from inside the request directly.
=> fix: attempt to do gevent monkey patching in Celery worker that doesn't run start.py

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/datasets_db.py
This is to prevent slow datacut queries causing a backlog of tasks
=> feature: add lock to store_custom_dataset_query_metadata celery task

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Adjust sort orders available from the dropdown on catalogue index page so that Search relevance is first priority regardless of whether a search term has been provided
=> fix: make search results order by relevance again

dataworkspace/dataworkspace/apps/core/constants.py, dataworkspace/dataworkspace/apps/your_files/forms.py, dataworkspace/dataworkspace/tests/your_files/test_utils.py, dataworkspace/dataworkspace/tests/your_files/test_views.py
Amend data type map dict to be lower case as this broke the data types defaulting
=> Fix: Amend data type map dict to default choice

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/partials/code_snippets.html
if a schema has a `.` in it it breaks the tabs on the dataset page.
=> fix: remove dots from tab identifiers

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/test_admin.py, dataworkspace/dataworkspace/tests/test_datasets_db.py
The previous version caused issues with dataflow in terms of not having permission to drop the temporary views, as well as some cases of the views hanging around even though they are temporary
=> feat: avoid touching the database when extracting database tables

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py
Converting the search by popularity to a flag to allow specific users (such as member of the Data Infrastructure team) to test it in production before we roll it out to all users.
Also, putting it at the bottom of the list, so default behaviour is as it is for all users.
=> feat: search by popularity as flag rather than switch

dataworkspace/dataworkspace/apps/datasets/utils.py
We wanted it as 60 seconds, not 60 milliseconds - many datacut metadata queries are failing.
=> fix: statment timeout is too small by a factor of 1000

dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/test_datasets_db.py
It's rare for us to use recursive CTEs, but they can be used in Tariff data, which is complicated enough, so avoiding that bug before it hits.
=> fix: recursive CTEs were being mis-identified as in the public schema

dataworkspace/dataworkspace/apps/applications/utils_tools.py, dataworkspace/dataworkspace/templates/tools.html, dataworkspace/dataworkspace/tests/core/test_views.py
- With the new tools access policy, users no longer need to complete any mandatory training in order to access Gitlab and Your Files on Data Workspace
- Update to ```utils_tools.py``` to enable this change
- Temporary removal of tools access warning sign on the tools page in ```tools.html```. This will be reinstated and updated once the appropriate designs are available.
=> feat: remove tools access requirement for gitlab and your files

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/tests/datasets/test_search.py
Calculate visualisation catalogue item popularity...
- Popularity is average number of unique users per day in the past 28 days
- The past 28 days should be the midnight before the calculation is done, to the midnight 28 days before that
- For newly published datasets include only whole days they have been published in the calculation.
- Each user can be counted as a "viewer" of a given dataset at most once per day
=> feat: calculate visualisation popularity via the event log

dataworkspace/dataworkspace/apps/datasets/search.py
Do not calculate usage stats for unpublished datasets
=> fix: do not include unpublished datasets in avg calculations

dataworkspace/dataworkspace/apps/datasets/admin.py
show sortable popularity column on all catalogue item admin pages
=> feat: display `average_unique_users_daily` on dataset admin listings

dataworkspace/dataworkspace/apps/datasets/search.py
When searching for "companies in the uk", the dataset "Companies in the UK" was ar below other result. Specifically, below those of the form "UK Companies xxx xxxx xxxx". Suspect this is due to
- The fact that cover density strongly prioritises results with the words "UK" and "Companies" close together.
- The fact that normalization=1, dividing the search rank by log of the document length, doesn't penalise longer titles enough.
So trying out turning off cover density matching for the name, and setting normalization=2, dividing the search rank by the document length.
Can't be completely sure how much this helps before it hits production data, but it's behind a feature flag.
=> feat: stronger normalisation and no cover density in dataset title search rank

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
hide internal field names from the search results query string by mapping them to descriptive names. Any requests for the old style sort params will be translated to the new type.
=> feat: hide internal fields from user facing sort options

dataworkspace/dataworkspace/apps/datasets/search.py
Reorder sort mapping to make relevance first. This is the only way to select a default choice in a django sort field.
=> fix: relevance should be default search

dataworkspace/dataworkspace/apps/datasets/search.py
We have some reference datasets that are published but don't have `published_at` set. If this is the case set the lookback to 28 days when calculating averages
=> fix: workaround ref datasets missing publish date

dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table_column_config.html
Updated the existing validation message when a CSV upload contains a different amount of columns to the existing table, in lines with GDS content requirements. 
- New validation message explaining the error 
- Exclamation device removed  
=> fix: update column validation message

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
- Edit API endpoint that lists catalogue items for consumption by data flow to include ```dictionary_published```
=> feat: add api endpoints for dictionary_published field reporting

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
https://trello.com/c/buNU0ZoZ/2679-add-filter-to-search-for-iaos-iams-to-filter-results-by-data-they-own-or-manage
=> feat: filter for datasets a user is IAO/IAM of

infra/ecs_main_mlflow.tf
The mlflow proxy is no longer listening on port 80 so the tracking server host env var needs the port to be specified
=> fix: specify port for mlflow tracking server host env var

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/settings/base.py
- Task config was pointing to the explorer tasks rather than the new core charts module
- Remove incorrect use of double curly braces `{{}}` in aggregate query
=> fix: chart data aggregation fixes

dataworkspace/dataworkspace/templates/your_files/create-table-confirm-data-types.html
Hide the table name field from your files column definitions page
=> fix: hide table name field

dataworkspace/dataworkspace/apps/explorer/templates/explorer/share.html
The share.html page uses the `content` template block which is already inside a govuk-width-container
=> fix: remove duplicate govuk-width-container

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/templates/partials/code_snippets.html, dataworkspace/dataworkspace/templates/partials/subscription_link.html
Updates to the data catalogue pages, including:
- 'Get updated when this dataset changes' moved to the left of 'Bookmark' for all catalogue types
- 'Use this data' link changed to 'use this data for analysis' link
- Text ellipsis added to model name in breadcrumbs for all catalogue types
- 'View all tools' link added to code snippet sections
- Related data/related dashboards/source dataset sections re-formatted into sidebar sections
- New text added to related dashboard section with a link to Quicksight help centre article
- 'Ways to use our data' removed from all catalogue pages
- 'Open JupyterLab' and 'Open R Studio' buttons added to code snippet sections
=> feat: design changes to the data catalogue

dataworkspace/dataworkspace/static/explorer_query.js
The table list is formed of schema.table_name pairs, but the default regex used to find the current identifier does not include dots. This mis-match caused the autocompletion to ignore the schema name in the existing query, and re-add the whole schema.table_name pair, resulting in schema.schema.table_name, which then resulted in the server complaining about cross database references not being implemented.
=> feat: include dots in identifiers from the point of view of auto-completion

dataworkspace/dataworkspace/apps/core/utils.py
The existing copy_object resulted in errors for files > 5GB:
> An error occurred (InvalidRequest) when calling the CopyObject operation: The
> specified copy source is larger than the maximum allowable size for a copy
> source: 5368709120
So using copy instead, which does a multipart CopyObject.
=> feat: support ingestion of files bigger than 5GB

infra/ecs_main_mlflow.tf, infra/ecs_main_mlflow_container_definitions.json, mlflow/start.sh
This isn't needed when using the proxied artifact set-up
=> feature: remove mlflow default-artifact-root param as it isn't needed

dataworkspace/dataworkspace/templates/running_base.html
Two changes:
1. When visualisations are in FULL_HEIGHT_IFRAME then the margin made it not actually full height - there was a visual border that looked bad. This must have snuck in - it's not how it was originally designed.
2. When the visualisation in FULL_HEIGHT_IFRAME, then there is no header/navigation to skip, so it's strictly worse having the "Skip to main content" link than not having it.
=> feat: remove skip for certain custom visualisations, and unnecessary padding

dataworkspace/dataworkspace/templates/running_base.html
Without `height: 100%` the quicksight vis iframe is buggy and either doesn't display full page or flickers and disappears.
=> fix: make iframe full height

dataworkspace/proxy.py
This is specifically to allow access to the Data Workspace video on the welcome page.
But we don't put anything with any  access restrictions in the mirror, and it's still behind SSO auth. So we're KISS and opening up the whole mirror up to everyone with Data Workspace access.
=> feat: allow mirror access from not behind the whitelist

dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py
airflow have changed their date format. Use dateutil to parse it for use in templates
=> fix: use dateutil to parse airflow dates

dataworkspace/dataworkspace/static/search-v2.js
Add name key to accessibleAutocomplete to allow search functionality to perform
=> fix: Add name key to accessibleAutocomplete dict

dataworkspace/dataworkspace/apps/datasets/utils.py
Amend the recently viewed catalogue query to show the latest data and generate a list of unique object ID's to query
=> Fix: Amend recently viewed catalogue query to pick up latest data

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/tests/datasets/test_views.py
The source's download_limit was being set to 5000 in utils.py if it was None, it needs to be set in the View and passed back to the client in the JSON response.
The rowcount query from the utils package will return download_limit+1, with logic in data-grid.js to compare rc and dlimit to display "5000+ rows".
Fix for what was likely a regression in PR #2137.
=> set null source download_limit to 5000

dataworkspace/dataworkspace/apps/datasets/search.py
Limit suggested searches to past 30 days to prevent performance load issues on DW
=> fix: limit suggested searches to 30 days to prevent performance issues

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/static/search-v2.js
Results were being limited to 5 in the frontend, this should be done in the backend to try reduce database query size
=> fix: Limit results to 5 max in backend instead of frontend

dataworkspace/dataworkspace/templates/tools.html
The individual tools are h3, the "Tools" heading is h1, so the sections/groups should be h2
=> fix: missing level in heading structure on tools page

dataworkspace/dataworkspace/apps/datasets/search.py
This results in SQL like:
```
SELECT
LOWER("eventlog_eventlog"."extra" ->> 'query') AS "lower_query"
FROM
"eventlog_eventlog"
WHERE
"eventlog_eventlog"."event_type" = 29
AND "eventlog_eventlog"."extra" -> 'number_of_results' > '0'
AND LOWER("eventlog_eventlog"."extra" ->> 'query')::text LIKE 'my search query'
AND "eventlog_eventlog"."timestamp" > '2022-08-24T06:47:25.269903+00:00'::timestamptz
GROUP BY
LOWER("eventlog_eventlog"."extra" ->> 'query')
ORDER BY
COUNT(LOWER("eventlog_eventlog"."extra" ->> 'query')) DESC
LIMIT
5
```
As in comments in the code, there is a bit of faff to force Django to use `->>`to allow the result to be passed to `LOWER`.
Also includes a fix where the least popular searches were shown, when it should have been the most popular
=> feat: case-insenstive search suggestions and fix ordering of search suggestions

dataworkspace/dataworkspace/static/search-v2.js
At the moment if a user tries to tab to a dataset link and click it, it runs the form change instead of navigating them to that dataset page. This is a fix to ensure the form is only changed if input has enter key pressed or one of the dropdown options
=> fix: allow user to select dataset by tabbing

dataworkspace/dataworkspace/apps/explorer/schema.py
The select_related was to work around related fields being used by __init__ on the model. However, `values` doesn't call `__init__`, so we don't need select_related anymore
=> feat: avoid N+1 queries for reference datasets by using `values`

dataworkspace/dataworkspace/apps/explorer/schema.py
The Datasets have code inside `__init__ `that cause N+1 problems, which were previously solved with select_related. However, almost none of that data is used, to the queries were joining needlessly and returning unused data.
It's much simpler, quicker, and more robust to use `values` which doesn't call `__init__` on each model instance.
=> feat: queries don't needlessly select_related on data they don't use

dataworkspace/dataworkspace/static/search-v2.js
At the moment if you type an input and press enter on something not on the suggested dropdown list, it still shows the menu. This PR resolves this problem
=> fix: hide suggested search menu on enter

dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/explorer/utils.py, test/test_application.py
Looking at APM, we still have N+1 queries in Data Explorer in some cases for ReferenceDataset. Suspect this is due to code it has in its `__init__` method.
We could do more "selected_related" and/or "prefetch_related", but it's much easier, and robust, and likely quicker, to avoid these and call "values" that doesn't run` __init__` at all because model instances are not constructed.
Note that `Credentials-Db-Id` isn't used by Superset, and so can be removed.
=> feat: use `values` to better avoid N+1 issues when querying ReferenceDataset in bulk

dataworkspace/dataworkspace/static/search-v2.js
We now have a search type of input rather than text, so we need to listen on type=search rather than type=text
=> fix: enter on search when there are suggested searches

dataworkspace/dataworkspace/apps/your_files/views.py
The purpose of the credentials creation is more to ensure that the schema and role are setup for when the ingest happens in dataflow. Since this can take quite a while and here is part of the request-response cycle (and so can cause 504s) moving it to data-flow
=> feat: don't create new database credentials when importing CSV

dataworkspace/dataworkspace/templates/welcome.html
* Commented out block about chart builder as this feature is now hidden
* Changed background colours of other blocks to account for missing block
* Switched image alignment of other blocks to account for missing block
* Reordered Find out more bullets to lead with newsletter and Teams
I haven't tested it locally as I am editing in the browser.
=> feat: removed chart builder reference from welcome screen

dataworkspace/dataworkspace/apps/datasets/views.py
For some reason sometimes a server side cursor can make a query less performant. Here, we don't need to take that risk since we're fetching all the rows and loading them into memory anyway, so there is no benefit of a server side cursor.
To help debugging production issues, we now set application_name instead, which is viewable by (for example) pg_activity
=> perf: speculative removal of server side cursor for data grid

dataworkspace/dataworkspace/apps/datasets/views.py
Suspecting that data grid queries were holding locks that prevented swap table task from running
=> feat: set statement timeout for data-grid queries

dataworkspace/dataworkspace/apps/core/migrations/0011_auto_20221017_1448.py
Use `.distinct()` to get distinct users from the `TeamMembership` queryset as using a `set()` does not work
=> fix: use queryset distinct to get team users

dataworkspace/dataworkspace/apps/your_files/forms.py, dataworkspace/dataworkspace/tests/your_files/test_views.py
Right now you can hack the URL to make a CSV from a file in your own personal bigdata/ 
e.g. https://data.trade.gov.uk/files/create-table/confirm?path=user/federated/9c57e86a2fdb79b11256ce3f8cc827814f146a7f268d4930817516e685c86267/bigdata/output.csv
This PR is to make it so you can do this for files in team folders, e.g.
https://data.trade.gov.uk/files/create-table/confirm?path=teams/My Team Folder/output.csv
=> feat: create a table from a CSV in a team s3 folder by hacking the URL

.gitignore, docker-compose-dev.yml
small cleanup for the localstack work.
- Move the mounted config dir to `.localstack` as we don't need to see it. 
- Add `.localstack` to gitignore
=> fix: use .localstack and ignore it

dataworkspace/dataworkspace/static/js/react_apps/src/your-files/popups/DeleteObjects.jsx, dataworkspace/dataworkspace/static/js/react_apps/src/your-files/popups/UploadFiles.jsx
The delete one is slightly tricky since
- A user might have selected a folder which has lots of files
- And then files are deleted in batches, combining files inside folders and specifically selected
So a single selected item can correspond to multiple requests any of which can fail, and a single request can correspond to multiple selected items.
https://user-images.githubusercontent.com/13877/197370338-664183c7-f398-41ae-bbee-9e3dd19e57b5.mov
=> feat: show upload and Delete errors

localstack/init/buckets.sh, localstack/init/s3-cors.json
The etag header is needed for multipart uploads, but it wasn't configured to be accessible from Javascript, CORS-wise.
There is a localstack environment variable, EXTRA_CORS_EXPOSE_HEADERS, but that didn't seem to work - it only returned the header names in Access-Control-Expose-Headers in response to the preflight request, not the request proper where it needs to to be.
Suspect that there is some conflict between EXTRA_CORS_EXPOSE_HEADERS and the "proper" CORS config for S3, where the S3 config takes priority for certain requests.
https://user-images.githubusercontent.com/13877/197385699-a526b468-46d8-409e-8b0f-ac5b78e2f054.mov
=> feat: fix multipart upload (for large files) in local dev environment

dataworkspace/dataworkspace/static/js/react_apps/src/your-files/App.jsx
In Chrome, attempting to re-select the same file after doing it once didn't trigger the onChange event. Clearing the file input's value at the end of the change handler fixes this.
The behaviour was already correct in Firefox
https://user-images.githubusercontent.com/13877/197386025-e201b786-5f1b-4628-9c4f-99552b0c2c87.mov
=> fix: re-select same file in Chrome

dataworkspace/dataworkspace/static/js/react_apps/src/your-files/FileList.jsx
=> feat: tweak spacing and sizes of shared team folder icon

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
As per the comments on the Jira ticket, removed the blue strip on the collections page, fixed some small styling issues, corrected grid widths and added a main wrapper for content
=> styled collection page as per DT-735

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
The "Owner" section was between the "Data" title and the list of data items. This caused some strange spacing.
DT-739
=> fix: html structure/spacing on collection page

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json, dataworkspace/dataworkspace/static/js/react_apps/package.json
The change in 4cfde1c961966832050793b93edb0c75056e0c05 was committed without an `npm install` which runs force-resolutions, so have now run that. Also noticed that some dependencies don't need to be in resolutions any more it seems, so removed to allow them to be upgraded.
DT-773
=> build(deps): bump d3-color and remove no-long needed resolutions

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
This colours the links correctly, including focus style
https://user-images.githubusercontent.com/13877/200603299-7417418a-be86-469c-8f86-3d565bc0e09b.mov
DT-780
=> fix: use govuk classes on Search for links on collections page

dataworkspace/dataworkspace/apps/data_collections/admin.py
Do not show deleted members on the collection admin page
=> fix: do not show soft deleted members of collections on admin

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
The following fields are recorded in Django but are not present in public.dataworkspace__catalogue_items
a.       License url
b.       Restrictions on usage
c.       User access type
d.       Authorised email domains
DNA-178
=> feat: add fields to CatalogueItemsInstance viewset on API

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
It's potentially slightly odd to be re-using the "search-result" class, but I think it's reasonable to use the same class as the front page to get as much consistency between those results and these items. The worst thing may be the name "search-result" since it's now also used not as a search result, but leaving as is. This commit is still a step forward in terms of UX consistency and code consistency between different parts of the code.
https://user-images.githubusercontent.com/13877/202454858-c4dc90cc-39c5-4080-bc05-fa3e59bb21fc.mov
DT-807
=> feat: add lines between collection items

dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html
When trying to fill in these details for publication, the box appears but can't be edited/added to. This then prevents users from publishing and requires us to add descriptions on the admin side.
=> feat: make catalogue page description on front end editable

dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/templates/datasets/edit_dataset.html, dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html
Convert descriptions in both the dataset and catalogue item front end edit UI to rich text fields
=> fix: convert descriptions to rich text fields for datasets and catalogue items

s3sync/Dockerfile, s3sync/requirements.txt, s3sync/start.sh
It looks like s3sync wasn't responding well to AAAA request failures from our DNS Rewrite proxy. Rather than supporting AAAA, trying best to not use ipv6 to KISS (since this is all internal).
The main thing that I think makes this more robust is the move to Debian and trying to get it to prefer A records.  Although I still see requests in the DNS rewrite proxy for AAAA records, s3sync doesn't seem to be going wrong in response to them. While it's not great to not completely understand everything that's going on, might have to live with the fact that this seems to be working now.
Requires merge and release of https://github.com/uktrade/mobius3/pull/50
=> fix: force mobius3 to use ipv4 only

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
Based on feedback from one of the pilot users on 30 Nov 2022, it isn’t clear that Collection “users” are users of the Collection itself rather than users of the datasets.
A simple text change should help with this.
On the Collection page:
Change “Owner” to “Collection owner”
Change “Users” to “Collection users”
DT-897
=> feat: change collection terminology based on UR

dataworkspace/dataworkspace/apps/data_collections/admin.py, dataworkspace/dataworkspace/apps/data_collections/models.py, dataworkspace/dataworkspace/templates/data_collections/collection_form.html
So we can see the details of Collections in Django admin without needing to open each one, the following columns are being added:
- Datasets (total number)
- Dashboards (total number)
- Users (total number)
- Notes (Text snippet, ie truncated) - we just need to see if Notes have been added. It isn’t important to be able to read the whole string.
=> Feat: DT-915 - add columns to collection admin list display

dataworkspace/dataworkspace/apps/datasets/utils.py
The row count query was failing for dataset queries with filters. This was due to the way the query and the where clause were joined. 
DT-944
=> fix: ensure row count works for queries with filters

.circleci/config.yml, Makefile
Shaving unit test timings from about 10 minutes to approx 3-4 minutes using parrallelism.
=> fix: improving unit test timings 

dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html
The Manage this dataset link (or equivalent of) on visualisation pages does not seem to appear for superusers.
=> fix: allow superusers to manage catalogue item

dataworkspace/dataworkspace/apps/data_collections/views.py
We want to include people finder link as an enhancement to the access request (this person has asked for access - view their profile)
=> feat: include people finder link in request access for collections

dataworkspace/dataworkspace/tests/test_admin.py
The test_create_chart function for some reason can cause some tests in test_admin.py to fail, since if test_create_chart runs, then the times on these assertions end up an our off. Moving these times out of UK summer time is a bit of a guess, but it seems to fix the issues. Potentially the test_create_chart function causes some setting in the application or the database that persists to the next test? Not sure.
This wasn't found until we started investigating parallelising tests, where different sets of tests would run on different instances in different orders.
Potentially this commit is hiding a production issue to do with daylight savings/time zones, but I think we're just going to have to live with it - some things being an hour off, for our use cases, we can live with
DT-270
=> tests: make tests less flakey by moving them out of UK summer time

test/test_application.py, test/test_application_1.py, test/test_application_2.py, test/utility_functions.py
It looked like the test decorator was causing pytest to consider the test as being un utility_functions.py. This is fine for pass/fail, but it was reporting timings are part of that file, which then messed up the test parallelisation in CircleCI
DT-270
=> build(ci): inherit from built in asyncio test

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html, dataworkspace/dataworkspace/templates/data_collections/request_access_to_collection_form.html
Request from content designer to increase the following on request access for collections page:
- the margin between the button and the footer an extra 10px
- the margin between the field and the buttons by  10px
and for the collection detail page to have govuk-body-s be used instead of govuk-body for the following:
- The name of the owner and their email address underneath the title
- The names of users underneath the title
- The link ‘View and edit collection users’
=> fix: spacing adjustment for request access page and text resizing of collection detail

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/templates/datasets/search_authorised_users.html
Minor issues regarding the wording due to the waffle flag that has been put in place
=> fix: ensure wording for user search form is correct dependent on flag

dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/search_authorised_users.html
This is a follow on from [DT-859: Ability to give users access to datasets/dashboards in bulkREVIEW](https://uktrade.atlassian.net/browse/DT-859) to allow the user to choose and add multiple users at the same time.
Note: IAO/IAMs may be adding up to 1,000 users at once, so it needs to accommodate this. Pagination is not in-scope at the moment. We could add that later if necessary.
It includes:
Checkboxes against each valid user
A button to add the selected users in one go
=> feat: allow user to select checkbox for specific user from list

dataworkspace/dataworkspace/apps/datasets/views.py
Searching for authorised users to add to dataset now retains the search data in the textarea upon displaying results, which it previously did not.
=> fix: dataset authorised users search preservation

dataworkspace/dataworkspace/apps/applications/utils.py, test/test_application.py, test/utility_functions.py
Suspect this was just an oversight that it wasn't done when the authorisation by email domain feature was added
DT-984
[DT-984]: https://uktrade.atlassian.net/browse/DT-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow authorisation by email domain for visualisations

dataworkspace/dataworkspace/apps/datasets/views.py
Ned Burton is trying to add a group of users to the Business Intelligence dashboard (https://data.trade.gov.uk/datasets/61a8066f-a3b9-4b59-baf3-ac39b663897f/search-authorized-users/408). However, a number of valid users are refusing to be added due to case sensitivity
=> fix: update search query to ignore case

dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/core/utils.py
This is a step towards granting custom visualisations access to MLFlow (which uses JWT tokens for auth) independently from the user that launched it
https://trello.com/c/xmJyHE8k/2-custom-visualisations-for-ml-flows
=> refactor: make generating JWT token independant of user

dataworkspace/dataworkspace/templates/partials/dataset_info.html
User story
As a Data Workspace user, I need to know the Security Classification of data before I use it, so I can use it appropriately
Acceptance criteria
GIVEN that the user is on a catalogue page
THEN the table of metadata contains a new row called “Government Security Classification”
AND the row shows the current classification
AND the row includes a link “About security classifications“
AND the link goes to https://workspace.trade.gov.uk/working-at-dit/policies-and-guidance/guidance/information-classification-and-handling/
=> feat: DT-933 - Display security classification on catalogue pages

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/static/data-grid.js
- Ensure the where and limit clauses are within the inner query so we only count the maximum number of rows we can download
- Fixes a small issue with the grid where an empty first column was displaying the loading spinner
=> fix: ensure row count is limited to <download limit> to speed up grid

dataworkspace/dataworkspace/settings/base.py
This is a very speculative attempt at fixing Quicksight permissions syncing. Quicksight permissions syncing starts, but then just seems to stop. However, notification email sending seems to carry on.
So guessing, but maybe one is blocking the other? At the very least would make logs less noisy.
=> feat: disable sending of notification emails

dataworkspace/dataworkspace/apps/applications/spawner.py
Create two separate except clauses to deal with other errors where it should be STOPPED (since I think in the case of other errors there is a good chance that the tool has died and then the IP address re-used)
=> fix: catch spawning ThrottlingException within ClientError

dataworkspace/dataworkspace/apps/applications/utils.py
I've seen "tuple concurrently updated errors" when granting privileges on the database. Our locking means this shouldn't happen. But it has. If it does, we at least do the remaining users.
=> feat: carry on syncing quicksight users even if some failed

dataworkspace/dataworkspace/settings/base.py
This reverts commit db276b64b83ac065ed33437db2914f1a81643ef1.
Now manually syncing Quicksight users, and have changed it to not stop syncing all Quicksight users at the first exception, so re-enabling the sending of emails.
=> Revert "feat: disable sending of notification emails"

dataworkspace/dataworkspace/apps/core/utils.py
PostgreSQL's LIKE must match the entire pattern, and without the % it would have looked for roles that are exactly `_team_`, rather than just starting with `_team_`
=> fix: revoking team role from a user's role

dataworkspace/dataworkspace/templates/spawning.html
GIVEN that the user launches a tool and sees the launch screen
THEN the screen includes new security information in this PR
AND the link to the Data Workspace catalogue is https://data.trade.gov.uk/
(behind a feature flag)
=> feat: DT-1000 - Security Classification message on Tool launch screen

infra/ecr.tf, infra/ecs_main_mirrors_sync.tf, mirrors-sync-cran-binary/Dockerfile-rv4, mirrors-sync-cran-binary/build.R
Pre-compiles packages and pushes them to our binary mirror bucket for R v4. These packages can then be used by our tools.
Deleted config for jobs that are now run in https://github.com/uktrade/data-flow/blob/master/dataflow/dags/mirrors_sync_pipelines.py, so I think it was possibly an oversight they weren't deleted earlier.
=> Added new dockerfile for rv4

dataworkspace/dataworkspace/templates/partials/dataset_info.html, dataworkspace/dataworkspace/templates/partials/dataset_info_additional.html
To accompany the new Government Security Classification, can we move Personal data immediately after it in the metadata table, and “Restrictions on usage” after that.
Can we also change the names to:
Personal data (small d)
Usage restrictions (shorter)
Could we also move the Summary to the top (above Government Security Classification).
=> feat: DT-1089 - update dataset summary

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
The sync of permissions currently uses email address to match users, but users sometimes have more than one email address. This is causing problems where users cannot access QuickSight because the "wrong" email address has been synced.
Can we change the sync to match users on SSO ID instead, since this is unique and there is only one for each user?
(FYI this also seems to be affecting Your Files uploads for this user)
=> fix: get quicksight user by SSO id instead of email

dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
To accompany the new Government Security Classification, can we move Personal data immediately after it in the metadata table, and “Restrictions on usage” after that.
Can we also change the names to:
Personal data (small d)
Usage restrictions (shorter)
Could we also move the Summary to the top (above Government Security Classification).
=> feat: add security classifications to ref dataset and reorder

dataworkspace/dataworkspace/apps/applications/utils.py, infra/ecs_main_admin.tf
There is often confusion when sharing quicksight dashboards due to the seperate READER and AUTHOR users. While we would like to have a single user for these, in the meantime this PR replaces the {user.email} in the name of READER users with their {sso_id}. This should hopefully hide these fromthe options when sharing a dashboard.
This includes a fix to correct the embed role for non prod environments, an oversight from previous changes to quicksight namespaces
=> feat: replace user email with ssoid to hide reader accounts when sharing dashboards

dataworkspace/dataworkspace/apps/datasets/views.py
Minor fix to event logs recording grid view twice and correcting reference datasets
=> fix: event log recording grid view twice

dataworkspace/dataworkspace/settings/base.py, dataworkspace/start-celery.sh
After some investigation around permission syncs and other tasks that hinted
that tasks weren't running due to contention for a limited resource. This is a
speculative change that increases the limit for db connections for those tasks.
We are deliberately not increasing limit everywhere to avoid hitting the max
number of connections on the db itself.
=> Increased the max number of db connections available for quicksight celery tasks

dataworkspace/dataworkspace/apps/datasets/utils.py
The job is set to run every 5 minutes, but looks like the job can in some cases take more than 5 minutes. Not really sure how long the "timeout" value should be - this is the maximum time the lock can be held. Maybe this is too short. However, it's still longer than now which is essentially "0" beceause there is no lock
Suspect this could be a contributing factor to various background jobs not running - if many send_notification_emails jobs were running, for various reasons they could have blocked others.
DT-1162
=> feat: avoid running more than one send_notification_emails task at a time

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
The Manage link/screen is visible to users on Source datasets but not on Data cuts. 
Graham has checked with Anthony and there are no concerns about adding it.
Can we reveal the Manage link for superusers so that they can edit data cuts on the front-end?
=> feat: DT-1136 - Reveal manage screen for superusers on data cuts

dataworkspace/dataworkspace/templates/datasets/charts/filter_chart_data.html, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table.html, dataworkspace/dataworkspace/templates/running_base.html
Reference for awaiting security classification in some places is incorrect. This is a PR to correct to ensure security classification is displayed appropriately everywhere
=> fix: correct model reference to security classification

dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html
The screen to manage catalogue items at data.trade.gov.uk/visualisations doesn’t have an option to add/manage a security classification. This needs to be added to ensure that dashboards have a classification before being published.
=> feat: DT-1166 - add security classification to visualisation

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/templates/admin/reference_dataset_changeform.html
Some reference datasets cannot be edited in Django Admin because it times out. 
This is preventing the Datasets and Analysis team from editing reference datasets. This is my attempt to fix this problem.
=> fix: attempt to make reference datasets admin screen load faster

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
As part of work done to assist D&A ingesting DW catalogue pages into data flow, creating this ticket to expose quicksight identifier. To note - supersets are excluded
=> feat: add quicksight identifier to API endpoint

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
In API the quicksight ID has been called "visualisation_type", this renames it to quicksight ID to ensure there is no confusion when working with the endpoint
=> fix: correct quicksight_id to have an appropriate name

dataworkspace/dataworkspace/apps/datasets/views.py
After discussion with PM, it has been agreed data cut custom queries will be recorded under a different key/value pair in the event log extra dict.
=> feat: implement separate dict pair for data cut custom query data grid event log

dataworkspace/start-celery.sh
Allow us to configure the max db connections from celery. This is needed to workaround the issue we are having with connections getting exhausted on dev
=> fix: allow for setting default num of celery db connections

dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/templates/errors/error_403.html, dataworkspace/proxy.py
Adds the user's current peer IP on the 403 error page. 
When a user is denied access to due to their IP not being in the whitelist we have no way to tell what is going wrong. Adding the IP to the user facing page means we can ask for a screenshot of the error. If the IP is not part of our whitelist we can at least tell that either their zscaler is disabled or incorrectly configured somehow.
=> feat: display client ip on the 404 page

dataworkspace/dataworkspace/templates/quicksight_running.html
User requested that dashboards can be pre-filtered via links.
QuickSight can use URL parameters to preset controls (among other uses) which could be very helpful for the reuse of dashboards.
However, the parameters don’t do anything on published dashboards, probably because we aren’t passing them through to the iframe.
=> Feat: Enable published dashboards to use QuickSight parameters

dataworkspace/dataworkspace/templates/datasets/index.html
Since the new Publisher tag category was created, this is a better nugget of info than Source. However, Source is shown on search results and Publisher is not. Source is often blank, so this is unhelpful.
We are going to review the user needs soon, but can we at least swap Source for Publisher in the immediate term?
=> feat: swap source with publisher

.circleci/config.yml
This includes a small change to the commands that copy out test results from the containers. I suspect that the bump of image has a more recent docker/docker-compose in it, which results in slightly differently named containers.
=> ci: move to better supported CircleCI base image

.circleci/config.yml, Makefile, README.md, docker-compose-test.yml, docs/development/remotedebugging.md
* Changed `docker-compose` to `docker compose` to match latest syntax [(soon to deprecate)](https://docs.docker.com/compose/gettingstarted/)
* Removed -f references to default file
=> Docker-compose to docker compose and -f removal

dataworkspace/dataworkspace/apps/explorer/views.py
Fixes issue where an `UnboundLocalError` was thrown when the query was not found.
=> fix: show empty headers/data in case where query cannot be found

CONTRIBUTING.md, docs/architecture/components.md, docs/contributing.md, docs/data-ingestion.md, docs/deployment/aws.md, docs/development/enhancedtables.md, docs/development/running-locally.md, docs/development/running-tests.md, docs/stylesheets/extra.css, mkdocs.yml
It feels less confusing to have have on 2 sides, top and left, rather than 3. Some titles in the toc went onto multiple lines, which looked very messy on the left hand nav, so this change include shortening them.
=> docs: integrating nav and toc, unhiding nav

docs/development/running-locally.md, superset/Dockerfile, superset/create-editor-role.sql, superset/start-dev.sh, superset/start.sh
This change does a number of things
- Makes the Editor role setup no longer brittle with respect to database ID values
- And specifically, allows permissions to be configured by name
- Removes the manual step required both locally and in production
- Adds the following Editor permissions found to be required by recent Supeset:
can post on TabStateView
can put on TabStateView
can delete on TabStateView
can recent activity on Superset
all_database_access on all_database_access
can write on ExploreFormDataRestApi
can read on ExploreFormDataRestApi
can execute sql query on SQLLab
can recent activity on Log
=> feat: more robust Editor role setup for Superset

docs/development/running-locally.md
It looks like the env file file is needed by docker compose even if _not_ running `--profile superset`
=> docs: ensure Superset .env file is created even if not running Superset

Dockerfile, dataworkspace/dataworkspace/settings/base.py, requirements-dev.txt, requirements.in, requirements.txt
Having a look at what was being used before, https://github.com/jneight/django-db-geventpool, suspect there are a few race conditions in the database connection pool code. We could fork (and we did try that), but
- It felt a bit like reinventing the wheel
- It used very little gevent-specific code
So, opting to use https://github.com/altairbow/django-db-connection-pool, a thin layer over SQLAlchemy's database connection pooling code, with the hope that with SQLAlchemy's popularity, it would address these race conditions, and be generally more robust. Note that because of gevent's monkey patching, using gevent with the pool _should_ work fine.
This change includes moving from psycopg2-binary to psycopg2 since https://github.com/altairbow/django-db-connection-pool requires that. It appears …
=> build(deps): use sqlalchemy's database pool

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/apps/api_v1/eventlog/views.py, dataworkspace/dataworkspace/apps/api_v1/mixins.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py, dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
Allow for filtering by timestamp on tool query and event log api endpoints
=> feat: allow for filtering api responses by timestamp

dataworkspace/dataworkspace/apps/datasets/views.py
The “Admin only options” appear to all users when they should only show for admin users. Can they be hidden unless the user is an admin?
=> feat: Admin only filter on search visible to all users

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/templates/partials/request_access.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py, test/test_application_1.py
When a user doesn’t have Tools access, the catalogue page tells them they will “need to request access to analyse this data” just above the data tables.
Users think this means they don’t have access to the data itself, but the message is actually just about access to Tools. This is very confusing. We discussed it in the team and agreed that this message can simply be removed.
=> feat: DT-1344 - Remove tools access message from catalogue page

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisation_datasets.html, dataworkspace/dataworkspace/tests/applications/test_views.py
This is the first step in a larger piece of work - to give visualisation developers the ability to write derived table SQL pipelines themselves. For now, just making them visible.
For now, it's only the Data Science team that are expected to have pipelines created for them
=> feat: show SQL for derived tables in application schema in visualisation datasets page

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/applications/test_fixture_activity_stream_sso_john_smith.json, dataworkspace/dataworkspace/tests/applications/test_fixture_activity_stream_sso_john_smith_multiple_emails.json
Trying to create inactive sso users has generated over 9 million errors in sentry. This fix ignores inactive when syncing
=> fix: ignore inactive sso users to quiet noise in the logs

infra/rds_admin.tf
During to last weeks outage, the storage size on the prod admin db was bumped to 100GB. This fix updates the config to match
=> fix: bump admin db storage from 60 to 100 GB

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
- Make returning the row count optional when fetching grid data
- If no grid filters are applied, display the row count from the metadata table
=> feat: do not calculate row count unless absolutely necessary

dataworkspace/dataworkspace/templates/running.html
This was breaking the html/js further down the page
=> fix: iframes must have a closing tag.

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisation_datasets.html, dataworkspace/dataworkspace/tests/applications/test_views.py
This allows visualisation developers to edit the SQL of existing, admin-added, pipelines that populate a visualisation schema, as long as it doesn't add to its set of tables.
This is a stepping stone to more functionality - but it is a fairly straightforward way to allow visualisation developers some ability to iterate on SQL pipelines
=> feat: allow sql editing on visualisation datasets page

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/your_files/utils.py
Fixes an issue where slashes in column names were creating duplicate columns. When an uploaded csv had multiple columns with forward slashes we were only using the last part of the name. 
For example if we had two columns,`business address / line 1` and `home address / line 1`, were were naming both columns `line_1`. This PR removes the forward slash so the columns would be named `business_address_line_1` and `home_address_line_1`.
=> fix: replace slashes in column names with underscores

dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/static/js/grid-utils.js
We no longer use floating filters on the grids so this PR replaces the custom boolean floating filter with a custom popup filter
=> fix: replace floating filter with standard filter for bools

bin/delete-qucksight-users.py, bin/list-notebook-tasks.py, bin/list-quicksight-author-assets.py, bin/list-s3-file-types.py, bin/stop-duplicate-notebook-tasks.py
Adds some scripts to automate some of the tasks we've been asked to do on aws recently.
1. List all authors on quicksight along with the number of assets associated with their accounts
2. Delete a list of users from quicksight
3. Find and stop any duplicate running task defs on an ecs cluster
=> feat: add some scripts to automate some common aws tasks

dataworkspace/dataworkspace/apps/datasets/utils.py
If a dataset has multiple "latest" visualisation sql links mark them all as not-latest and create a new link
=> fix: catch and fix duplicate vis sql links

dataworkspace/dataworkspace/apps/explorer/schema.py
This can cause issues if the query is running and data flow swaps the tables out
=> fix: ignore data flow's temp tables when generating user schemas

dataworkspace/dataworkspace/apps/applications/spawner.py
We are seeing a lot of 400 errors when stopping tasks, hopefully this will shed some light on what they are
=> fix: log failed stop task calls to sentry

dataworkspace/dataworkspace/apps/datasets/models.py
=> fix: don't let broken reference datasets break the metadata syncer

dataworkspace/dataworkspace/settings/base.py
User notifications were being sent every 5 mins, this is now setup to run hourly temporarily. This is to ease db load, while tools are having tough time.
=> less frequent user notifications to help ease db load

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/views.py, test/selenium/test_explorer.py
In order to make Data Explorer load and minimise db load, disable Database tab on Data Explorer. It is trying to access all schemas and tables a user has access to, every time the user loads it.
=> disable database tab on data explorer temporarily

dataworkspace/dataworkspace/apps/core/utils.py
Speed up the user table permission gathering query by not using the `information_schema.table_privileges` view.
=> fix: stop using information_schema for perms queries

dataworkspace/dataworkspace/apps/datasets/models.py
When a reference dataset is added to or removed from the datasets db we need to force a permissions change for all users. Do this by removing the cached tool permissions and schemas for all active users.
=> fix: bust tool/schema cache when a ref dataset is (un)published

dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/tests/data_collections/test_views.py
Fixes the issue where any user could add a dataset to an open collection
=> fix: don't allow non-owner/admin users to edit open collections

dataworkspace/dataworkspace/apps/datasets/views.py
This is to work around the fact that users can have either @trade or @businessandtrade emails currently. We are at whim of the SSO service as to which one a user has. This change allows us to search for a @trade user but if no user is found, return an @businessandtrade user
=> feat: if no match for an email exists widen the search

dataworkspace/dataworkspace/static/dialog.js, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
The data tables and data links for a datacut have been merged into one list known as "Data", and the corresponding links have been updated to display download modals when clicked.
=> Sub feat/combine data tables

dataworkspace/dataworkspace/apps/api_v2/recent_items/urls.py, dataworkspace/dataworkspace/apps/api_v2/recent_items/views.py, dataworkspace/dataworkspace/apps/api_v2/urls.py, dataworkspace/dataworkspace/tests/api_v2/recent_items/test_recent_items.py
Ticket [DT-1749](https://uktrade.atlassian.net/browse/DT-1749)
This change adds a new endpoint for the users recently visited datasets.
[DT-1749]: https://uktrade.atlassian.net/browse/DT-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add recent catalogue items endpoint

dataworkspace/dataworkspace/apps/datasets/data_dictionary/service.py
=> fix: use field name rather than column name when updating ref dictionary

dataworkspace/dataworkspace/apps/your_files/tasks.py, dataworkspace/dataworkspace/settings/base.py
Hourly (for now) task to calculate the "your files" storage size for all active users.
This only logs the outputs currently. The next step will be to store this data and make it accessible to admins (and finally users)
=> feat: task to log stats on s3 user prefixes

infra/ecs_notebooks_notebook.tf
This gives users in Data Workspace the ability to list the contents of the mirror bucket so they can see what's been mirrored, .e.g. from Python scripts inside tools.
At the moment however, I suspect for a user to be able to use this, they would have to have the Tools access IAM role arn manually cleared in their user record, which would force their IAM role to be reconstructed with the new permission. I'm not sure of a way to do this in bulk right now.
=> feat: allow users to list the mirror bucket

dataworkspace/dataworkspace/templates/datasets/details/sourceset_dataset.html
This simplifies the error message displayed to a user when a pipeline to a database table fails, so that we're no longer implying it is being resolved when this may not necessarily be the case
* [] Have tests been added to cover any changes?
=> Simplify error message where pipelines have failed to update

dataworkspace/dataworkspace/templates/applications/quicksight_running.html
This updates the version of the Quicksight embedding SDK to the latest.
This is done to hopefully fix issues with external links in QuickSight dashboards. They used to to work, but now they seem to open blank tabs. Invgestigating the dev console showed there is some issue to do with a null "opener", which suggests potentially the old SDK is hitting on a security barrier that is now present for some reason.
=> feat: use latest Quicksight embedding SDK

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This change enables the user to filter datasets that they are a direct contact for.
=> Add contact filter to data catalogue page

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/tests/core/test_views.py, test/pages.py, test/test_application_1.py
This change just removes a feature flag that was used to toggle the new homepage. Now post release we don't need this anymore.
=> Remove homepage feature flag

dataworkspace/dataworkspace/apps/applications/utils.py
If a tool has failed to start, there is a chance the hostname was not set. If you then try to view the details of that tool in the admin you get a 500 error as it expects the hostname to not be None.
Workaround this by raising an "expected" exception
=> fix: Catch `None` hostname when calculating metrics for app instance

dataworkspace/dataworkspace/apps/applications/admin.py
The admin application instance report has been out of service for quite some time due to django updates which require output fields on aggrgated queries
=> fix: app instance report 500 error due to missing output fields

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/explorer/_base.html, dataworkspace/dataworkspace/templates/partials/beta_banner.html, dataworkspace/dataworkspace/templates/partials/search_bar.html, dataworkspace/dataworkspace/tests/explorer/test_views.py
The phase banner has been removed and the Beta tag has moved to the header next to Data Workspace.
Also contains a tiny fix for a link in the search bar which was linking to the live site instead of local.
=> Remove phase banner and move beta tag to header

dataworkspace/dataworkspace/apps/maintenance/test_maintenance.py, dataworkspace/dataworkspace/settings/base.py
This PR makes  the `/healthcheck` page exempt from returning a 503 when maintenance mode is on. This was causing issues in deployments where maintenance mode was on prior to deploying/reploying
=> Exempt healthcheck page from maintenance_mode

infra/ecs_main_admin.tf, infra/ecs_main_gitlab.tf, infra/rds_admin.tf
This includes the changes required to move the Terraform AWS provider to 5.35.0. This is done because we're trying to make it easier to apply, and don't want to waste time solving rough edges that will have to be changed anyway when we eventually upgrade.
Note that when applying the terraform you will probably have to run `terraform init -upgrade` to allow selection of the new version.
=> refactor: move to Terraform AWS Provider 5.35.0

infra/ecs_main_admin.tf, infra/ecs_main_dns_rewrite_proxy.tf, infra/ecs_main_dns_rewrite_proxy_new.tf, infra/ecs_main_flower.tf, infra/ecs_main_gitlab.tf, infra/ecs_main_healthcheck.tf, infra/ecs_main_mirrors_sync.tf, infra/ecs_main_mlflow.tf, infra/ecs_main_prometheus.tf, infra/ecs_main_sentryproxy.tf, infra/ecs_main_superset.tf, infra/ecs_notebooks_jupyterlab_python.tf, infra/ecs_notebooks_notebook.tf, infra/ecs_notebooks_remote_desktop.tf, infra/ecs_notebooks_superset.tf, infra/ecs_notebooks_theia.tf, infra/ecs_pgadmin.tf, infra/ecs_rstudio.tf, infra/ecs_rstudio_rv4.tf, infra/ecs_user_provided.tf
This changes the use of the deprecated template_file provider to the now built in templatefile function in terraform.
This is done because the template_file provider as no current version for the arm processor (e.g. modern macs), and so it should make it easier to apply the terraform.
=> refactor: move from template_file to templatefile

cypress/e2e/homepage/dashboard.cy.ts, cypress/e2e/homepage/search.cy.ts, dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/datasets/data_catalogue.html, dataworkspace/dataworkspace/templates/partials/search_bar.html, dataworkspace/start-e2e.sh
This change persists the search query to the data catalogue page. UX behaviour:
1. User is on the homepage
2. User searches the term "Data"  
3. User gets directed to the "data catalogue" page showing results based on the search term "data"
4. User can see the term "data" is pre-populated in the search bar input field
=> Fix/DT-1790 Persist search term to the data catalogue page

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_admin.py
Custom visualisation description has a minimum word limit of 30.
=> Validate visualisation catalogue item description to at least 30 words

infra/ecs_main_mirrors_sync.tf
This only creates a aws_cloudwatch_log_subscription_filter on the mirrors sync job if configured to do so. This is consistent with the other cases of aws_cloudwatch_log_subscription_filter
(Note we might not even be using the mirror sync job any more? But leaving investigating that to another time)
=> feat: only apply cloudwatch subscription filter if configured to do so

infra/vpc.tf
This is so we can create environments not peered with PaaS
=> feat: only configure with PaaS if configured (part 2)

infra/rds_datasets.tf
This makes it easier to setup new Data Workspace environments because the default will never go out of date.
=> feat: use default engine version for database

infra/s3_uploads.tf
The ACL way previously used no longer works with the security settings of new buckets
=> refactor: use way of configuring upload bucket logging that works with new buckets

infra/container-tag.sh
Starting up a new Data Workspace environment results in task definitions refering to Docker containers with a tag, so ending in just ":", which is not valid.
Not sure on the best default, but "latest" is probably reasonable, because that usually (always?) exists once there is an image in the ECR repository.
=> fix: bootstrappable image tags for task definitions

infra/environment-template/main.tf, infra/main.tf, infra/rds_datasets.tf
Adds datasets db engine as a variable in the infrastructure.
This is a needed step in allowing for non-aurora datasets dbs
=> feat: make rds datasets db engine configurable

infra/ecs_main_admin.tf, infra/main.tf
This is because there was high cpu usages for users, therefore we added more instances to mitigate this.
It should be safe as each instance will use no more than 37 data base connections and even during a deployment, we will never have more than 10 instances including celery so we will never use more that 370 data base connections, which is less than the 403 which the data base supports.
=> Adding the ability to customise the number of admin instances.

infra/ecs_main_superset.tf, infra/route_53.tf
This PR makes use of the new `superset_on` terraform variable to allow us to enable/disable the running onf superset on an environment
=> feat: allow toggling of superset as a service

dataworkspace/dataworkspace/utils.py
Data explorer was incorrectly expecting a timestamp for columns with an OID of 1186. The correct type for this OID is interval.
=> fix: ensure data explorer can handle interval data types in queries

dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py
Tool access is not mandatory for source dataset. If the access request is for a source set then it now redirects to the summary page instead of continuing to the request tools page.
=> Skip tools access request for source data set

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
Fixes issue where quicksight user emails were never updated and users were not receiving notifications
=> fix: set quicksight email to DW user email when syncing users

dataworkspace/dataworkspace/templates/datasets/partials/dialog.html
This change removes a tabindex attribute from the download dialog to stop it focusing on the content when opened.
=> DT-1851/Remove focus on modal content

docker-compose.yml
The path to the sibling directory where Superset is expected to be found when developing locally was incorrect.
=> chore: fix local Superset profile

dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/templates/_main_no_container.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_cut_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_sourceset_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/reference_dataset_preview.html, dataworkspace/dataworkspace/templates/datasets/partials/breadcrumbs.html, dataworkspace/dataworkspace/templates/datasets/partials/grid-view-saved.html
Moved the breadcrumbs for all data preview pages outside of the main content block. This is so that the 'Skip to content' highlights the actual main content and not the breadcrumbs.
Also fixed the save grid banner as it was selectable when tabbing despite being hidden. It now is only selectable when visible and the focus will switch to the banner when it becomes visible
=> A11y: Move breadcrumbs from main content of data preview pages

cypress/e2e/data-catalogue/data-grid.cy.ts, dataworkspace/dataworkspace/static/data-grid.js
When setting a filter on a dataset that is of type boolean, the reset view button should now clear the filter.
=> Reset view button resets boolean type column filters

dataworkspace/dataworkspace/templates/datasets/partials/filter_button.html
Add aria-label to filter label so screen readers / users who cannot see the 'x' on a filter can know how to remove a filter.
```
<button data-id="1" data-module="remove-filter" data-filter-type="data_type" class="filter-button" aria-label="Remove filter Type: Source dataset">
✖&nbsp;Type: Source dataset
</button>
```
=> a11y: Add aria-label to highlight how to remove a filter

dataworkspace/dataworkspace/apps/core/utils.py
This removes what is thought to be unnecessary locking - although we do need locking when GRANTing SELECT to a table, because the permissions are all stored in one field in pg_class, GRANTing a role to another role is done by adding a row to pg_auth_members, which shouldn't need locking.
This is done as a small step towards hopefully more robust tools launches - while this change might look like it decreases robustness, locking adds to slowness, and if it turns out we _do_ need this locking, we need to known now, as we're about to build on the pattern that assumes that changes to role membership doesn't need locking.
There are existing integration tests that cover at least the main parts of tools being granted enough permissions to access datasets. While not impossible to make a test that …
=> feat: remove some of the locking when granting to a role

dataworkspace/dataworkspace/apps/core/utils.py
This fixes an error introduced in
https://github.com/uktrade/data-workspace-frontend/pull/3108/files - when granting missing roles to the master user it attempted to use a closed cursor, i.e. outside the context manager in which it's open.
=> fix: cursor already closed error when granting db permissions error

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py
This is a bit of a workaround because it's a touch more complex than thought to have non-published source tables (without destroying their historical log info)
Hopefully this will be followed by some sort of unpublish/soft delete for source tables.
=> feat: filter out dit schemas from views and permissions

dataworkspace/dataworkspace/templates/_base.html
When using a screen reader, the number of active tools should be read out. The example below would say:  "You have 3 tools running"
=> A11y: Add aria-label to tools notification

dataworkspace/dataworkspace/apps/core/utils.py
Because we now check permissions directly on pg_namespace, we don't need to exclude information_schema or pg_* schemas because users are never granted permissions on them directly.
=> refactor: slightly simplier query fetching existing schema perms

dataworkspace/dataworkspace/apps/core/utils.py
This fixes an issue where there can be errors when creating tools credentials, but they would be hidden.
=> fix: don't swallow exceptions when locking in grant credentials flow

dataworkspace/dataworkspace/apps/core/utils.py
Quicksight users were getting an error where there were too many connections, so increase the limit for them. Keeping the limit for general tool users low, as people can accidentally make thousands of connections and use all the connections available in the database. However, this is much harder to do in Quicksight.
=> Changing the qs limit to 50, keeping other tools at 10

dataworkspace/dataworkspace/apps/core/utils.py
Especially when the database is under load, querying permissions on pg_class is taking quite a while and causing tools to fail to load. We are manually clearing up pg_class permissions separately, which should help, but to see if can get tools working now, the best thing that can think of is to increase the timeout.
=> feat: increase statement timeout when creating credentials

dataworkspace/dataworkspace/apps/core/utils.py
This should make it just a touch faster to query for existing tables when syncing permissions.
The previous version would be slower for 2 reasons:
- Querying views that each do more than they need to for our purposes.
- And the fact 3 views were queried, when 1 query on pg_class is all that's needed.
This is done because according to RDS performance insights, the previous query had an every latency of ~30 seconds, which is far far too much for something that should be really cheap.
=> perf: slightly faster checking for existing tables

dataworkspace/dataworkspace/apps/core/utils.py
This stops REVOKE of an app's own role when loading it by not including it in the list of any "shared" roles it may have.
(Realistically an app will not have any access granted to shared roles, unless it was done manually somehow. This code is more for human user's roles that are granted team membership.)
=> fix: don't try to revoke an app's own role when loading

dataworkspace/dataworkspace/apps/applications/utils.py
This makes sure that the GRANTs on the master user are REVOKEd. This is done because it seems there are very high performance implications for the master user having many roles.
=> fix: make sure to cleanup GRANTs on master user when cleaning up users

dataworkspace/dataworkspace/apps/core/utils.py
The recent changes where the master user doesn't have the user's roles granted. However, it looks like to grant/revoke various things, the master user has to be a member of the user's role. This change does that.
=> fix: ensure can grant and revoke shared roles

dataworkspace/dataworkspace/apps/datasets/admin.py
When we released #3141 we forgot to update the JS in the admin area for visualisation catalogue items. As a result jQuery was undefined causing the select drop downs to fail in admin. This change enable the jQuery object to be initialised before we need to call it.
=> Fix the select dropdown in admin

dataworkspace/dataworkspace/static/js/react/features/your-files/App.scss, dataworkspace/dataworkspace/static/js/react/features/your-files/popups/UploadFiles.jsx
Ticket [DT-1920](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-1920)
Currently the buttons are covering the files listed in the table if the user has chosen more than 5 files to upload.
This change now limits the table to show a maximum of 5 files, anymore than 5 then the user has to scroll.
1. Go to "Your files" by visiting `/files`
2. Try uploading more than 5 files
3. You should only 5 in the table and the table should now be scrollable
[DT-1920]: https://uktrade.atlassian.net/browse/DT-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow scrollable table when uploading more than 5 files

dataworkspace/dataworkspace/static/js/react/features/your-files/popups/UploadFiles.jsx
This PR is to wrap one line file name and type when user is uploading a file on their folder.
=> fix/ DT-1921 update css class name for type and name on upload modal

dataworkspace/dataworkspace/static/js/react/features/your-files/popups/UploadFiles.jsx
This change adds a message to the top of the "Upload files" modal letting users know where the files will be stored depending on what the file sizes are. This message also contains a link that will direct users to the help centre which gives them more information and guidance around uploading files and file size limits.
1. Visit the file upload tool `/files`
2. choose some files to upload
3. View the message above the table containing files to be uploaded
=> feat/DT-1913: Add upload location message to upload files modal

dataworkspace/dataworkspace/static/js/react/features/your-files/popups/UploadFiles.jsx
This change updates the warning message on the file upload modal to a shorter message thats clearer to the user.
1. List the file upload tool /files
2.  Choose some files to upload
3. View the message below the table containing files to be uploaded
=> refactor/DT-1923: Update the warning message on the upload files modal

cypress/e2e/data-catalogue/bookmarked.cy.ts, dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/datasets/data_catalogue.html
Currently the bookmarked icons are not showing when a user searches within the data catalogue page. However they will show if you visit the data catalogue page directly or reload the search results. This change fixes this bug and will show bookmarked icons on datasets regardless of how you use and view the data catalogue page and its search functionality.
1. Visit the data catalogue page `datasets`
2. Bookmark a dataset
3. Reload the page and you should see that the bookmark icon has a solid fill colour indicating that it has been bookmarked
4. Now refine/narrow the search results by entering the title of the dataset you bookmarked
5. You should now see an updated results page with your dataset listed and again, a solid fill colour on the bookmark icon
=> fix/dt-1964: Bookmark should show when searching catalogue

dataworkspace/dataworkspace/static/js/react/features/your-files/App.scss
This PR is to update status tag style. We want to amend these for consistency and for best practice to follow GDS equivalent, but also Data Workspace equivalent:
=> fix/DT-1931 update status tag style to match gds/data workspace

dataworkspace/dataworkspace/apps/datasets/manager/forms.py, dataworkspace/dataworkspace/apps/datasets/manager/views.py, dataworkspace/dataworkspace/apps/your_files/forms.py, dataworkspace/dataworkspace/apps/your_files/views.py, dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table_column_config.html, dataworkspace/dataworkspace/templates/your_files/create-table-confirm-data-types.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/your_files/test_views.py
This change enable users to auto generate an ID column when creating new tables from CSV's.
Before testing both journeys create two CSV files. One that includes an ID column and one that doesn't.
**Catalogue page journey**
1. On the catalogue choose a source dataset that you have access to
2. Within the "Data Tables" section, alongside a table in the list click "Update or restore table"
3. Click the "Choose file" button and upload the CSV file that doesn't have the ID column and click "Upload CSV"
4. Scroll to the bottom of the page and where it says "Do you want to generate an ID column?" click "yes" and submit
5. After the new table has been created go back to the data catalogue page and click on the table you updated
6. You should now see a new ID column generated in the table
Repeat …
=> feat: DT-1834 add option to generate an Id column

dataworkspace/dataworkspace/apps/core/utils.py, requirements-dev.txt, requirements.in, requirements.txt
This is technically a refactor given the existing behaviour of pg-sync-roles, and it doesn't give _that_ much. However, in later changes we'll
- Be moving more logic into pg-sync-roles
- Fixing an issue that results in an accumulation of roles on tables
=> refactor: use pg-sync-roles for creating and maintaing database users

dataworkspace/proxy.py
We have a known streamlit bug in Data Workspace Visualisation in which we can't deploy a streamlit app based on streamlit version > 1.28. The visualisation, in preview and in deployment, would not load on Chrome, unlike Safari and Firefox.
streamlit runs on a host of websockets to provide interactivity. Data Workspace, when reverse proxying connections, handles the [websocket protocol upgrade mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism) by only expecting [one](https://github.com/uktrade/data-workspace-frontend/blob/52ba47019e869c21b2739bc4cf0b984c947c2fe6/dataworkspace/proxy.py#L806C1-L807C52) incoming subprotocol, while multiple subprotocol upgrades may be [requested](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism). …
=> fix: accept multiple secure websocket protocols

dataworkspace/dataworkspace/static/js/react/components/InlineFeedback/InlineFeedback.stories.tsx, dataworkspace/dataworkspace/static/js/react/components/InlineFeedback/InlineFeedback.test.tsx, dataworkspace/dataworkspace/static/js/react/components/InlineFeedback/index.tsx, dataworkspace/dataworkspace/static/js/react/components/InlineFeedback/mocks.tsx, dataworkspace/dataworkspace/static/js/react/components/index.tsx, dataworkspace/dataworkspace/static/js/react/constants.ts
Ticket [DT-1990](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-1990) 
This change adds a new inline feedback component which will initially be mounted on the data catalogue page. This component will help collect data around how helpful the page is to the user and how we could improve it. This change ONLY adds the component to the codebase so its not being surfaced anywhere in the UI.
To view the component you will need the codebase running locally. Then follow these steps:
1. cd into `dataworkspace/dataworkspace/static/js` 
2. Open terminal and run `npm run storybook`
3. Once Storybook is running you will be able to navigate to the component
[DT-1990]: https://uktrade.atlassian.net/browse/DT-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
=> feat/DT-1990: Add inline feedback component

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
Removed capital letters in regex validator for the basepipeline class so that lower case table names is now enforced.
=> Amend regex in basepipeline form to disallow capital letters

dataworkspace/dataworkspace/apps/core/utils.py
This removes setting settings on permanent roles when creating credentials. Now the settings are only done on the temporary user used to login. This should not have any effect because, from https://www.postgresql.org/docs/14/sql-alterrole.html
> executing SET ROLE or SET SESSION AUTHORIZATION does not cause new configuration values to be set.
and from https://www.postgresql.org/docs/14/view-pg-roles.html about the connect limit specifically
> For roles that can log in, this sets maximum number of concurrent connections this role can make.
=> refactor: remove unnecessary settings on database roles

dataworkspace/dataworkspace/apps/explorer/schema.py, dataworkspace/dataworkspace/tests/explorer/test_schema.py
The Database tab in Data Explorer can be quite slow. It's cached, and uses Ajax on a separate tab to not block the main page load, but it's still not great. By using PostgreSQL catalogue tables even more directly by leveraging pg_shdepend we can speed it up
At busy database times, the previous query took around 45 seconds, and the new around 1 second. At less busy times the difference is less pronounced, the previous query taking ~2 seconds and the new around 0.75 seconds.
As a small bonus, this now properly excludes indexes and sequences by using the 'relkind' field when filtering on pg_class.
The change in the tests is because the previous way automatically included tables granted to the PUBLIC role - the new way doesn't and the user has to have permissions granted explicitly for them …
=> perf: faster database tab (and better exclude non-tables)

dataworkspace/dataworkspace/apps/api_v2/inline_feedback/serializers.py, dataworkspace/dataworkspace/apps/api_v2/inline_feedback/urls.py, dataworkspace/dataworkspace/apps/api_v2/inline_feedback/views.py, dataworkspace/dataworkspace/apps/api_v2/urls.py, dataworkspace/dataworkspace/tests/api_v2/inline_feedback/test_inline_feedback_views.py, dataworkspace/dataworkspace/tests/factories.py
This change adds a REST endpoint which allows the client to add inline feedback data to the database.
=> feat/DT-2010: Add endpoint for inline feedback

dataworkspace/dataworkspace/apps/request_access/forms.py, dataworkspace/dataworkspace/apps/request_access/urls.py, dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/templates/design_system/date.html, dataworkspace/dataworkspace/templates/design_system/textinput.html, dataworkspace/dataworkspace/templates/request_access/self-certify.html, dataworkspace/dataworkspace/tests/request_access/test_views.py
Adds a new page at the `request-access/self-certify` url to allow users to self submit proof they are allowed to access tools.
This PR does not add any logic to save the values in the form, it is just the content with redirects
=> Added page for self certify

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
When a user is a `data_catalogue_editor` of a dataset it should appear under the new filter `Data I am an editor for`. It currently appears under the `Data I own or manage` filter.
=> Filter for 'Data I am an editor for'

dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py
Removed appstream permission (For Stata) from the list of permissions that are granted during self certify as Stata has it's own request access flow
=> Remove Stata permission from self certify flow

dataworkspace/dataworkspace/apps/datasets/views.py
Add spacing between commas in list of Publishers on catalogue pages
To test, add a couple publisher tags to a dataset in Django Admin and view on the catalogue page.
=> Add space between commas in publisher list

dataworkspace/dataworkspace/templates/partials/code_snippets.html
When a user is looking at a table and they select ‘Use this data for analysis at the top of the page’, a link which says ‘View all tools’ should now send the user to the correct page (/tools)
=> Update link in code snippets to redirect to tools page

dataworkspace/dataworkspace/apps/datasets/add_table/urls.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/templates/datasets/add_table/about_this_service.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Ticket [DT-2051](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2051)
This change is the start of the new "add table" journey. 
How to test
1. Visit any data catalogue page
2. Add `/add-table` to the end of the url
[DT-2051]: https://uktrade.atlassian.net/browse/DT-2051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat/DT-2051: Add the first page for the new "add table" journey

dataworkspace/dataworkspace/apps/datasets/utils.py
It's been reported that changing details of VisualisationLinks appear to work, but then are undone within a few minutes. Although we're not 100% sure, it could be due to background tasks that query for VisualisationLink instances, do slow tasks, and then save all the fields of the model instance, and thus undoing any interim changes to the model instance.
We fix this by using the `update_fields` option of the save method to only save the specific fields that should be being saved, and thus not undoing any recent changes persisted in the database.
=> fix: avoid undoing recent VisualisationLink changes

dataworkspace/dataworkspace/apps/datasets/utils.py
It looks like we're running multiple process_quicksight_dashboard_visualisations at once - it's set to start every 5 minutes but it might be taking longer than 5 minutes these days.
By wrapping the code that does the work in a lock this should avoid the problem. This pattern is already in use for other scheduled Celery tasks.
=> fix: avoid multiple process_quicksight_dashboard_visualisations

dataworkspace/dataworkspace/apps/datasets/add_table/urls.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/templates/datasets/add_table/classification_check.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Part of the Add Table flow for the security classification check page.
To test:
Go to a data catalogue page and add `/add-table` to the url (removing #{dataset-name} if there)
Follow the flow and you should get to this page. The header should display the security classification of the dataset
=> Classification check page and tests

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/applications/test_utils.py, dataworkspace/dataworkspace/tests/core/test_utils.py
Ticket [DT-2190](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2190)
This change adds a new Celery task that checks if any users tools certificates have expired. If they have, then a function runs that removes all tools access. This task will run every morning at 5:00am.
[DT-2190]: https://uktrade.atlassian.net/browse/DT-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat/dt 2190 Remove tools access for users with expired certificates

dataworkspace/dataworkspace/apps/core/utils.py
This changes the source_tables_for_app to be more like the source_tables_for_user function in that it uses the Django "values" function to avoid N+1 queries.
This function is used in visualisation previews, and some are being reported as being very slow - to the point of getting 504 errors. It's not a definite that this is the main problem, but I think it shouldn't hurt so at worst this should exclude N+1 as being the problem.
The source_tables_for_user was previously optimised in: https://github.com/uktrade/data-workspace-frontend/commit/d857b2b92456239d87831298b6fc66d6f3a3b2ee
=> perf: speed up preview permissions checks by avoiding N+1 queries

dataworkspace/dataworkspace/templates/datasets/pipelines/list.html
This adds the pipeline type (so "Sharepoint" or "SQL") and the platform ("GOV.UK PaaS" or "Data Workspace AWS") to each pipeline in the /pipelines page.
This is to primarily help the migration off GOV.UK PaaS, so we know what is done and what's left to do, and is a temporary change. However, the pipeline type is apparently useful to see, so that might be left longer term.
=> feat: show pipeline type and platform on pipelines page

dataworkspace/dataworkspace/apps/applications/utils_tools.py
This PR removes the tags from the Tools page for Quicksight and Superset. This is because Superset is no longer new and Quicksight is not so strongly recommended (it's expensive and Superset is stable enough for more general use)
=> Remove tags for QS and Superset in Tools

dataworkspace/dataworkspace/apps/accounts/admin.py
This PR updates the help text presented when granting a user with permission to access QS. This reflects the fact that there is no longer a mannual SSO step, and should hopefully help with resolving issues users may have when acessing QS
=> Update help text for granting QS access to users in Admin

dataworkspace/dataworkspace/apps/core/utils.py
In our PostgreSQL permissions setup, each tool has a temporary database user that is granted the permanent database role of the person launching the tool. We also SET ROLE of the temporary user to the permanent role, so that objects created by the temporary user are then owned by the permanent role.
However, this seems to have performance implications on connecting:
- It increases the "best case" connection time from 0.03s to 0.06s.
- Which doesn't matter too much, but it also increases the frequency of "worst case" connection times, when connection takes about 40 seconds.
So this change makes it so we avoid running SET ROLE for the environments where it's not possible to make objects: QuickSight, Superset and Data Explorer.
This doesn't appear to completely remove "worst case" connection …
=> Reduce connection timeout frequency by avoiding running SET ROLE for contexts that can't make objects

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py, dataworkspace/dataworkspace/apps/datasets/add_table/urls.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/templates/datasets/add_table/upload_csv.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
This is the upload CSV page for the service of adding a table to an existing catalogue page. This work includes validation:
Given a user hasn’t selected a CSV to upload and they press the continue button then an error message should appear above the text input and an error summary should appear at the top of the page saying “Select a CSV”
Given a user has selected a CSV that contains special characters in the name and they press the continue button then an error message should appear above the text input and an error summary should appear at the top of the page saying “File name cannot contain special characters apart from underscores and hyphens
**How to Test**
- Navigate to /datasets
- Add /add-table to the end of the dataset ID
- Click through the flow to get to 'Upload CSV'
- Try …
=> feat/DT-2059 Add Table: Upload CSV

.envs/sample.env, .envs/test.env, dataworkspace/dataworkspace/apps/arangodb/utils.py
This PR specifies the protocl through which ArangoDb should be communicated. This is HTTP in local/test environments and HTTPS remote environments in AWS, given the difficulty of using HTTPS locally
=> Specify per env protol for connecting to Arango

dns-rewrite-proxy/nameserver.py
The dns-rewrite-proxy rewrites and filters certain DNS requests (it was created before AWS could do this with their DNS firewall). One of the things it does it rewrites <host>.<public-domain> to <host>.<private-domain> in tools so that the same domain can be used from outside of tools as well as in (for example, GitLab).
However, the arango host under (for example) data.trade.gov.uk resolves to the internal load balancer, and so we don't need the rewriting, because there is no arango.<private-domain>.
Also the Docker registry has not existed for several years - so this repurposes its entry in the rewrite list for Arango.
=> feat: make Arango's nice domain work from tools

dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py
Ticket [DT-2246](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2246)
This change stops the self certify flow from allowing users to access the visualisation tools. There are no visual frontend changes. All this does is NOT check the "Can develop visualisations" box in admin against the users profile.
[DT-2246]: https://uktrade.atlassian.net/browse/DT-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat/DT-2246: Remove visualisation tool access from self cert

dataworkspace/dataworkspace/apps/applications/spawner.py
This change makes it so custom visualisations not longer inherit the IAM/S3 permissions of the person that happens to start them. It was always slightly strange, and in fact a mild security issue that it was possible.
=> feat: visualisations no longer have IAM/S3 and Arango permissions

Jenkinsfile
This change just removes staging from the production pipeline. We now have a dedicated staging pipeline so we don't need this anymore.
=> chore: remove staging from the production pipeline

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/urls.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
Added v1 API endpoint to expose the custom sql generating data cuts. This is part of larger work to build a pipeline to ingest these into Data Workspace for greater visibility to our users.
=> feat: add data cuts endpoint to expose custom sql

dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Ticket [DT-2295](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2295)
This change removes any assumptions that the database in use is always called "datasets_1". We also shouldn't try to create this if it doesn't exist.
[DT-2295]: https://uktrade.atlassian.net/browse/DT-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/DT-2041: Update database query to stop other environments breaking

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py
This change updates the regex validation in order to allow numbers in the CSV file name when using the "upload a csv" form.
=> fix: update regex validation

dataworkspace/dataworkspace/static/js/package-lock.json
Updates `send` from 0.18.0 to 0.19.0
Updates `express` from 4.19.2 to 4.21.0
Updates `serve-static` from 1.15.0 to 1.16.2
Updates `body-parser` from 1.20.2 to 1.20.3
=> Dependencies 2024-09-23

cypress/e2e/data-catalogue/data-grid.cy.ts, cypress/e2e/data-catalogue/source-dataset.cy.ts, dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py, dataworkspace/dataworkspace/templates/datasets/details/sourceset_dataset.html, dataworkspace/dataworkspace/tests/datasets/test_datasets_tags.py
Ticket: [DT-2371](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2371)
Currently all the new tables being created via the new "add table" journey are being formatted with underscores between each word. This change adds a template filter that will format the table correctly. It replaces the underscore with a space and sentence cases the name. 
[DT-2371]: https://uktrade.atlassian.net/browse/DT-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/DT-2371:  Add template filter to correctly format the table name

Makefile, cypress/e2e/access-requests/data-access-request.cy.ts, cypress/e2e/homepage/dashboard.cy.ts, cypress/fixtures/datasets.ts, cypress/index.d.ts, cypress/support/assertions.ts, cypress/support/commands.ts, cypress/tsconfig.json, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/apps/test_endpoints/datasets/serializers.py, dataworkspace/dataworkspace/apps/test_endpoints/datasets/urls.py, dataworkspace/dataworkspace/apps/test_endpoints/datasets/views.py, dataworkspace/dataworkspace/apps/test_endpoints/urls.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/static/js/react/features/confirm-remove-user/ConfirmRemoveUser.tsx, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py, dataworkspace/dataworkspace/urls.py, dataworkspace/e2e_fixtures.json, dataworkspace/start-e2e.sh
Ticket [DT-2389](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2389)
This change adds E2E tests running against the new data access request feature. As I have needed to change the users profile status between test suites I have also created a new endpoint in this PR that can be used to add/remove editorial the users editorial access against any dataset. 
[DT-2389]: https://uktrade.atlassian.net/browse/DT-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor/DT-2389: E2E tests for data access review

cypress/e2e/datasets/add-remove-access.cy.ts, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/search_authorised_users.html
Ticket [DT-2433](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2433)
When you are searching for users to add to a dataset permissions list you don't want to add a user that already has access. Although there is no harm in this its better to show the label "User is already a member" than surfacing a button that will add them again. This change adds that label so you know who already has access.
[DT-2433]: https://uktrade.atlassian.net/browse/DT-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat/dt-2433: Guard against adding a user that already exists

dataworkspace/dataworkspace/templates/datasets/add_table/upload_csv.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Text updated to:
Check that:
- the file has more than one row
- there are no special characters in the file name (e.g. /*? ) apart from underscores and hyphens
- the file type is CSV UTF-8 (comma delimited) instead of any other CSV file type
- Google Sheets documents are downloaded as CSV UTF-8 (comma delimited)
=> Correcting CSV guidance

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
Add source and publisher tags to CatalogueItemSerializer to enrich data-flow ingestion detailed here: https://github.com/uktrade/data-flow/pull/4271
=> [DRAFT] feat: add source and publisher tags to CatalogueItemSerializer

dataworkspace/dataworkspace/apps/applications/admin.py
This adds the ability to manage tag and tag_extra_css_class from Django admin. It was an oversight to omit this from the earlier change that added the fields.
=> feat: add tool tag management to Django admin

dataworkspace/dataworkspace/templates/datasets/manage_permissions/review_access.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
This change updates a link in the breadcrumb for the data request access journey and stops the last link wrapping.
=> fix: update breadcrumb and fix wrapping

docs/data-workspace-frontend.postman_collection.json
This adds more of the Hawk-authenticated endpoints to the existing (very light) Postman collection. It also adds a few sentences of brief documentation on what variables have to be set in the Postman environment.
=> docs: add more Hawk endpoints to Postman collection

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This change makes sure we are catching the correct exception type when a user cannot be found when managing permissions.
=> fix: catch correct error type

dataworkspace/dataworkspace/apps/datasets/views.py
This change guards against two scenarios that can crop up when managing access requests. 
1. The user has left the department so the query tries to look up an object that doesn't exist
2. There is a possibility that there are duplicate emails so now we only return the active one.
=> fix: catch all error types when managing permissions

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py
This change:
- Stops adding the suffix-less tag of just the visualisation name to ECR images
- And stops using this tag in favour of the tag with the "--prod" suffix, which was added in a previous change
While not technically required, it makes releasing just a tiny bit more robust, because it is now atomic, and makes it easier to reason about the tags when looking in ECR, for example when debugging future issues.
=> feat: simplify ECR tagging

dataworkspace/dataworkspace/apps/request_access/views.py
Ticket: [DT-2525](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2525)
Currently some users are getting a false positive around access requests. For some reason we were restricting access requests to visualisations if the visualisation catalogue item didn't have a gitlab template attached. This change makes sure a user can still ask for access on a visualisation catalogue even when the template does not exist.
[DT-2525]: https://uktrade.atlassian.net/browse/DT-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/DT-2525: make sure zendesk tickets and emails are sent

dataworkspace/proxy.py
This opens up parts of the CSP on tools to subdomains of vscode-cdn.invalid
This domain can not actually exist, so it doesn't meaningfully increase risk of data leakage. However, our (modified) VS Code that we run in tools is configured to request resources (scripts, stylesheets, and fonts) from subdomain of this domain, and then intercepted by a service worker to retrieve the contents without communication with the internet.
Why VS Code uses this pattern is not known.
=> feat: open up CSP for tools to allow VS Code components to communicate

dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/templates/errors/error_500_visualisation_docker_build.html
This changes the error message shown to the users when visualisation preview fails.  It previously showed a generic error page with a cryptic Application Stopped message.
This now shows relevant 'Your visualisation failed to build' message along with a link to docker build logs
This doesn't yet tackle other failures during visualisation life cycle.
=> Show link to docker build logs when visualisation preview fails

dataworkspace/dataworkspace/apps/applications/fixtures/project_member_fixture.json, dataworkspace/dataworkspace/apps/applications/fixtures/project_members_fixture.json, dataworkspace/dataworkspace/apps/applications/fixtures/user_fixture.json, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/applications/visualisation_approvals.html, dataworkspace/dataworkspace/tests/applications/test_visualisation_owner_ui_approval.py
This change follows on from #3465 and adds the logic needed to display the users that have approved a visualisation.
=> feat/DT-2601: Display a list of approvers - Owner view

dataworkspace/dataworkspace/apps/accounts/management/commands/store_db_creds_in_s3.py, dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/tests/api_v1/core/test_views.py, dataworkspace/dataworkspace/tests/core/test_utils.py
This PR introduces the concept of common and non-common tables to the functions that generate database credentials for users and applications. Common tables are those that every Data Workspace user has access to (Reference data and tables in catalogue pages without any access restrictions), non-common are the remainder (where access to the table is determined by a user's email domain name/being specifically granted access to tables on a catalogue page).
This is a step towards an implementation of the Data Workspace permissions model that doesn't require users to assume as many roles to query the data they have access to. This will have one role for all of the common tables, one for each of the email domains that are used to control access by domain, and one per catalogue page.
=> feat: separate common and non common tables when generating credentials

dataworkspace/dataworkspace/apps/core/utils.py
This tweaks the definition of "common" datasets so only superusers can access unpublished OPEN and REQUIRES_AUTHENTICATION datasets.
=> feat: do not include unpublished datasets in "common"

dataworkspace/dataworkspace/apps/accounts/management/commands/store_db_creds_in_s3.py, dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/tests/api_v1/core/test_views.py, dataworkspace/dataworkspace/tests/core/test_utils.py, requirements-dev.txt, requirements.txt
This changes how database table privileges are granted for users that get access by their email domain. Instead of being granted a per-table role, there is now a per-email-domain role.
This is done to try to limit the number of role memberships users have, which causes performance problems on connection.
This includes a bump to pg-sync-roles that fixes a bug where it doesn't grant permissions when it should.
=> feat: separate out roles for tables granted by email domain

requirements-dev.txt, requirements.txt
This bumps the version of pg-sync-roles.
This is to have https://github.com/uktrade/pg-sync-roles/pull/133 to reduce a bit of churn on the database. In a future change we're about to call sync_roles much more (once per dataset), so I think good to get this in before.
=> build(deps): bump pg-sync-roles

dataworkspace/dataworkspace/apps/core/utils.py
Setting direct=true on schema usage for both private and team schemas, permissions are granted for the role directly instead of using intermediary role.
=> create direct role for user and team schemas

dataworkspace/dataworkspace/apps/core/utils.py, requirements-dev.txt, requirements.txt
To try to reduce the time to connection to the datasets db, we're reducing the number of rules the connecting user has.
This change uses direct=True mode on the schema create permission to avoid using the intermediate role on schemas that users have the ability to create tables in: private and team schemas.
=> perf: use direct mode for schema create permission

dataworkspace/dataworkspace/apps/core/utils.py
A previous optimisation incorrectly removed the schema USAGE permission for email-domain-granted datasets. This adds that back in.
=> fix: missing schema usage for email-domain granted datasets

dataworkspace/dataworkspace/apps/applications/spawner.py
This adds the MB__CLIENT__API_ROOT environment variable to tools, so that they can more easily use the Matchbox client library out of the box.
=> feat: populate matchbox api root environment variable in tools

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/apps/core/utils.py
This change simplifies the source_tables_for_user and source_tables_for_app functions by leveraging Django's `F` and `Values` functions to do inline "normalisation" of results for SourceDatasets and ReferenceDataset, allowing intermediate data structures (a dictionary for dataset) and list comprehensions to be removed.
Although the visualisation dataset management area does use the dictionaries, so they are added back in just for that area.
This is done because we are likely to make the functions source_tables_for_user and source_tables_for_app more complex in a future change.
=> refactor: fewer data structures and comprehension expressions

deploy.sh
This adds a new deployment script that replaces Jenkins, that works across all environments. It script takes either a release tag or a commit id. Making sure its a  release tag for production deployments. And allows deploying commit id to non-prod environments.  It checks out the release tag or commit id, builds docker image, pushes to ECR, uses [ecs-deploy](https://github.com/fabfuel/ecs-deploy) to deploy the tag to ecs task.
=> add deployment script

cypress/e2e/data-catalogue/unpublish-data-catalogue.cy.ts, dataworkspace/dataworkspace/static/js/react/components/ConfirmDialog/ConfirmDialog.stories.tsx, dataworkspace/dataworkspace/static/js/react/components/ConfirmDialog/index.tsx, dataworkspace/dataworkspace/static/js/react/features/unpublish-catalogue-page/UnpublishCataloguePage.tsx
- Refactored `ConfirmDialog/index.tsx` to remove the `bodyElement` prop (my bad) in favour of using `children`, aligning with React best practices and improving consistency
- Added a new story to demonstrate the updated usage with `children`.
- Removed excess space around dialog list items.
- Corrected a typo.
=> refactor: ConfirmDialog

dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/tests/request_access/test_requesting_data_integration.py, healthcheck/healthcheck.py
PEN test identified that too much information about the server is being returned in the healthcheck response header.
=> Fix/security: remove Server header from healthcheck response

dataworkspace/dataworkspace/static/js/eslint.config.mjs, dataworkspace/dataworkspace/static/js/react/components/ConfirmDialog/index.tsx, dataworkspace/dataworkspace/static/js/react/components/WarningText/IconImportant.tsx, dataworkspace/dataworkspace/static/js/react/components/WarningText/index.tsx
New `WarningText` component that improves the wonky icon from `govuk-react`
---
When text wraps the icon stays central
---
[Current WarningText component](https://govuk-react.github.io/govuk-react/?path=/docs/warning-text--docs)
---
Now, if someone writes:
```js
import { WarningText } from govuk-react
```
They'll get an ESLint error with a custom message.
```sh
error  'WarningText' import from 'govuk-react' is restricted. Do not import 'WarningText' from 'govuk-react'. Use '../components/WarningText' instead  no-restricted-imports
```
Correct usage:
```js
import WarningText from 'path/to/components/WarningText'
```
=> feat: new WarningText component

Dockerfile
This avoids installing unpinned versions of pip, wheel, and pip-tools, where they are already installed elsewhere in the Dockerfile, either via requirements file or by installing them as Debian packages.
This is to address the error when building the test layer in the Dockerfile, e.g. from `docker build . --target test`:
> 13.33 ERROR: Exception:
> 13.33 Traceback (most recent call last):
> 13.33   File "/usr/lib/python3.9/py_compile.py", line 144, in compile
> 13.33     code = loader.source_to_code(source_bytes, dfile or file,
> 13.33   File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
> 13.33   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 13.33   File "/usr/local/lib/python3.9/dist-packages/../../../pydevd_attach_to_process/winap …
=> build(deps): avoid installing unpinned pip, wheel, and pip-tools

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/pipelines/list.html, dataworkspace/dataworkspace/tests/core/test_error_pages.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
This opens up the /pipeline page to all users, but unless the user is a superuser, just have it show a message that the user has no access to any pipelines.
This isn't particularly useful itself - the main reason for this is that this is a stepping stone in terms of code and UX to a bigger feature where Data Catalogue Editors, IAMs, and IAOs can trigger pipelines for datasets they manage.
=> feat: open up /pipelines to all users, but have it empty unless superuser

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/pipelines/list.html, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
This adds the ability for data catalogue editors to view the Sharepoint pipelines for tables in pages they are the catalogue editors for.
This only slightly useful - the main reason for this is that this is a stepping stone to a bigger feature where they can trigger these pipelines, and that IAMs and IAOs can trigger their pipelines.
=> feat: catalogue editors view own sharepoint pipelines in /pipelines

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/pipelines/list.html, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
This adds the ability for catalogue editors to start and stop their own Sharepoint pipelines, or more specifically, Sharepoint pipelines that populate the tables in datasets for which they are catalogue editors for.
This is part of ongoing work to distribute responsibility for managing data.
=> feat: catalogue editors can start and stop own Sharepoint pipelines

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
This extends the ability from [catalogue editors](https://github.com/uktrade/data-workspace-frontend/pull/3571) to IAM and IAO, to be able to view, run and stop their own pipelines.
=> feat: dataset IAM and IAO can view, run and stop thier own pipelines

dataworkspace/dataworkspace/apps/data_collections/views.py
The PR fix the error surfaced when a data workspace user (Email address) have a duplicate sso ID with active and non-active status on Collection. When Data workspace user invite another user to collection, only active user is fetched.
[`Link to the ticket on Jira`](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2699)
=> fix to only add active user on collection when invited by user

dataworkspace/dataworkspace/templates/partials/related_data_link.html
Fix the link to related dashboard content for data source catalogue page with less than four linked dashboards.
=> fix the link to related dashboard on catalogue page

dataworkspace/dataworkspace/templates/datasets/pipelines/list.html, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py
This adds an id attribute to each pipeline in the /pipelines page.
This is so links from other pages can be linked directly to each pipeline. Specifically, in a future change, we expect to add links from catalogue pages to the pipelines that populate their tables.
=> feat: add ids to table names in pipelines page

dataworkspace/dataworkspace/apps/datasets/manager/forms.py, dataworkspace/dataworkspace/apps/datasets/manager/views.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
This links to the pipeline in the /pipelines page from the "Update or restore" page for a table, if there is a Sharepoint pipeline that populates that table. This also does a few tidy ups:
- Tidies up some spacing by correctly nesting GOV.UK Design System rows and columns
- Increases the visible heading size to medium for second-level headings - small seemed a bit too small given the size of the text
- Sets second-level headings to be h2 from h1
- Introduces horizontal lines between sections in the "Update or restore" page - it was already a bit unclear what went with what, and that would have only gotten worse with the extra link .
=> feat: link to /pipelines from "Update or restore" page of Sharepoint-populated

dataworkspace/dataworkspace/apps/datasets/manager/views.py, dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This links to the pipeline in the /pipelines page from the "Update or restore" page for a table, if there is an SQL pipeline that populates that table.
=> feat: allow catalogue editors, IAMs and IAOs to run and stop SQL pipelines

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/templates/datasets/pipelines/list.html, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py, requirements-dev.txt, requirements.in, requirements.txt
This makes the schedule descriptions on the pipelines page more human readable and uses the Cron Descriptor library to address the issue of cron expressions appearing for custom schedules.
These changes allow users to see when each pipeline is run, especially for pipelines on custom schedules, which previously were not human readable.
=> feat: human readable cron in pipelines page
