dataworkspace/dataworkspace/templates/finder/index.html
Extend GTM to cover search result click events from dataset finder
=> feat: add dataLayer push for dataset finder search click

dataworkspace/dataworkspace/static/js/chart-builder/package-lock.json, dataworkspace/dataworkspace/static/js/chart-builder/package.json
=> fix: bump node-forge

dataworkspace/dataworkspace/static/gtm-support.js
fix to the jQuery selector to select the checkboxes within the new accordion filter widgets.
=> fix: select checkboxes from accordion filters

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/templates/explorer/_base.html
=> fix: use correct version of govuk frontend

dataworkspace/dataworkspace/apps/applications/spawner.py
Missed this from bd043f6ae4db450aee8e5431ea0aa362d28f284a
=> feat: support libpq-based libraries and programs automatically for FargateSpawner

superset/requirements.txt
Bump to dependencies for superset flask-appbuilder
=> build(deps): bump Flask-AppBuilder for superset

infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/ecs_main_healthcheck.tf, infra/ecs_main_prometheus.tf, infra/ecs_main_sentryproxy.tf, infra/security_groups.tf
https://trello.com/c/l6sIkpZu/1469-bump-everything-to-fargate-140
Tested on dev.
=> infra: upgrade aws_ecs_service to fargate platform version  1.4.0

dataworkspace/dataworkspace/apps/applications/spawner.py
=> feat: more logging on failed tool startup

dataworkspace/dataworkspace/apps/datasets/utils.py
Now environment variables are libpq compatible, and since RPostgres seems to use libpq under the hood, we don't need to pass it credentials.
We also ensure to close the database connection to avoid users using many database connections by not closing them.
=> feat: simpler and more robust R-snippet

README.md, redis/Dockerfile
=> fix: update redis version and README for M1 chipset

.envs/sample.env, dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/core/boto3_client.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/apps/your_files/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/static/explorer-ie11-compat.js, dataworkspace/dataworkspace/static/explorer.js, dataworkspace/dataworkspace/templates/your_files/create-table-confirm-data-types.html, dataworkspace/dataworkspace/templates/your_files/files.html, dataworkspace/dataworkspace/tests/common.py, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/tests/your_files/test_utils.py, dataworkspace/dataworkspace/tests/your_files/test_views.py, dataworkspace/proxy.py
When creating a table from CSV we try to decode the csv first via `utf-8` and if that fails it is decoded as `cp1252`
=> Fix your files uploader

dataworkspace/dataworkspace/templates/datasets/master_dataset.html
=> use correct url name for edit link

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
=> fix: update edit dataset url on datacut page after refactor

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py
Strip the derived query before validating it
=> fix: strip semicolons before checking query is valid

dataworkspace/dataworkspace/apps/core/utils.py
https://trello.com/c/oYcHlYG2/2555-limit-tools-database-users-to-10-connections-or-so
=> feature: set connection limit for tools database users

dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html
=> fix: correct bad formatting for manage visualisation link for IAM/IAOs

Makefile, dataworkspace/dataworkspace/settings/integration_tests.py
new `test_application.py` to make logs easier to read
=> build: adding new settings for integration tests

dataworkspace/dataworkspace/apps/request_access/admin.py
Create try except block to capture access requests for datacut datasets and repair broken catalogue links
~* [] Have tests been added to cover any changes?~
=> Fix: Try except block for datacut sets in access requests

dataworkspace/proxy.py, dataworkspace/proxy_session.py, test/test_application.py
This is to mitigate the risk of session hijacking
=> feat: tie sessions to IP address

dataworkspace/proxy.py
Suspect this was used in a previous version to allow the healthcheck
=> refactor: remove unused checking if client IP is private

requirements-dev.txt
We were on a version a few years old, and a bit of a hopeful guess that this could be a step to sorting integration test issues on M1
=> build(deps): bump selenium

requirements-dev.txt, requirements.txt
There are still more (unknown) things to do, this is just a step on the way.
=> build(deps): bump cffi for M1 support

dataworkspace/dataworkspace/static/js/chart-builder/src/chart-builder/App.js, dataworkspace/dataworkspace/static/js/chart-builder/src/chart-builder/components/QueryErrorModal.js, dataworkspace/dataworkspace/templates/datasets/charts/filter_chart_data.html
**Update the instructions on the chart filter data page to**
**Update the "query failed" error message on the chart builder with what could be wrong**
Both of these are temporary measures to get users building charts while we look at optimising the way data is fetched.
=> fix: give more info about what could be wrong with a query

dataworkspace/dataworkspace/apps/datasets/views.py
views are logging details of tags. This is left over from local dev work and not helpful for prod logs.
=> fix: remove noisy and redundant logging

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/datasets/test_pipelines.py, requirements-dev.txt, requirements.in, requirements.txt
Suspect there were some unpinned deps as well, so those have been tidied up.
This also sneaks in a slightly more robust check on only allowing SELECT statements in the pipeline builder via an allowlist rather than a denylist.
=> build(deps): move to pglast for better M1 support

dataworkspace/dataworkspace/static/explorer-ie11-compat.js, dataworkspace/dataworkspace/templates/datasets/manager/restoring.html, dataworkspace/dataworkspace/templates/datasets/manager/uploading.html, dataworkspace/dataworkspace/templates/your_files/create-table-processing.html, dataworkspace/dataworkspace/templates/your_files/restore-table-in-progress.html
Attempting to ingest CSVs would always show the error
Expected a `schema` parameter
There were 2 issues causing this
1. Because next_step already has the query string parameters in it, this would cause some strange URLs with what seemed to be two '?' and two sets of parameters.
2. Because incorrect escaping was used, JS rather than HTML, the parameters were separated by `&amp;` rather than `&`
Have to admit not sure when or how this broke
This PR also fixes Your Files on staging. Somehow `s3ForcePathStyle:true` was missing from the compiled JS, which causes Your Files to fail on staging, since it has a DNS-compatible bucket name that causes host style access to be used, which violates the CSP
=> fix: CSV uploader not redirecting to correct pages & Your Files on staging

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py
=> fix: re-remove pglast column validation in favour of cursor.description

dataworkspace/dataworkspace/apps/applications/utils_tools.py
'Use Superset to create advanced visuals and **dashbaords**' fixed to '**dashboards**' in ```utils_tools.py```
=> fix: superset description typo

superset/Dockerfile, superset/requirements.txt
Since this locales version doesn't appear to exist any more
=> build(deps): bump superset, and unpin locales

test/selenium/conftest.py
This hopefully helps errors where ports are already in use when running multiple tests locally
=> tests: more robust tests by shutting down mock SSO and Zendesk more gracefully

requirements-dev.txt, requirements.txt
=> build(deps): bump pyjwt

dataworkspace/dataworkspace/apps/datasets/views.py
A small tidy to have less duplication and nesting.
=> refactor: less nesting and duplication between dataset types last updated date calculation

dataworkspace/proxy.py
=> fix: put flower behind VPN

dataworkspace/dataworkspace/apps/datasets/utils.py
=> fix: wrap get_data_hash in try except when adding metadata for datacuts

.circleci/config.yml, Makefile
=> fix: update python for circleci and echo black version

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/partials/beta_banner.html
We have de-facto passed Alpha assessment, and so are in in Private Beta
=> feat: move to Beta

mirrors-sync-cran-binary/Dockerfile
=> feature: fix cran binary mirror dockerfile debian dependencies etc

dataworkspace/dataworkspace/apps/datasets/search.py
=> fix: SearchQuery config in rank to match the SearchQuery config when searching

dataworkspace/dataworkspace/static/data-grid.js
fixes issue where ag grid failed to load array fields
=> fix: use formatted data value if provided

dataworkspace/dataworkspace/apps/datasets/utils.py
=> fix: a SQL issue in one datacut query was preventing all subsequent datacut queries from being processed

dataworkspace/dataworkspace/apps/datasets/manager/views.py, dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table_column_config.html
- error message for column validation enhanced to show columns that have been added/removed 
- added to ```manage_source_table_column_config.html``` template 
=> feat: add column comparison for data uploader

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/settings/base.py
=> fix: run average calculations hourly while testing

dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/test_datasets_db.py
This includes a refactor to avoid recursion, which can be a bit tricky to reason about
=> fix: recursive CTEs can contain forward references - they're not always tables in the public schema

dataworkspace/dataworkspace/apps/core/forms.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/tests/core/test_views.py
- Additional of UTM parameters to the 'Switch to Data Hub' link to track user journeys across the two sites
=> fix: add utm parameters to data hub link

dataworkspace/dataworkspace/apps/datasets/search.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
=> feat: ignore bookmarks if there is a search query

dataworkspace/dataworkspace/tests/datasets/test_views.py
=> docs: comments explaining the order of datasets in bookmarked tests

dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html
- group 'report an issue' link with buttons on preview page so they align 
=> fix: align 'report an issue' button on preview page

dataworkspace/dataworkspace/apps/datasets/search.py
=> feat: prioritise shorter matching names even more highly in search

infra/rds_admin.tf
So we don't run out of disk space for django admin db
=> fix: increase disk space for admin db

.pre-commit-config.yaml
fixes broken pre-commit hooks on m1 macs (for me)
=> use https git endpoint to fix pre-commit issue on m1

infra/ecr.tf, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/ecs_main_mlflow.tf, infra/ecs_main_mlflow_container_definitions.json, infra/ecs_notebooks_notebook.tf, infra/main.tf, infra/route_53.tf, infra/s3_mlflow.tf, infra/security_groups.tf
Infrastructure required for https://github.com/uktrade/data-workspace/pull/2064
=> infra: add terraform resources to handle multiple mlflow instances

infra/ecs_main_mlflow.tf, infra/ecs_notebooks_notebook.tf
=> fix: remove second mlflow instance definition as its not needed on prod

dataworkspace/dataworkspace/apps/explorer/forms.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
=> trapping a pglast parsing error appears to work

dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/core/support.html, dataworkspace/dataworkspace/templates/welcome.html, dataworkspace/dataworkspace/tests/core/test_views.py, test/selenium/test_request_data.py
Updates to Data Workspace navigation based on findings from UR:
- **About** and **Our Work** removed from navigation and added to footer links 
- **Support** renamed to **Contact Us**
=> feat: updates to navigation

dataworkspace/dataworkspace/apps/api_v1/core/serializers.py, dataworkspace/dataworkspace/apps/api_v1/core/urls.py, dataworkspace/dataworkspace/apps/api_v1/core/views.py
Expose newsletter subscriptions via api so they can be ingested by data flow
=> feature: expose newsletter subscriptions via api

dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/welcome.html, dataworkspace/dataworkspace/tests/core/test_views.py
Move _'Contact us'_ so it is the last item in the navigation
=> fix: rearrange navigation

dataworkspace/dataworkspace/apps/applications/spawner.py, infra/ecs_notebooks_jupyterlab_python.tf, infra/ecs_notebooks_notebook.tf, infra/ecs_notebooks_remote_desktop.tf, infra/ecs_notebooks_theia.tf, mlflow/requirements-mlflow.txt
=> Increase ephemeral storage to 50GB

dataworkspace/dataworkspace/apps/applications/spawner.py, infra/ecs_notebooks_jupyterlab_python.tf, infra/ecs_notebooks_notebook.tf, infra/ecs_notebooks_remote_desktop.tf, infra/ecs_notebooks_theia.tf, mlflow/requirements-mlflow.txt, requirements-dev.txt, requirements.txt
=> Fix  increase ephemeral storage

infra/ecs_pgadmin.tf, infra/ecs_rstudio.tf
=> Fix  ephemeral storage rstudio pgadmin

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/core/views.py
=> how do we want healthcheck to work?

dataworkspace/dataworkspace/static/search-v2.js
=> fix: setting a bookmark from search results

dataworkspace/dataworkspace/apps/eventlog/admin.py
=> Return a link to the related object (dataset)

infra/ecs_main_gitlab.tf
We ran out in prod - so am doubling it. Potentially this should be configurable, but this is the easiest/quickest thing.
=> feat: bump GitLab EBS size

package-lock.json, package.json
Using method from https://github.com/uktrade/data-workspace/blob/master/dataworkspace/dataworkspace/static/js/react_apps/package.json#L40-L45 to bump scss-tokenizer to 0.4.3
=> fix: upgrade scss-tokenizer to 0.4.3

dataworkspace/dataworkspace/templates/datasets/index.html
=> Fix: search bar input placeholder

dataworkspace/dataworkspace/apps/datasets/search.py
Remove timestamp cast to mitigate for indexing
=> fix: Remove timestamp cast

dataworkspace/dataworkspace/templates/datasets/index.html
=> fix: Add header to label search results

dataworkspace/dataworkspace/static/gtm-support.js, dataworkspace/dataworkspace/static/search-v2.js
Integrate GTM for suggested searches
=> feat: integrate GTM for suggested searches

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/explorer/schema.py
=> feat: reduce number of queries in Data Explorer

dataworkspace/dataworkspace/apps/explorer/schema.py
=> feat: reduce N+1 queries in Data Explorer

requirements-dev.txt, requirements.txt
=> build(deps): bump elastic-apm to be able to reduce SPAN_STACK_TRACE_MIN_DURATION to debug N+1 queries

dataworkspace/dataworkspace/apps/explorer/schema.py
=> feat: choose specific fields to attempt to reduce N+1 queries

dataworkspace/dataworkspace/apps/explorer/utils.py
We are getting exceptions:
Unable to acquire lock within the time specified
when using Data Explorer. However, it shouldn't even need to lock unless credentials have expired and need to be made (to avoid making multiple sets of credentials at the same time)
Suspect there are more optimisations for Data Explorer speed.
=> feat: don't lock when checking for Data Explorer credentials

dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html
Fix: change create a chart to be behind build flag instead of publish as this is the wrong flag
=> fix: change create a chart to be behind build flag instead of publish

mlflow/requirements-mlflow.txt
update mlflow joblib package version to 1.2.0
=> update mlflow joblib version

infra/ecs_main_admin.tf, infra/main.tf, infra/route_53.tf
Upgrade terraform files to support 1.3.1
=> feat: upgrade terraform to 1.3.1

dataworkspace/dataworkspace/apps/core/utils.py
Sometimes this was so slow it was hitting 504s and preventing tools from loading
Seems to cut times down from > 60 seconds to ~12 seconds. The `has_table_privilege` function I think was the cause.
Potentially could make this faster still - information_schema.table_privilege is a view that probably queries too much. Maybe could get faster by going to the pg_* tables directly.
=> perf: faster check for existing privileges

.envs/sample.env, docker-compose-dev.yml, localstack/Dockerfile, localstack/init/buckets.sh
Allows your files to be run locally without any extra env faff.
=> feat: switch to localstack for s3/sts

mlflow/requirements-mlflow.txt
=> bump: upgrade protobuf to 4.21.7

dataworkspace/dataworkspace/static/js/react_apps/src/your-files/popups/AddFolder.jsx, dataworkspace/dataworkspace/static/js/react_apps/src/your-files/popups/DeleteObjects.jsx
This was already being done on the upload files popup, and for consistency doing it on the delete and add folder popups
https://user-images.githubusercontent.com/13877/197386295-c733fda2-70a1-478b-b677-044fb83179f9.mov
=> feat: close popups on Escape key

dataworkspace/dataworkspace/templates/your_files/files-react.html
This is to avoid having to tell users to force a refresh to see new features
=> feat: use django's static to cache bust Your Files

mlflow/requirements-mlflow.in, mlflow/requirements-mlflow.txt
=> build(deps): downgrade protobuf to maintain tensorflow compatibility

dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/tests/data_collections/test_views.py
Restrict collections view to owner only or superuser
=> feat: restrict collections view to owner

README.md, dataworkspace/dataworkspace/static/js/stats/react_apps-stats.json
Changes to Your Files weren't visible in prod without the stats file change
DT-771
=> fix: commit missing stats file for webpack_bundle

mlflow/requirements-mlflow.txt
=> build(deps): bump MLFlow

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json
=> build(deps): bump minimatch

dataworkspace/dataworkspace/apps/datasets/views.py
Suspect this detail wan't really thought about when the ticket was written
=> feat: choose first collection that someone is the owner for that than of all collections

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json, dataworkspace/dataworkspace/static/js/react_apps/package.json
Missed in 2269a70f426608440fe75404970f46c0db327b98
DT-779
=> build(deps): bump loader-utils second attempt

dataworkspace/dataworkspace/apps/data_collections/urls.py, dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/templates/data_collections/collection_detail.html, dataworkspace/dataworkspace/templates/data_collections/collection_membership_confirm_removal.html, dataworkspace/dataworkspace/tests/data_collections/test_views.py
Not being too precious on the styling - we have another ticket to tidy things up.
https://user-images.githubusercontent.com/13877/200381430-a096031d-f732-479e-803f-0468eb0a7833.mov
DT-740
=> feat: confirm removal of datasets and dashboards from collections

dataworkspace/dataworkspace/templates/datasets/master_dataset.html
somehow missed the master dataset template
=> fix: use correct link for master dataset collection add

dataworkspace/dataworkspace/templates/data_collections/collection_membership_confirm_removal.html
=> feat: tweak back link on collections removal page

dataworkspace/dataworkspace/templates/data_collections/partials/add_dataset_link.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html
fix: include svg plus icon as part of "Add to collection" link to collection detail
=> fix: include svg plus icon as part of "Add to collection" link to collection detail

dataworkspace/dataworkspace/apps/data_collections/admin.py, dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
Implement feedback based on testing from stakeholder on initial review of collections
=> Feat: Implement feedback based on initial review of collections

dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/templates/data_collections/collection_detail.html, dataworkspace/dataworkspace/templates/data_collections/collection_membership_confirm_removal.html, dataworkspace/dataworkspace/templates/data_collections/select_collection_for_membership.html
- send events to GS on collection member add/remove
=> feat: push to GA on add/remove collection member

dataworkspace/dataworkspace/apps/data_collections/admin.py, dataworkspace/dataworkspace/apps/data_collections/forms.py
=> fix: rename DELETED to DELETE?

mlflow/requirements-mlflow.txt, requirements-dev.txt, requirements.txt
=> build(deps): bump cryptography

.dockerignore
=> build: make Docker ignore .git folder to slightly speed up local development

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json, dataworkspace/dataworkspace/static/js/react_apps/package.json
=> fix: bump loader-utils

infra/ecs_notebooks_notebook_container_definitions.json
Add sentry details to s3sync container to surface errors
=> fix: add sentry env vars to s3sync container

dataworkspace/dataworkspace/apps/datasets/forms.py
Add rich text editor to edit-dataset screen
=> feat: convert dataset description to WYSIWYG text area

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/templates/datasets/edit_visualisation_catalogue_item.html
Convert the description field in manage visualisations to rich text
=> feat: convert manage visualisaton description field to rich text

dataworkspace/dataworkspace/apps/data_collections/views.py, dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
Collection history link to appear on collection view pages with GA event integrated. Also updating the history log query to exclude collection view
=> feat: history link for collections

dataworkspace/dataworkspace/templates/data_collections/collection_detail.html
Accidental reordering of tags has caused the spacing to collapse, this reverts these changes
=> fix: spacing on collections has collapsed due to tag reordering

.circleci/config.yml, .gitignore, Dockerfile, Makefile, docker-compose-test.yml
=> build(ci): Store test results in CircleCI for better parallelism timings

Dockerfile, setup.cfg
=> build(ci): fix junit test format for CircleCI test timings

dataworkspace/dataworkspace/apps/datasets/views.py
Waffle flag is being used across the views.py and template, this is refactoring the logic so it is used less, reducing the chance for errors
=> fix: refactor user permission form to reduce waffle flag usage

mlflow/requirements-mlflow.txt
This is to bump past a vulnerability. GitHub's version checker isn't yet aware that this version fixes the vulnerability, but hopefully it will be soon
DT-974
=> build(deps): upgrade gitpython

dataworkspace/dataworkspace/static/data-grid.js, dataworkspace/dataworkspace/static/js/grid-utils.js, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html, dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/finder/results.html
=> DT866 add GA4 parameters for file download

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
Differentiating QuickSight instances in dev and prod environment (dev is shown first and then follows with prod)
https://user-images.githubusercontent.com/113979857/212874975-6af4b19a-679c-4830-95e2-73c452b1fafe.mov
=> changing namespace variables

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json
=> fix: rebuild package-lock.json to update d3-color

infra/ecr.tf, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/ecs_rstudio_rv4.tf
There is some nervousness about jumping from v3 to v4, so for now, running as a separate tool
https://trello.com/c/tYFOqbsA/44-r-upgrade-to-4-latest-in-tools
=> feat: RStudio V4 as a separate tool

dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/core/utils.py
=> Fix team visualisation access

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/templates/datasets/edit_dataset.html, dataworkspace/dataworkspace/templates/partials/dataset_info.html
As a Data Owner (IAO or IAM), I need to confirm and change the Security Classification of the data or visualisation I am managing, so that I can ensure it is correct
This ticket allows the Data Owner to edit the dataset and set the appropriate security classification
=> Feat: DT-1001 edit security classification

dataworkspace/dataworkspace/templates/running_base.html
=> DT-990 adding security classification to visualisations

dataworkspace/dataworkspace/apps/applications/spawner.py
This is a possible fix for the 202 status and unexpected cut off errors on Tools that users are currently experiencing
=> fix: configure retries for fargate spawner task

dataworkspace/dataworkspace/apps/core/utils.py
=> fix: giving permissions to app schemas

dataworkspace/dataworkspace/templates/datasets/manager/manage_source_table.html
This is to add a message to the upload screen for IAO/IAMs.
=> feat: DT-1002 - Display security classification on csv upload

dataworkspace/dataworkspace/apps/datasets/management/commands/map_security_classification_to_dataset.py
Once we’ve got the full list of security classifications, we need to upload it to populate the catalogue items. This management command provides us with the ability to do this
=> feat: security classification management command

dataworkspace/dataworkspace/apps/applications/utils.py
This would only really effect non-prod environments
=> feat: use namespace when embedding Quicksight dashboards

dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/test_admin.py
=> making datacuts mandatory fields

mlflow/requirements-mlflow.txt, requirements-dev.txt, requirements.txt
Upgrading oauthlib, tested in staging
=> upgrading oauthlib to 3.2.2

dataworkspace/dataworkspace/apps/applications/utils.py
list all users before calling quicksight sync to avoid token expire
=> list all users before calling quicksight sync to avoid token expire

s3sync/requirements.txt
This is primarily to have the change in https://github.com/uktrade/mobius3/pull/53 to reduce the number of API calls
=> feat: bump mobius3 to reduce API calls

package-lock.json, package.json
=> bump: node-sass to 8.0.0

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
Adding user ids to catalogue API
=> Update catalogue api items visualistaiontype usersid

dataworkspace/dataworkspace/apps/applications/spawner.py
Part of the work to reduce duplicate tools
=> fix: retry fargate stop task 5 times with exponential backoff

dataworkspace/dataworkspace/static/data-grid.js
=> feat: allow data grid to display appropriate timeout message

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/partials/dataset_info.html
Add publisher tag category on catalogue pages
=> feat:DT-1135 add publisher to catalogue template

dataworkspace/dataworkspace/templates/admin/reference_dataset_changeform.html
=> fix: remove duplicate queries for fields in admin template

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/data-grid.js
Reference datasets are logging a download event on data preview load and recording everything under 'csv' format (incorrectly recording json downloads). This is a PR to resolve all issues regarding this without impacting the ref dataset model.
=> fix: correct reference dataset download events

dataworkspace/dataworkspace/templates/partials/dataset_info.html
=> fix:rearranage source and publisher tags

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/conftest.py
=> feat:DT-1199 add get rows numbers on metadata

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/settings/base.py
- Sends a slack alert if duplicate tools are detected
- Optionally stop duplicate tools (controlled by waffle switch)
=> feat: add duplicate running tools monitor

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/data-grid.js
Specs have changed to include the raw table name within the event log for both view and table grid load. Also to ensure we have consistent variable names I am updating the json for three different events
=> feat: add data_table_raw_name to event log and amend json for consistency

dataworkspace/dataworkspace/apps/datasets/views.py
=> fix: add conditional for CustomDataSetQuery source to prevent attr error

requirements-dev.txt, requirements.txt
=> fix: bump ipython

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py
=> changing quicksight_id to lists

dataworkspace/dataworkspace/apps/applications/utils.py
Adds some logging to aid in debugging the false positives
=> fix: add more logging to the duplicate tool monitor

dataworkspace/dataworkspace/apps/accounts/models.py, dataworkspace/dataworkspace/apps/api_v1/accounts/serializers.py, dataworkspace/dataworkspace/tests/api_v1/accounts/test_views.py
=> feat:DT1261 add private schema on user API

dataworkspace/dataworkspace/tests/api_v1/applications/test_views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
=> fix: add freeze time to prevent unit tests failing due to daylight savings

dataworkspace/dataworkspace/apps/api_v1/core/serializers.py, dataworkspace/dataworkspace/apps/api_v1/core/urls.py, dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/tests/api_v1/core/test_views.py, dataworkspace/dataworkspace/tests/core/factories.py
=> feat:DT:1261 create an API to expose teams schema name, members and id

infra/ecs_main_gitlab.tf, infra/main.tf
To avoid cross team/project security issues, this is just for a single project.
=> feat: provide_gitlab_runner_for_tap

.github/workflows/docs.yml
=> fix: changed branch name for mkdocs

README.md, docs/contributing.md, docs/index.md, docs/infrastructure.md, mkdocs.yml
Also removed display of navigation on single pages and re-introduced a sticky nav bar
=> docs: changed home page styling

README.md, docs/infrastructure.md, mkdocs.yml
=> docs: change path from infrastructure to architecture

docs/index.md
=> docs: tailor front page more for internal and external devs

docs/CNAME
=> docs: publish to data-workspace.docs.data.trade.gov.uk

docs/architecture.md
=> docs: fix missing architecture file

mkdocs.yml
=> docs: fix double blue bar and not having sticky tabs

superset/requirements.txt
=> deps: bump superset psycopg2-binary for easier M1 development

README.md, docs/architecture.md, mkdocs.yml
=> docs: changes to architecture diagrams

docs/index.md
This was missed from the recent rename
=> docs: rename front page to Data Workspace Technical Documentation

docs/index.md
It looked a bit squashed visually
=> docs: slightly bigger start button

docs/ADRs/0001.md, docs/ADRs/0002.md
=> docs: updates to ADRs

superset/create-editor-role.sql, superset/requirements.txt, superset/superset_config.py
=> deps: bump superset and cryptography

infra-config-template/admin-environment.json, infra-config-template/create-keys.sh, infra-config-template/gitlab-secrets.json, infra-config-template/main.tf, infra-config-template/versions.tf
Addition of a new folder containing templates for terraform config, which should in future make it easier to deploy Data Workspace elsewhere, as part of our goal to make DW more open source.
=> feat: created template for terraform configuration

docs/gettingdata.md, mkdocs.yml
=> docs: initial addition of section for getting data into data workspace

README.md
=> docs: more links in the GitHub README

README.md, docs/index.md
=> docs: fix broken links

docs/development/running-locally.md, docs/development/running-tests.md
=> docs: prerequisites

docs/development/running-locally.md, docs/development/running-tests.md
=> docs: knowledge prerequisites

docs/development/running-locally.md
=> docs: mention Python

docs/development/running-locally.md
=> docs: mention creating a GitHub account

docs/development/running-locally.md
=> docs: briefly explain the context of the running locally page

docs/development/running-tests.md
=> docs: explain why run tests

docs/contributing.md
=> docs: remove note on discussions no longer existing, because they do

CONTRIBUTING.md, docs/development/running-locally.md
This also fixes a few minor typos, and also makes the development page more suitable for people not in DBT.
=> docs: reduce duplication between contributing and development pages

CONTRIBUTING.md
=> docs: reduce duplication on Contributing page

CONTRIBUTING.md
=> docs: remove unnecessary word

CONTRIBUTING.md
=> docs: more useful intro to contributing page

CONTRIBUTING.md
=> docs: fix instructions for running tests

docs/index.md
=> docs: use same case as title for link

docs/data-ingestion.md
=> docs: refine data ingestion page

docs/data-ingestion.md
=> docs: clarify source dataset ingestion

docs/data-ingestion.md
=> docs: bit of info on ad-hoc data

CONTRIBUTING.md, docs/architecture/ADRs/0001.md, docs/architecture/ADRs/0002.md, docs/architecture/ADRs/README.md, docs/architecture/application-lifecycle.md, docs/architecture/comparison-with-jupyterhub.md, docs/architecture/components.md, docs/contributing.md, docs/data-ingestion.md, docs/deployment/aws.md, docs/deployment/other-platforms.md, docs/development/database-migrations.md, docs/development/enhancedtables.md, docs/development/remotedebugging.md, docs/development/running-locally.md, docs/development/running-tests.md, docs/development/updating-dependencies.md, mkdocs.yml
=> docs: pass docs for errors

mkdocs.yml
=> docs: removed heading anchor links

mkdocs.yml
=> docs: url now displays which heading is currently being viewed

docs/development/running-locally.md
=> updating local development instructions

docs/architecture/components.md
=> docs: prerequesites for understanding the architecture

docs/architecture/components.md
=> docs: fix typo

superset/create-editor-role.sql
=> fix: fix missing Superset editor CSV export

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/datasets_db.py
Reduce the noise caused by parsing pgaudit logs with pglast
=> fix: optionally log pglast parse errors

dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/data_collections/forms.py, dataworkspace/dataworkspace/apps/datasets/constants.py, dataworkspace/dataworkspace/apps/explorer/forms.py, dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/share_email.txt, dataworkspace/dataworkspace/templates/about.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/request_access/tools_1.html, dataworkspace/dataworkspace/templates/request_data/data-description-hint.html, dataworkspace/dataworkspace/templates/request_data/data-location-hint.html, dataworkspace/dataworkspace/templates/request_data/security-classification-hint.html, dataworkspace/dataworkspace/templates/spawning.html, dataworkspace/dataworkspace/tests/data_collections/test_views.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
Replace DIT with **DBT** and Department for International Trade with **Department for Business and Trade** in the templates
=> DT-1113 replace DIT and Department for International Trade in template

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/apps/api_v1/eventlog/views.py, dataworkspace/dataworkspace/apps/api_v1/mixins.py, dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
Switch to using a start/end date for filters
=> fix: change filters to from/to

infra/rds_admin.tf
=> fix: enable performance insights

infra/ecs_main_admin.tf, infra/ecs_main_gitlab.tf
=> fix: bump elasticache engine version to match aws

dataworkspace/dataworkspace/apps/datasets/utils.py
Sentry alerts for bad queries make a lot of noise but the onus is not on devs to fix these. Reduce the noise by changing errors to warnings
=> fix: quiet warnings

dataworkspace/dataworkspace/static/js/visualisation-share-utils.js
=> fix: stop propagation on copy button click

dataworkspace/dataworkspace/apps/core/utils.py
use boto3 instead of boto client function
=> use boto3 instead of boto client function

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/templates/partials/dataset_charts.html, dataworkspace/dataworkspace/tests/applications/test_utils.py
Add message to request access to view datasets and charts, while removing the request access to tools.
Ticket on Jira:
https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?selectedIssue=DT-1433
=> Add message to request access to data while removig the request access to tools  

dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html
=> fix: missed button size and table details

dataworkspace/dataworkspace/static/assets/images/green-filter.svg, dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html
=> fix: grid style cleanup

dataworkspace/dataworkspace/static/data-grid.js
=> fix: getSortModel has been deprecated

dataworkspace/dataworkspace/context_processors.py, dataworkspace/dataworkspace/templates/tools.html
=> Running tools message on tools page

dataworkspace/dataworkspace/apps/accounts/migrations/0006_migrate_username_to_sso_id.py
=> fix: catch profile key errors

dataworkspace/dataworkspace/apps/accounts/migrations/0006_migrate_username_to_sso_id.py
=> fix: transaction issues in migration

dataworkspace/dataworkspace/apps/datasets/models.py
=> feat: give iao and iam access to the dataset by default

dataworkspace/dataworkspace/sass/data-workspace.scss, dataworkspace/dataworkspace/templates/_base.html
=> DT1393:feat add badge notification on Tools nav

dataworkspace/dataworkspace/sass/data-workspace.scss, dataworkspace/dataworkspace/templates/_base.html
This reverts commit dd2d25c01ce226ee3d9545ec963c91c16c6a5227.
=> Revert "DT1393:feat add badge notification on Tools nav (#2638)"

dataworkspace/dataworkspace/templates/partials/tool_section.html
=> DT1397:feat add resume button for ECS tools

dataworkspace/dataworkspace/settings/base.py
This is the first step towards migrating usernames to sso ids
=> feat: monkeypatch django user model to return email as `__str__()`

dataworkspace/dataworkspace/apps/accounts/backends.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/accounts/test_authentication.py, test/utility_functions.py
part of the ongoing work to migrate usernames to sso ids
=> feat: update user sso status

dataworkspace/dataworkspace/templates/partials/tool_section.html
=> DT-1396 - Clearer Help links on Tools page

.circleci/config.yml, dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/tests/accounts/test_authentication.py
=> feat: add an auth test and stop displaying username on admin list

dataworkspace/dataworkspace/static/js/visualisation-share-utils.js
=> fix: init js once dom has loaded

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/settings/base.py
=> feat: run a full sync of sso users at 1am every day

dataworkspace/dataworkspace/apps/applications/utils.py
=> fix: only update existing users during sync

dataworkspace/dataworkspace/apps/applications/utils.py
We have some user records in data workspace that do not seem to exist in the staff sso. Mark them as inactive when we encounter them
=> fix: set sso status as inactive if the user doesn't exist in the sso records

dataworkspace/start-celery.sh
=> fix: max celery db conns

dataworkspace/dataworkspace/apps/applications/utils.py
=> fix: do not update username in sso full sync

dataworkspace/dataworkspace/apps/explorer/schema.py
=> fix: include pg_catalog and information_schema in user schemas

dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/templates/errors/error_403_visualisation.html, dataworkspace/proxy.py
=> fix: clean up view a bit

dataworkspace/dataworkspace/apps/applications/utils.py, test/test_application.py
Usual access to a preview:
If the preview has access to a dataset the user doesn't have access to:
Leaving a better error message until later
=> feat: don't allow visualisation preview access if the user doesn't have access to all the datasets it has access to

dataworkspace/dataworkspace/apps/explorer/schema.py
Attempt 2 at including pg catalog tables in the users schema page.
- Remove index and temp tables as they are not needed
- Show pg catalog tables
=> feat: update user schema query to return catalog tables

dataworkspace/dataworkspace/templates/welcome.html
=> fix: update welcome bootcamp link

dataworkspace/dataworkspace/static/js/react_apps/package-lock.json, dataworkspace/dataworkspace/static/js/react_apps/package.json
=> bump semver

dataworkspace/dataworkspace/apps/datasets/admin.py
=> fix: access to editors before dataset exists

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/static/data-grid.js
Blank/not blank filters were added in the latest version of ag-grid. They were not implemented in the backend though. Now they are
=> fix: implement new blank/not blank filters

dataworkspace/dataworkspace/apps/explorer/exporters.py
=> fix: convert to string before escaping download fields

dataworkspace/dataworkspace/apps/applications/utils.py
=> fix: run full sso sync for a max of 1 hour

dataworkspace/dataworkspace/datasets_db.py
pglast does not always find a valid statement in pgaudit log queries. So catch this and return to avert an exception later on
=> fix: catch no statements found for query

dataworkspace/dataworkspace/apps/applications/utils.py
=> fix: catch resource not found when listing QS users

dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py
=> fix: reference datasets do not have catalogue editors

dataworkspace/dataworkspace/apps/datasets/admin.py
=> fix: autocomplete user fields for vis catalogue items

dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
=> fix: email is no longer a unique field. Get users by ID when creating credentials

dataworkspace/dataworkspace/apps/applications/utils.py
Reverts uktrade/data-workspace#2716
=> Revert "checking if this latency is causing visualisation preview to fail"

dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py, dataworkspace/dataworkspace/tests/test_admin.py
Reverts uktrade/data-workspace#2718
=> Revert "making contact required field in catalogue pages"

mlflow/requirements-mlflow.txt
=> bump mlflow 2.5.0

requirements-dev.txt, requirements.txt
=> bumping cryptography to 41.0.3

mlflow/requirements-mlflow.txt, requirements.txt
upgrade aiohttp to version 3.8.5
=> upgrade aiohttp to 3.8.5

mlflow/requirements-mlflow.txt, superset/requirements.txt
=> upgrading cryptography in superset and mlflow

requirements-dev.txt, requirements-docs.txt
=> upgrading pygments in requirement files to 2.15.0

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_admin.py
introduce min word limit for reference dataset description
=> introduce min word limit for reference dataset description

dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/tests/applications/test_views.py, dataworkspace/dataworkspace/tests/factories.py
=> making enquiries_contact required on front-end custom visualisation page

dataworkspace/dataworkspace/apps/applications/utils.py
log instance ip while killing idle fargate, in an attempt to figure out reason for lack of cpu stats
=> log instance ip while killing idle fargate

dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/utils.py
ignore spawner state when there is no need
=> ignore spawner state when there is no need

.circleci/config.yml
bursting cache to see if it fixes circle ci linting failure
=> bursting cache to see if it fixes circle ci linting failure

dataworkspace/dataworkspace/apps/applications/spawner.py
increase spawning timeout to mitigate failing tool starts
=> increase spawning timeout to mitigate failing tool starts

dataworkspace/dataworkspace/apps/applications/utils.py
=> fix: catch invalid sso id during QS sync and skip the user

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/schema.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/schema_deferred.html, dataworkspace/dataworkspace/apps/explorer/urls.py, dataworkspace/dataworkspace/apps/explorer/views.py
Defer feature flag, when active will now only load the schema tab on demand.
=> feat: defer loading of schemas

dataworkspace/dataworkspace/apps/core/utils.py
=> fix: clean up query logging

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/schema.html
=> fix: bug where request was made on subsequent clicks

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/explorer/schema.py
=> fix: timeout cache after 7 days

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py
Expose catalogue editors in dataset view
=> expose catalogue editor to dataset view

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
This PR will update Reference Dataset SQL snippet on catalogue pages to expose linked reference fields as the grid does.
=> fix: update reference table sql snippet

dataworkspace/dataworkspace/apps/datasets/utils.py
=> update sql snippet for two or more table

dataworkspace/dataworkspace/apps/datasets/utils.py
Make it a bit easier to tail celery logs. This will hopefully help in diagnosing the db issues caused by notifications.
=> fix: more logging for notification tasks

dataworkspace/dataworkspace/apps/datasets/utils.py
=> fix: add some timing to the notification tasks

dataworkspace/dataworkspace/apps/datasets/utils.py
=> fix: remove null column data

dataworkspace/dataworkspace/apps/dw_admin/views.py
=> fix: cache the missing source tables for 6 hours as they don't change often

dataworkspace/dataworkspace/templates/datasets/pipelines/delete.html
Update delete confirmation to be more explicit
=> fix: update pipeline delete copy

dataworkspace/dataworkspace/templates/admin/data_workspace_stats.html
=> fix: add tools started in last 24 hours to stats

dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/_base_no_footer.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_cut_source_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_sourceset_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/reference_dataset_preview.html, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/tests/core/test_error_pages.py
Ticket [DT-1678](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-1678)
Copy the code snippets from the catalogue page to the detail/preview view. This is in preparation for the new catalogue page layouts which will launch shortly afterwards. 
[DT-1678]: https://uktrade.atlassian.net/browse/DT-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: copy code snippets to detail/preview page

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
=> fix: use convenience method for pipeline status

dataworkspace/dataworkspace/settings/base.py, requirements-dev.txt, requirements.in, requirements.txt
=> feat: add celery results backend to track down task issues

dataworkspace/dataworkspace/apps/dw_admin/views.py, dataworkspace/dataworkspace/templates/admin/data_workspace_stats.html
=> feat: show number of failed celery tasks on stats page

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
=> fix: logic around failed pipelines

dataworkspace/dataworkspace/apps/datasets/migrations/0155_catalogues_replace_dit_dbt.py
migration file to find and replace the text `DIT` with `DBT` and `Department for International Trade` with `Department for Business and Trade` within catalogue items fields.
=> migration file to find and replace DIT within catalogue items

dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
Notifications have been added to the reference dataset view, displaying a draft dataset message. They have also been added to the master dataset view, displaying a no longer updated message.
=> Sub feat/dataset status notifications

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/templates/datasets/data-preview/data_cut_source_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_sourceset_preview.html, dataworkspace/dataworkspace/templates/datasets/data-preview/reference_dataset_preview.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
Append security classification to the names of downloaded files (if set)
=> feat: append security classification to downloaded file names

dataworkspace/dataworkspace/apps/datasets/migrations/0155_catalogues_replace_dit_dbt.py
fixing eligibility_criteria changes
=> fixing eligibility_criteria changes

dataworkspace/dataworkspace/apps/datasets/migrations/0155_catalogues_replace_dit_dbt.py
remove eligibility criteria from migration to fix deployment
=> remove eligibility criteria from migration to fix deployment

dataworkspace/dataworkspace/apps/api_v2/datasets/serializers.py
=> fix: round daily table usage to 3 places

dataworkspace/dataworkspace/static/js/.babelrc, dataworkspace/dataworkspace/static/js/.storybook/main.ts, dataworkspace/dataworkspace/static/js/.storybook/preview.ts, dataworkspace/dataworkspace/static/js/package-lock.json, dataworkspace/dataworkspace/static/js/package.json, dataworkspace/dataworkspace/static/js/react/components/DataDisplay/DataDisplay.stories.tsx
This changes adds [Storybook](https://storybook.js.org/) to DW. This will help us build components in isolation and speed up development.
=> Add Storybook

superset/requirements.txt
=> bump gevent

dataworkspace/dataworkspace/sass/data-workspace.scss, dataworkspace/dataworkspace/templates/datasets/data-preview/data_cut_source_preview.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html
This change surfaces a notification to the user when the dataset is no longer updated. Also this change fixes two small bugs:
1. Adds text to the "Report an issue" flag within the data cut preview page
2. Increases an offset value to reduce multiple scroll bars on data preview pages
=> Show source dataset notification 

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
=> fix: reduce number of requests for sso users

dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
This change adds the corporate governance section to the reference dataset catalogue page
=> Add the corporate governance to reference datasets

dataworkspace/dataworkspace/static/js/react/components/GetHelp/GetHelp.stories.tsx, dataworkspace/dataworkspace/static/js/react/components/GetHelp/index.tsx, dataworkspace/dataworkspace/static/js/react/components/OtherSupport/OtherSupport.stories.tsx, dataworkspace/dataworkspace/static/js/react/components/OtherSupport/index.tsx, dataworkspace/dataworkspace/static/js/react/features/support-you/SupportYou.stories.tsx, dataworkspace/dataworkspace/static/js/react/features/support-you/SupportYou.test.tsx, dataworkspace/dataworkspace/static/js/react/features/support-you/SupportYou.tsx
An Other Support tile component has been created as a part of the home page feature.
=> feat: other support tile

dataworkspace/dataworkspace/static/data-grid.js
=> fix: do not add listen event when download button is missing

dataworkspace/dataworkspace/settings/base.py
=> fix: remove ckeditor pdf plugin

dataworkspace/dataworkspace/apps/applications/spawner.py
=> feat: log task stop exception to sentry for debugging

dataworkspace/proxy.py
=> fix: use default error url if passed url is None

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/settings/base.py
=> fix: do not use dynamic pipelines for pass/success data

dataworkspace/dataworkspace/apps/api_v2/datasets/serializers.py, dataworkspace/dataworkspace/apps/api_v2/your_bookmarks/utils.py, dataworkspace/dataworkspace/apps/api_v2/your_bookmarks/views.py
add bookmark created date to the bookmarks api and order results by it (desc)
=> feat: add bookmark created date to the bookmarks api

dataworkspace/dataworkspace/apps/datasets/migrations/0160_migrate_bookmark_creation_dates.py
=> fix: handle more than one bookmark event for a user/dataset

dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py, dataworkspace/dataworkspace/apps/api_v2/recent_tools/serializers.py, dataworkspace/dataworkspace/apps/api_v2/recent_tools/urls.py, dataworkspace/dataworkspace/apps/api_v2/recent_tools/views.py, dataworkspace/dataworkspace/apps/api_v2/urls.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py, dataworkspace/dataworkspace/tests/api_v2/recent_tools/test_recent_tools.py
Ticket [DT-1730](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-1730)
This change adds a new REST endpoint so we can surface what tools a user has recently been using.
[DT-1730]: https://uktrade.atlassian.net/browse/DT-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add recent tools endpoint

dataworkspace/dataworkspace/static/js/react/features/support/Support.test.tsx, dataworkspace/dataworkspace/static/js/react/features/support/Support.tsx
This change is a small content amendment to the title of the support section within the homepage
=> Title change for support section

dataworkspace/dataworkspace/static/js/react/features/support/Support.test.tsx, dataworkspace/dataworkspace/static/js/react/features/support/Support.tsx
This change is a small content amendment to the title of the support section within the homepage
=> Remove question mark

dataworkspace/dataworkspace/apps/core/views.py
=> fix: catch empty app id in error view

infra/rds_datasets.tf
This updates the terraform for the datasets database with what _should_ be in prod.
The change in 4bd9affa354e21c62e4ba8a9be805c11cf22e1d8 attempted to do this, but for some reason wasn't quite right and changes still tried to be made. This is attempt 2
=> feat: update datasets database terraform with what's in prod part 2

infra/s3_mlflow.tf
This updates the terraform for the MLFlow bucket to match what exists in prod. I suspect some settings were changes manually in the AWS console in response to an ITHC.
=> feat: update MLFlow bucket terraform to match prod

infra/rds_admin.tf
This updates the terraform for the admin database with how it's currently configured in production. Suspect some changes were manually applied in the console causing it to get slightly out of sync.
=> feat: update terraform admin database with prod

infra/ecs_main_flower.tf
This updates the configuration for a load balancer with how it is configured in production.
=> feat: update load balancer config with production

dataworkspace/dataworkspace/apps/applications/views.py
This overrides the Cross-Origin-Opener-Policy HTTP header from its Django default of 'same-origin' to 'same-origin-allow-popups' for the pages where Quicksight dashboards are embedded.
This is done to fix the issue that QuickSight embedded dashboards cannot open new tabs. Or more specifically, they can open new tabs, but they remain blank. This fix is done at the suggestion of Quicksight via a support ticket.
From testing this on staging, it does fix the issue. However, before getting it to production we should be sure why it not working, why it broke now, why this fixes it, and be sure that the fix is safe - as in, we should know it doesn't meaningfully introduce more risk.
From looking around its Javascript source, inside its embedded iframe, Quicksight appears to be using the technique …
=> feat: set COOP to same-origin-allow-popups for Quicksight

dataworkspace/dataworkspace/apps/dw_admin/views.py
Allows us to get an idea of how much space is used for all users
=> feat: show s3 storage usage on the admin stats page

infra/ecs_main_admin.tf
A few missing values were discovered while deploying some whitelist changes
=> fix: add some missing ecs config to terraform

docs/development/releases.md, mkdocs.yml
This change adds some documentation around the release process.
=> Add release documentation

infra/ecs_main_gitlab.tf, infra/main.tf, infra/rds_admin.tf
This makes certain settings in the terraform configurable.
This is so we can have different sizes for prod and non prod environments.
=> feat: allow certain infrastructure settings to be configurable

infra/vpc.tf
This is to make it easier to fire up a new Data Workspace environment
=> feat: auto accept internal VPC pairings

infra/security_groups.tf, infra/vpc.tf
This is so we can create environments not peered with PaaS
=> feat: only configure with PaaS if configured

infra/main.tf, infra/rds_datasets.tf
=> feat: make rds datasets db parameter group configurable

sentryproxy/Dockerfile
=> fix: bump requirements for sentryproxy

infra/ecs_main_mlflow.tf, infra/route_53.tf, infra/security_groups.tf
Made use of the new mlflow_on variable to toggle running mlflow in an environment.
This is allows an environment to be spun up without mlflow.
=> feat: Allow environments without mlflow

infra/ecr.tf, infra/ecs_main_gitlab.tf, infra/main.tf, infra/route_53.tf, infra/s3_gitlab.tf, infra/security_groups.tf
Setting `gitlab_on=false` will prevent the gitlab service and any related infrastructure from being started on an environment
=> feat: enable/disable gitlab based on `gitlab_on` var

dataworkspace/dataworkspace/static/js/react/features/your-files/App.scss
This change just removes some bottom margin from the buttons in the "Your files" modal component.
=> Remove bottom margin on modal buttons

dataworkspace/dataworkspace/apps/datasets/migrations/0164_update_datacuts_dit_dbt.py
As part of the schema migration, update datacut's queries to use dbt instead of dit
=> Migrate datacuts, dit schemas to dbt

dataworkspace/dataworkspace/templates/partials/how_to_use_data.html
This change removes the alt tag attribute value as they are not important for users using assistive technology
=> DT-1849/remove alt tags from images

dataworkspace/dataworkspace/templates/welcome.html
This change makes the form on the welcome page accessible by using a label over a paragraph.
=> DT-1853/Use a label for the search form

dataworkspace/dataworkspace/templates/partials/search_bar.html
=> DT-1869/update the label for data workspace search

dataworkspace/dataworkspace/templates/datasets/partials/filter_button.html
Reverts uktrade/data-workspace-frontend#3106
=> Revert "a11y: Add aria-label to highlight how to remove a filter"

dataworkspace/dataworkspace/templates/datasets/partials/filter_button.html
Reverts uktrade/data-workspace-frontend#3110
=> Add aria-label to highlight how to remove a filter

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py
This removes the Redis-based locking when creating database users (and then when cleaning them up).
This is to remove the case where Redis locks are lost due to their limited lifetimes (which are in place so if the server goes down 1/2 way through, they are not kept indefinitely), which can cause "tuple concurrently updated" errors. It's also to simplify the setup - only PostgreSQL is involved and has to be reasoned about.
This is a stepping stone towards a setup where each table has a permanent role where it's the only role that's granted permissions to the table to work around limits on how many users can be granted select to a table.
We could potentially have more granular locking by using different lock IDs. However, we already weren't using granular locking, so keeping the change as …
=> feat: remove Redis-based locking when making database permissions

dataworkspace/dataworkspace/apps/core/utils.py
It looks like in addition to PostgreSQL not handling concurrent changes to permissions on database objects, it also doesn't handle ALTER USER ... SET ... concurrently well. This now wraps that code in a lock.
This shouldn't meaningfully increase non-parallelism _too_ much, because there the same lock needs to be grabbed in all cases anyway.
=> feat: wrap setting settings on database users/roles in a lock to avoid more tool startup failures

dataworkspace/dataworkspace/apps/core/utils.py
This is a small step of the plan where temporary database users / user permanent roles are never granted privileges directly on various objects, because they have small limits (their privileges have to squeeze into 1 database page, ~8kb).
Instead, they will all be granted membership of intermediate roles, and only those roles will be granted permissions to the various objects.
The objects in question are databases (where CONNECT is needed by the user's temporary user), schemas (where USAGE is needed by permanent roles) and tables (where SELECT is needed).
This change handles just the database case.
Note: the name of the role is not arbitrary - it has the OID of the object being granted privileges on, in this case the database. The alternative is the human readable name. While that might …
=> feat: grant database connect via role to avoid hitting limits

dataworkspace/dataworkspace/apps/datasets/migrations/0165_update_data_dictionaries_dbt.py
fix for existence of multiple source tables within a dataset
=> fix for existence of multiple source tables within a dataset

dataworkspace/dataworkspace/apps/core/utils.py
There are statement_timeout exceptions getting raised from queries that should take < 10s. While even 10s is still quite long, they shouldn't be hitting timeouts.
Best guess is that because of connection pooling, a much shorter timeout is being set somewhere else, and "leaking" through to this code. So we're making very sure what the statement_timeout is in all queries when starting tools.
=> feat: ensure a 30s timeout for queries when getting credentials

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/apps/datasets/utils.py
This PR excludes source tables that are not published from selection, so that they are not accessible.
=> exclude unpublished tables from being exposed

dataworkspace/dataworkspace/apps/core/utils.py
Replace usage of `has_schema_privilege` to use `aclexplode()` to determine a users direct schema permissions.
This is done primarily as a stepping stone to permissions being granted via roles rather than directly on objects. When we move to that, we will need to always check what permissions any role has been granted directly, rather than walking the tree of roles, which is what `has_schema_privilege` does.
There should be a small performance benefit as well because roles don't need to be checked, and PostgreSQL I think would be able to optimize a query that _doesn't_ use `has_schema_privilege` better. This is lightly verified for a single user - the original query takes ~2.4 seconds in prod, and the new one ~1.2 seconds.
=> feat: find direct schema privileges when determining available perms

dataworkspace/dataworkspace/apps/core/utils.py
This avoids granting USAGE on schemas directly to users. Instead, it grants via a per-schema role. This is to work around the de-facto limits that various database objects have on how many grants they can have.
We already do this for CONNECT on databases, and will follow up with doing this for SELECT on tables in the catalogue.
=> feat: grant privileges on schemas via roles to avoid limits when starting tools

dataworkspace/dataworkspace/apps/core/utils.py
This removes unnecessary CONNECT privileges on the database left over from how we used to grant CONNECT on the database, which was direct, rather than via an intermediate role.
=> feat: clean up legacy database connect privileges

dataworkspace/dataworkspace/apps/core/utils.py
The ::regnamespace::text pattern wraps schemas that have dots (or other special characters) in double quotes. Which then means they're wrapped in _another_ set of double quotes in later queries and the first set is assumed to be part of the name, which they're not and causes errors. We don't want the double quotes so we can properly wrap then in a single set of double quotes later.
Potentially this isn't robust to having quotes in schema names... but that is so unlikely. We did consider joining on the pg_namespace to get the unquoted name, but that seemed to make the queries must slower than they are now, and they're slow now (many seconds).
=> fix: remove double quotes when fetching schema names

dataworkspace/dataworkspace/apps/core/utils.py
=> feat: add placeholders for role based table perms

dataworkspace/dataworkspace/apps/your_files/urls.py, dataworkspace/dataworkspace/apps/your_files/views.py
Show appending message when pipeline is in incremental mode
=> feat: add page to poll for table append

dataworkspace/dataworkspace/apps/your_files/views.py
Show custom message when the append flag is set
=> fix: show single page when flag is set

dataworkspace/dataworkspace/apps/core/utils.py
For all tables that exist:
- Map table names to role names
- For any roles that don't exist, create them
=> Feat: Adding creation of table usage roles

dataworkspace/dataworkspace/apps/core/utils.py
This makes sure that all the table roles have SELECT permissions on their tables.
This is part of the move to more role-based permissions on each table.
=> feat: ensure table roles have SELECT permissions

dataworkspace/dataworkspace/apps/core/utils.py
This makes sure we check permissions properly for "tables" that are views, materialized views, and partitioned, and well as normal tables.
=> feat: role-based-permissions for more complex table types

dataworkspace/dataworkspace/apps/core/utils.py
This should make it less likely changes are made needlessly again
=> feat: clear table permissions cache if changes have been made

dataworkspace/dataworkspace/apps/core/utils.py
This is the final (other than maybe some bits of tidy up) change to move to granting permissions to users via roles rather than directly on objects. Specifically this moves to role-based perms on tables, having already moved for schemas and the database.
=> feat: grant permissions to tables using roles

dataworkspace/dataworkspace/apps/core/utils.py
This avoid giving the master user what I think are now not neccessary.
This is to try to address performance issues with the database, that from what we can tell, are not associated with any query, but associated with starting connections.
- In some cases just connecting to the database as the master user could take 10 minutes.
- From the OS process list in RDS (having enabled enhanced monitoring) there was "start" processes from the master user with ~6% for several minutes and several hundres megabytes of memory. 6% is on the current setup 1 whole CPU. Similar start processes for non master users took much more trivial levels.
- Manually deleting the roles from the master user has resulted a tremendous drop of CPU usage - this PR makes is so the roles are kept down.
I suspect that this …
=> perf: avoid granting unnecessary roles to master user

dataworkspace/dataworkspace/apps/core/utils.py
This addresses a small problem where schema roles would have been being repeatedly GRANTed USAGE even when they had them.
=> fix: properly check for schema roles to grant USAGE on

dataworkspace/dataworkspace/static/js/react/features/your-files/App.scss
Increase modal size so that it's max size is 960px with 40px padding.
=> Increase max width of upload modal

requirements-dev.txt
This change updates a dependency that was missed from #3175
=> chore: update dependencies

visualisation-base/Dockerfile
bumping visualisation base to bullseye to match the base environment on which users develop their visualisation apps
=> feat: bump visualisation base to bullseye to match tool environment

dataworkspace/dataworkspace/apps/api_v1/core/serializers.py, dataworkspace/dataworkspace/apps/api_v1/core/urls.py, dataworkspace/dataworkspace/apps/api_v1/core/views.py
This PR is to allow Data flow to ingest Data workspace user inline feedback data from Data workspace API.
All data available on data workspace database is exposed through the API.
=> DT-2009/create Data workspace user inline feedback API for data flow

flower/requirements.txt
=> chore: update tornado

dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/templates/request_access/confirmation-page.html, dataworkspace/dataworkspace/tests/request_access/test_views.py
- Redirect to either self-certify or request access based on user's email domain.
- Content changes for confirmation page
=> Add method to validate user email domain

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/datasets/utils.py
A very speculative effort to address a memory leak - in case multiple are running at once and using more and more memory.
=> feat: more locking around background tasks

dataworkspace/dataworkspace/templates/datasets/add_table/about_this_service.html
Update header sizing and remove cancel link
=> Minor changes to About this Service html

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/templates/datasets/add_table/classification_check.html, dataworkspace/dataworkspace/templates/datasets/add_table/table_schema.html
Minor css changes to header sizes in the Add Table flow
Fixes to reference datasets when on table schema page
=> Minor fixes for add table flow

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py, dataworkspace/dataworkspace/apps/datasets/add_table/urls.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/templates/datasets/add_table/descriptive_name.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Next step of add table journey: [the validation for the Descriptive name page.](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?selectedIssue=DT-2056)
**How to Test** 
1. Head to /datasets
2. Add /add-table to the end of the dataset ID
3. Click through the flow to get to 'Give your table a descriptive name'
4. Try 'data', 'dataset', 'record', '_' and an empty string in the input field to confirm the error messages are displaying correctly. 
5. Enter a valid string to proceed, currently being redirected to '/' to be changed once the nest step in the flow is completed.
=> Validation for the Descriptive name page

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py, dataworkspace/dataworkspace/apps/datasets/add_table/urls.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/templates/datasets/add_table/table_name.html, dataworkspace/dataworkspace/templates/design_system/textinput.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Adds the 'table name' page as part of the add table flow
This PR also removes any code for reference datasets so that only source/master datasets will be allowed to do this flow.
=> Feat/dt 2057 Table name page

dataworkspace/dataworkspace/apps/core/utils.py
A custom visualisation was reported as losing database permissions intermittently. Tracked it down to admins of the visualisation causing this permissions loss when they started a tool.
In more detail, when they started a tool, it would cause `new_private_database_credentials` to run, and as part of that many calls to `sync_roles`. However, some of some of these were originally designed for team schemas and their corresponding roles but were being run for visualisation schemas and roles. This was "bad" because unlike team roles, visualisation roles are granted SELECT privileges on tables, and the code for team schemas removed such permissions.
The solution is to just not call `sync_roles` for the visualisation schemas and roles - it would get run next time the visualisation starts up …
=> Fix visualisations losing database permissions

dataworkspace/dataworkspace/apps/core/utils.py
This PR points the Your Files csv import feature at the new data-flow. This is part of the continued PaaS migration work
=> Point Your Files trigger import pipeline at new Data Flow

dataworkspace/dataworkspace/apps/arangodb/utils.py
We have made this change as if there are any errors creating Arango credentials, the exceptions will appear on sentry and make it easier for us to debug.
=> Feat: Changing logger.info to logger.exception

dataworkspace/dataworkspace/apps/applications/spawner.py
This reverts commit d6205159fd84eec9c1c513382675ae9183e3e3b3.
Suspected related to tools not starting - reverting while we figure out the problem
=> Revert "feat: visualisations no longer have IAM/S3 and Arango permissions

dataworkspace/dataworkspace/templates/request_access/tools_1.html
QuickSight bullet point removed for non DBT users, context sentence added.
=> QuickSight removed for non DBT

.circleci/config.yml
Updated cache key for circleci to fix pipeline error
=> Bump circleci cache key

dataworkspace/dataworkspace/apps/datasets/add_table/forms.py, dataworkspace/dataworkspace/apps/datasets/add_table/views.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/templates/datasets/add_table/data_types.html, dataworkspace/dataworkspace/templates/datasets/add_table/upload_csv.html, dataworkspace/dataworkspace/tests/datasets/add_table/test_views.py
Ticket [DT-2303](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?isInsightsOpen=true&selectedIssue=DT-2303)
This addresses some final issues that were raised from testing the new "add table" journey. Changes include:
1. Protecting the view from unauthorised users
2. Fixing form validation issue by removing a required form attribute
3. typos and tests
[DT-2303]: https://uktrade.atlassian.net/browse/DT-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/DT-2303: add table bugs

dataworkspace/dataworkspace/templates/datasets/details/sourceset_dataset.html
Ticket [DT-2049](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?selectedIssue=DT-2049)
This change just exposes a button for a user(with the right permissions) to create a new table from a source dataset
[DT-2049]: https://uktrade.atlassian.net/browse/DT-2049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat/dt-2049: add button for the add table journey

dataworkspace/dataworkspace/static/js/package-lock.json, dataworkspace/dataworkspace/static/js/package.json
=> Bumps [ckeditor5] from 43.0.0 to 43.1.1.

docs/data-workspace-frontend.postman_collection.json
This is to kick things off - more endpoints need to be added
=> docs: initial Postman collection

requirements-dev.txt, requirements.txt
This change just bumps the django version as some security vulnerabilities are being raised.
=> Update django version

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/manage_permissions/edit_access.html, dataworkspace/dataworkspace/templates/datasets/manage_permissions/review_access.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Ticket: [DT-2363](https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?selectedIssue=DT-2363)
This change adds the new review access request form which can grant the user access to a particular source dataset. 
[DT-2363]: https://uktrade.atlassian.net/browse/DT-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat/DT-2363: Add review access request form

dataworkspace/dataworkspace/static/js/package.json
Force resolution for cross-spawn to 7.0.6
=> force resolution for cross-spawn

.circleci/config.yml
The cache/image we're using for linting is failing, I'm bumping it up and clearing the cache
=> Fix linting, python version (bump py3.9 to py3.10) and clearing cache

.circleci/config.yml, Dockerfile, dataworkspace/dataworkspace/static/js/package.json, package.json
=> Update node 16 -> 18

dataworkspace/dataworkspace/templates/request_access/confirmation-page.html
styling change on confirmation page see https://uktrade.atlassian.net/jira/software/projects/DT/boards/356?selectedIssue=DT-2451
=> feat/restyle content change for confirmation page of request-access journey for datasets

dataworkspace/dataworkspace/apps/applications/views.py
This adds the "--prod" tag suffix to production Docker-based visualisations.
This is so we can add a lifecycle policy to clean up old previews, but prevent the production visualisations, that would match "*--prod", from being deleted.
Note that before such a policy is added, we would need to manually add the "*--prod" tag to all prod images in ECR.
=> feat: add --prod tag suffix to production visualisations to help cleanup old ones

dataworkspace/dataworkspace/apps/api_v2/managed_data/views.py, dataworkspace/dataworkspace/tests/api_v2/managed_data/test_managed_data.py
bug atm with unpublished datasets showing up in Dataset You Own or manage stats
=> fix/managed data don't show unpublished data on home screen

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/templates/admin/custom_change_form.html, dataworkspace/dataworkspace/templates/admin/submit_line.html
=> Fb save button

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/explorer/schema.py, dataworkspace/dataworkspace/apps/explorer/templates/explorer/schema.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/schema_deferred.html, dataworkspace/dataworkspace/templates/datasets/data-preview/data_grid_header.html, dataworkspace/dataworkspace/templates/datasets/details/sourceset_dataset.html
=> Remove dict flag

dataworkspace/dataworkspace/apps/datasets/models.py
=> making government_security_classification required

dataworkspace/dataworkspace/apps/datasets/models.py
make the name, short description and personal data fields bigger!
* [] Have tests been added to cover any changes?
* [] Have E2E tests been added to cover any React changes?
* [] Have Accessibility tests been added to cover any React changes?
=> fix: making name, short description and personal_data use TextFields

dataworkspace/dataworkspace/apps/datasets/admin.py
=> Fb dc save buttons vis

dataworkspace/dataworkspace/apps/core/admin.py
adding some code to make it easier for data analysts to search for team schema when using "ctrl F".
=> feat: adding team schema to team schema admin overview page

cypress/e2e/tools/tools-access.cy.ts, dataworkspace/dataworkspace/templates/admin/admin_home.html
=> testing master

requirements-dev.txt, requirements.txt
Noticed one breaking change from this version bump, QuerySets don't get parsed by frontend components as JSON objs (noticed on ConfirmRemoveUser). Still plan to fix this, just need to change some of the code as well. Reverting for now so as not to break some of the app react components.
=> revert django version

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/apps/request_access/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/templates/datasets/manage_permissions/edit_summary.html, dataworkspace/dataworkspace/templates/datasets/search_authorised_users.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/request_access/test_views.py, dataworkspace/dataworkspace/zendesk.py, dataworkspace/reload-e2e-data.sh, dataworkspace/start-e2e.sh
https://uktrade.atlassian.net/browse/DT-2551?atlOrigin=eyJpIjoiMGM3MzQ3MzUxMWUyNGQwOGIzYjU2MjA5MzliMDcwYmUiLCJwIjoiaiJ9
=> fix/remove traces of waffle flag ALLOW_REQUEST_ACCESS_TO_DATA_FLOW, run isort on affected files

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/templates/admin/submit_line.html
Fix for the  'Save and continue editing' button in django admin to stay on the page.
=> Fixing the 'Save and continue editing' functionality

dataworkspace/dataworkspace/static/js/package-lock.json, dataworkspace/dataworkspace/static/js/package.json
Package updates and security fixes
=> chore: update deps to fix security vulnerabilities

dataworkspace/dataworkspace/static/js/react/features/your-files/popups/UploadFiles.jsx
Removing warning text from the upload popup
=> Removing warning text

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/apps/datasets/data_dictionary/service.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/data_dictionary.html
Adding in primary keys to data dictionaries - shown as [PK] after the column name.
=> feat: add primary keys to data dictionaries

Makefile, dataworkspace/dataworkspace/apps/applications/gitlab.py, dataworkspace/dataworkspace/tests/applications/test_gitlab.py
=> adding function check for dataworkspace team member

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py, dataworkspace/dataworkspace/apps/datasets/pipelines/views.py, dataworkspace/dataworkspace/templates/datasets/pipelines/pipeline_detail.html
* steal ace editor from data explorer
=> feat: ace editor for derived pipelines

dataworkspace/dataworkspace/templates/core/newsletter_subscription.html
This change fixes some broken dynamic content due to a badly formatted django template.
=> fix: formatting issues breaking dynamic content on button

Jenkinsfile
Fix code to match new name for Kubernetes secret.
=> Update Jenkinsfile with new pod secret name

docs/data-workspace-frontend.postman_collection.json
One endpoint was copy and pasted, but not properly edited. This corrects that mistake (that I made I suspect).
=> docs: correct postman collection paths

dataworkspace/dataworkspace/apps/applications/spawner.py
=> Add envvars for Matchbox to container spawner

docs/data-workspace-frontend-api-v2.postman_collection.json
This change adds the API V2 collection to the docs
=> chore: add api v2 collection to docs

dataworkspace/dataworkspace/apps/core/utils.py
Investigating slow initiation of connections to the database leads to suspected new_private_database_credentials involvement, and cache effects, so slightly speculatively looking at reducing what new_private_database_credentials does.
One thing it does is set the default privileges on tables created in shared (i.e. team) schemas, and in order to do this, grants the current (master) user the roles to do this. However, an event trigger is in place that automatically reassigns the ownership of tables creates in such schemas to the corresponding roles, which by default also gives all privileges on the tables to the owners.
So it shouldn't be necessary to set default privileges, and so also means it shouldn't be necessary to grant, and then revoke, privileges to the master user.
=> perf: reduce churn on database when creating users

CONTRIBUTING.md
Small documentation tweaks to reflect the move from `master` to `main` as the name of the default branch
=> Update README to reflect new default branch name

dataworkspace/dataworkspace/apps/core/utils.py
This groups database access to "individual"-ly granted tables by dataset, adding in a database role with the dataset id.
This is to reduce the amount of roles granted to users, which causes performance problems on connection.
=> perf: individual dataset access by role

dataworkspace/dataworkspace/templates/request_access/confirmation-page.html
=> correct html format on confirmation page

dataworkspace/dataworkspace/templates/datasets/details/sourceset_dataset.html
Add scope for accessibility on catalogue table header
=> Add scope accessibility on catalogue table header

dataworkspace/dataworkspace/apps/datasets/requesting_data/forms.py, dataworkspace/dataworkspace/apps/datasets/requesting_data/views.py, dataworkspace/dataworkspace/templates/partials/requesting_data_journeys.html
=> refactoring

dataworkspace/dataworkspace/apps/datasets/requesting_data/forms.py, dataworkspace/dataworkspace/apps/datasets/requesting_data/views.py, dataworkspace/dataworkspace/templates/datasets/requesting_data/add_new_dataset.html, dataworkspace/dataworkspace/templates/datasets/requesting_data/adding_data.html, dataworkspace/dataworkspace/templates/datasets/requesting_data/form_template.html, dataworkspace/dataworkspace/templates/datasets/requesting_data/radio_conditional.html, dataworkspace/dataworkspace/templates/datasets/requesting_data/security.html, dataworkspace/dataworkspace/templates/datasets/requesting_data/update_frequency_options.html, dataworkspace/dataworkspace/urls.py
=> Feature/requesting datasets/refactor

dataworkspace/dataworkspace/apps/datasets/requesting_data/views.py, dataworkspace/dataworkspace/templates/datasets/requesting_data/adding_data.html
Allowing users to create untitled requests
Fix for starting on section 2 or 3
=> fixing user request amount and unnamed datasets given name

dataworkspace/dataworkspace/apps/datasets/requesting_data/views.py, dataworkspace/dataworkspace/templates/datasets/requesting_data/submission.html
Zendesk Ticket creation fix and naming fix
=> zendesk ticket creation

cypress/e2e/requesting_data/requesting_data.cy.ts, dataworkspace/dataworkspace/apps/datasets/requesting_data/forms.py, dataworkspace/dataworkspace/apps/datasets/requesting_data/views.py, dataworkspace/dataworkspace/tests/factories.py, dataworkspace/dataworkspace/tests/requesting_data/test_requesting_data_integration.py, dataworkspace/dataworkspace/tests/requesting_data/test_requesting_data_unit.py, dataworkspace/dataworkspace/urls.py
=> Testing around zendesk ticket and URL update

dataworkspace/dataworkspace/templates/partials/related_data_link.html
=> display dashboard name assosiated
