uktrade/data-workspace-frontend

app/proxy.py
test/test.py

aiohttp was making _all_ onward requests chunked, even GET

(fix) For RStudio, no chunked transfers

---

app/app/templates/root.html

rename appstream link

---

app/app/templates/_base.html
app/app/templates/spawning.html

This is for consistency with the upcoming catalogue

(feat) Breadcrumbs on app spawning page

---

Dockerfile
requirements-dev.txt

To address CVE-2019-12308, CVE-2019-6975 and CVE-2019-3498

(feat) Bump to latest django

---

.pre-commit-config.yaml
mirrors-sync/Dockerfile
mirrors-sync/mirrors-sync.py

Please forgive the code... it was a rush and always on the to-tidy
list...

(refactor) Bring in mirrors-sync

---

s3sync/Dockerfile

Fixed by https://github.com/uktrade/mobius3/commit/91a83b182e2f8b2765aad5eb37ac03282674643a

(fix) Syncing in directories in containers

---

dataworkspace/dataworkspace/static/explorer-v1.js
dataworkspace/dataworkspace/templates/files.html

Will likely still need a bit of inline guidance on how to use it: in
that it will not be automatically synced to containers, and will need
manual boto calls

(feat) Show a bigdata folder in file browser

---

dataworkspace/dataworkspace/apps/api_v1/urls.py
dataworkspace/dataworkspace/apps/api_v1/views.py
dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/core/views.py
dataworkspace/dataworkspace/static/explorer-v1.js
dataworkspace/dataworkspace/templates/files.html

The browser exists primarily for large uploads. Before the credentials last one hour, and large uploads could take longer than this.

(feat) Refresh credentials automatically in s3 browser

---

infra/main.tf
infra/rds_admin.tf

Some of the environments can use a small or a micro

(infra) Make admin database instance class configurable

---

dataworkspace/dataworkspace/apps/accounts/admin.py

This is to be able to (manually) handle the case where someone's primary
email in SSO has changed.

(feat) Allow user email edit

---

dataworkspace/dataworkspace/apps/api_v1/views.py

It's not the best fix, suspect analysis will be tricky or impossible,
but it shouldn't error

(feat) Fix text[] -> Google Data Studio

---

.circleci/config.yml
requirements/dev.txt

CircleCI provided language and service images come with docker tools (as well as some other utilities) pre-installed, so we can skip the installation steps in our own CI config.
https://circleci.com/docs/2.0/circleci-images/#pre-installed-tools
There are additional requirements listed in the Dockerfile tha aren't part of the requirements.txt

Use CircleCI convenience images to avoid installing docker manually

---

gds-connector/src/Code.js

Trying to find source of flakiness

(feat) Better logging in Google Data Studio connector

---

test/test.py

There are occasional errors
> django.contrib.auth.models.User.MultipleObjectsReturned: get() returned more than one User -- it returned 201!
Suspect it might be due to multiple users in the test db ending up with
the same email address.

(tests) Attempt at less flakey tests

---

dataworkspace/dataworkspace/apps/accounts/backends.py
dataworkspace/dataworkspace/tests/common.py
dataworkspace/dataworkspace/tests/conftest.py
dataworkspace/proxy.py
test/test_application.py

Often what a user reports as their primary email isn't what their
primary email is in SSO.

(feat) Match new users on any SSO email

---

infra/ecr.tf
infra/ecs_notebooks_notebook.tf
infra/ecs_user_provided.tf
infra/main.tf
infra/security_groups.tf

This is since initially, the apps will contain the data in the docker
images, and we're happy for this to be in AWS

(feat) Use ECR for user-provided apps

---

dataworkspace/dataworkspace/apps/accounts/admin.py

Also brings the visualisation access selector in line with permissions selectors.

Fix issue caused by merge of visualisations and permissions branches.

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/accounts/backends.py

* ~[ ] Has the README been updated (if needed)?~

(fix) New user issues: not created with correct email and username

---

dataworkspace/dataworkspace/apps/datasets/models.py

Do not show request access link on open master datasets

Do not show request access link on open master datasets

---

dataworkspace/dataworkspace/templates/datasets/master_dataset.html

Add a list of fields to master dataset template

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/core/forms.py
dataworkspace/dataworkspace/apps/core/views.py
dataworkspace/dataworkspace/templates/core/support.html
dataworkspace/dataworkspace/tests/test_views.py
dataworkspace/dataworkspace/zendesk.py

Do not allow the uploading of files to the support form.

Remove support request attachments

---

CHANGELOG.md
Dockerfile

Bumped version of OpenSSL to 1.1.1d-r2
* ~[ ] Have tests been added to cover any changes?~
* ~[ ] Has the README been updated (if needed)?~

(feat) Bump OpenSSL

---

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py

* [ x] Has the README been updated (if needed)?

fix issue with not removing the previous query string

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/error_403.html
dataworkspace/dataworkspace/templates/error_404.html
dataworkspace/dataworkspace/templates/error_500.html
test/test_application.py

Based on https://design-system.service.gov.uk/patterns/page-not-found-pages/ and https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/
workspace/blob/master/CHANGELOG.md) been updated?

(feat) Better error pages

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/spawning.html
test/test_application.py

Display a random data protection reminder on tool loading pages.
[Trello Card](https://trello.com/c/ZIdSLCV0/736-16-small-display-messaging-on-tool-loading-pages)

Display messaging on tool loading pages

---

CHANGELOG.md
jupyterlab-python/Dockerfile
jupyterlab-r/Dockerfile
rstudio/Dockerfile
s3sync/start.sh

Added git to RStudio and JupyterLab, ready for the upcoming connection to GitLab. Also ensured that `.git` directories are synced between S3 and each user's home folder.

(feat) Add git to tools

---

CHANGELOG.md
gitlab/Dockerfile
gitlab/start.sh
infra/ecs_main_gitlab.tf
infra/ecs_main_gitlab_container_definitions.json
infra/ecs_main_gitlab_container_definitions_GITLAB_OMNIBUS_CONFIG.rb
infra/main.tf
infra/route_53.tf
infra/s3_gitlab.tf
infra/security_groups.tf

It's still in an early testing phase. There is not EBS backup for example, and the testers have been made aware data can be lost. Putting behind the VPN is also still to be done, but it is behind SSO.

(feat) Gitlab

---

dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/tests/datasets/test_views.py

Fix pagination link colors not matching GOV.UK style

---

CHANGELOG.md
Dockerfile

Bumped version of nginx to nginx=1.16.1-r2

(feat) Bump nginx

---

dataworkspace/dataworkspace/apps/core/utils.py

(fix) Propagate exception from fetching from db to StreamingHttpResponse

---

CHANGELOG.md
s3sync/Dockerfile
s3sync/start.sh

Bump mobius3 version to sync mode of files, specifically to maintain the mode of any private keys

(feat) Bump mobius3 to sync mode of files

---

test/test_application.py

Suspect the application takes a while to start

(tests) Attempt at making tests less flaky

---

dataworkspace/dataworkspace/apps/datasets/views.py

Default postgres configuration in AWS doesn't seem to do stemming
correctly by default, so we're setting the config explicitly
for each query.

Explicitly set full text search language to English

---

CHANGELOG.md
etc/nginx/nginx.conf

It's erring on the side of paranoia, but the header is potentially a
leak of data.

(feat) Never send referer header

---

CHANGELOG.md
infra/ecs_notebooks_jupyterlab_r.tf
jupyterlab-python/Dockerfile
jupyterlab-r/Dockerfile

Migrated R and Python docker images from Alpine to Debian.
* [ x] Have tests been added to cover any changes?
* [ x] Has the [CHANGELOG](https://github.com/uktrade/data-workspace/blob/master/CHANGELOG.md) been updated?
* [ x] Has the README been updated (if needed)?

Migrate docker debian

---

CHANGELOG.md
dataworkspace/proxy.py

This is to limit risk of egress
~* [] Have tests been added to cover any changes?~

(feat) Include Content security policy header

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/datasets/admin.py
dataworkspace/dataworkspace/apps/dw_admin/forms.py

Allow for easier finding/editing of all views and tables across the system.

Add standalone admin forms for SourceView and SourceTable.

---

CHANGELOG.md
jupyterlab-python/Dockerfile
jupyterlab-r/Dockerfile

Reduce unnecessary RUNs in Docker image

cleanup docker files

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/core/utils.py

More descriptive name for cursors, to help debug them

(feat) More descriptive name for cursors, to help debug them

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/datasets/forms.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/templates/request_access.html
dataworkspace/dataworkspace/tests/datasets/test_views.py
dataworkspace/dataworkspace/zendesk.py

Merges goal and justification questions into one

Remove justification question from request access form

---

Jenkinsfile

Previously, our images were build by quay.io using a Github trigger and we needed to wait for the build to finish before triggering a release job in Jenkins or it would pick up an old master image tag.
This adds a step to the Jenkins pipeline that builds a docker image for dataworkspace admin and pushes it to quay before proceeding with the release to dev. This way, we can kick off the release pipeline automatically after merge and the correct image, tagged with commit SHA will get released. This also allows us to resume older pipelines paused before staging/prod since they'll be tied to a unique immutable tag.
This merges existing prepare step and a k8s agent build step into one, since both require a workspace checkout. The agent is defined within the stage, allowing pipeline itself to …

Build dataworkspace docker container in Jenkins

---

CHANGELOG.md
rstudio/Dockerfile

Added packages in RStudio to include more frequently-used ones

(feat) More RStudio packages

---

CHANGELOG.md
jupyterlab-python/jupyter_notebook_config.py
jupyterlab-r/jupyter_notebook_config.py

Tab-completion and up for previous history item weren't working.

(feat) Set default shell to bash

---

CHANGELOG.md
s3sync/start.sh

(feat) Sync all hidden files, e.g. .gitignore

---

CHANGELOG.md
rstudio/Dockerfile

There has been a request for the pivot_longer, which is apparently missing in the installed version

(feat) Bump tidyverse to latest

---

.circleci/config.yml

Run our tests and linting in parallel so that tests complete faster and linting failures are reported sooner.

Test parallel circleci test

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/admin.py

Fix the incorrect change of nice_name -> name (it was on the wrong model...)

(fix) Incorrect change of nice_name -> name

---

CHANGELOG.md
infra/ecs_main_mirrors_sync.tf
infra/ecs_main_mirrors_sync_container_definitions.json
mirrors-sync/mirrors-sync.py

Mirror the NLTK packages: these have been asked after more than once.
~* [] Have tests been added to cover any changes?~

(feat) Mirror NLTK

---

CHANGELOG.md
rstudio/Dockerfile

Add package to enable creation of PDFs in RStudio

(feat) Adding texlive to publish PDF from RStudio

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/utils.py

The service discovery needs a "name" field to label the application

(fix) Metrics, and so auto application shutdown

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/templates/datasets/master_dataset.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html

Ticket: https://trello.com/c/YlZgZ3xB/886

Remove dates from dataset detail views

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py
requirements-dev.txt

Ticket: https://trello.com/c/sKVwyZmf/892

Add 'Help' link to header/footer

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py
requirements-dev.txt

Reverts uktrade/data-workspace#513
Let's put those help links back in, now we're about to publish the help pages.

Revert "Revert "Add 'Help' link to header/footer""

---

dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py

Update link to "Help centre", not just "Help"

Samuelhwilliams patch 1

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/datasets/forms.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/templates/datasets/filter.html
dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/tests/datasets/test_views.py

Ticket: https://trello.com/c/SOawo7Tx/829

Add 'access granted' filter for datasets

---

CHANGELOG.md
infra/ecs_main_gitlab.tf

(feat) Prevent-destroy on GitLab EBS volume

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/spawner.py
infra/ecs_main_admin.tf

In later changes this will change to dynamically build the tag if
possible
~* [ ] Have tests been added to cover any changes?
~

(feat) Check if ECR has tag: fail early if not

---

CHANGELOG.md
infra/ecr.tf
infra/security_groups.tf

The GitLab runner will need ECR API access (e.g. to login), but it doesn't have internet access.

(feat) Use a VPC endpoint for ECR API access

---

dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py

Move help centre link

---

infra/ecr.tf
infra/ecs_main_gitlab.tf
infra/security_groups.tf
visualisation-base-r/Dockerfile
visualisation-base/Dockerfile

Opting to have a (hopefully small) set of base Docker images for typical visualisations.

(feat) Build docker images in runner without internet access

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/visualisations.html

(fix) Links to branches and commits in GitLab in visualisations page

---

CHANGELOG.md
rstudio/Dockerfile

(feat) Bump RStudio packages

---

CHANGELOG.md
infra/ecs_main_mirrors_sync.tf

(fix) Run mirrors on correct branch

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/datasets/master_dataset.html

(fix) Google Data Studio link

---

dataworkspace/dataworkspace/apps/core/utils.py

When a user downloads a CSV we used to spawn a gevent greenlet that would fetch results from DB and put them in a queue. Django then returned a streaming response that was reading data from that queue to return to the client. This allowed us to prefetch results, making downloads potentially faster on quick connections since the query is executed in parallel with the request being streamed.
This approach however turned out to be prone to creating hard to debug problems. It used to cause incomplete downloads on slow connections without reporting the error to the user until we tweaked queue timeouts and linked greenlet error handling together. Since the queue still required a timeout it was still possible for a very slow connection to fail an otherwise successful download if it took too long …

Remove intermediary queue from CSV data downloads

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/_main.html
dataworkspace/dataworkspace/templates/about.html
dataworkspace/dataworkspace/templates/appstream.html
dataworkspace/dataworkspace/templates/appstream_admin.html
dataworkspace/dataworkspace/templates/core/support.html
dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/templates/datasets/master_dataset.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
dataworkspace/dataworkspace/templates/eligibility_criteria.html
dataworkspace/dataworkspace/templates/eligibility_criteria_not_met.html
dataworkspace/dataworkspace/templates/error_403.html
dataworkspace/dataworkspace/templates/error_404.html
dataworkspace/dataworkspace/templates/error_500.html
dataworkspace/dataworkspace/templates/files.html
dataworkspace/dataworkspace/templates/request_access.html
dataworkspace/dataworkspace/templates/request_access_success.html
dataworkspace/dataworkspace/templates/spawning.html
dataworkspace/dataworkspace/templates/tools.html
dataworkspace/dataworkspace/templates/visualisation_branch.html
dataworkspace/dataworkspace/templates/visualisations.html

(refactor) Rename inner_content -> content

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/_main.html
dataworkspace/dataworkspace/templates/_main_and_nav.html
dataworkspace/dataworkspace/templates/visualisation_branch.html

Move visualisations side navigation outside of the `main` html element

(feat) Move visualisations side navigation outside of the `main` html element

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/views.py

(feat) Support 'double precision' in Google Data Studio data

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py
dataworkspace/dataworkspace/apps/api_v1/eventlog/urls.py
dataworkspace/dataworkspace/apps/api_v1/eventlog/views.py
dataworkspace/dataworkspace/apps/api_v1/urls.py
dataworkspace/dataworkspace/apps/datasets/models.py
dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
dataworkspace/dataworkspace/tests/factories.py
dataworkspace/proxy.py
requirements.txt

Adds an api endpoint for event log entries for consumption by data flow. Includes the addition of django rest framework as there are at least 3 more endpoints to be added in the near future.

Add an api endpoint for event log entries

---

dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/urls.py
docker-compose-dev.yml

Fix debug toolbar for docker-compose-dev

---

CHANGELOG.md
Dockerfile
dataworkspace/dataworkspace/settings/base.py
requirements.txt

Based on https://readme.trade.gov.uk/docs/howtos/app-metrics.html
Currently not tested locally as I don't have access to ELK. But have requested access and will check it out when I get it.

Instrument ELK APM

---

CHANGELOG.md
Dockerfile
dataworkspace/dataworkspace/settings/base.py
requirements.txt

Reverts uktrade/data-workspace#571
Looks like AWS isn't quite set up for this to work yet, so rolling back as we're getting Sentry errors.

Revert "Instrument ELK APM"

---

CHANGELOG.md
Dockerfile
dataworkspace/dataworkspace/settings/base.py
requirements.txt

Reverts uktrade/data-workspace#576
Webops have tweaked AWS config again - let's see if it works.

Revert "Revert "Instrument ELK APM""

---

CHANGELOG.md
Dockerfile
dataworkspace/dataworkspace/settings/base.py
requirements.txt

Reverts uktrade/data-workspace#583
Webops updated the APM endpoint pretty quickly.

Instrument APM for real

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/spawner.py
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/visualisation_branch.html

This is the precursor to changing the commit ID of the production
visualisation.

(feat) Show commit ID of production visualisation

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/utils.py

(feat) Fewer exceptions polling Fargate for application stopped time

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/admin.py
dataworkspace/dataworkspace/apps/applications/utils.py

(feat) Send fewer exceptions to Sentry when finding CPU

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/accounts/serializers.py
dataworkspace/dataworkspace/apps/api_v1/accounts/urls.py
dataworkspace/dataworkspace/apps/api_v1/accounts/views.py
dataworkspace/dataworkspace/apps/api_v1/urls.py
dataworkspace/dataworkspace/tests/api_v1/accounts/test_views.py
dataworkspace/dataworkspace/tests/api_v1/base.py
dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
dataworkspace/proxy.py

- Adds a new hawk authenticated API endpoint for listing user accounts for consumption by data flow.
- Refactor api tests a bit in preparation for addition of new endpoint(s)

Add API endpoint for listing user accounts

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/visualisations.html

Showing all the projects I realise was a semi-accidental "nice to have" which had the primary effects of complicating/slowing things down for everyone.

(feat) Only show link to visualisation if have GitLab developer access

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py

(fix) Allow mixed case email when sharing visualisation

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/gitlab.py
dataworkspace/dataworkspace/apps/applications/views.py

Although the develop_visualisations permission was enforced, the GitLab permission check wasn't performed.

(feat) Only allow visualisation access if have GitLab developer access level

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/visualisation_users_give_access.html

(feat) Message on sharing visualisation

---

CHANGELOG.md
Dockerfile

(feat) Bump git

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/spawner.py

 (feat) Allow pipeline to take 30 minutes to complete

---

CHANGELOG.md
dataworkspace/proxy.py

Allow the correct users url through the proxy to the hawk authed endpoint

Fix typo in url

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/views.py

The database user had the name of the user starting the application,
which is confusing when investigating issues.

(feat) More accurate database user for visualisations

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py

(fix) Attempt to avoid 'tuple concurrently updated' errors

---

.pre-commit-config.yaml
CHANGELOG.md

(build) Don't automatically normalise strings

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py

List visualisations in lexicographical order

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/gitlab.py
dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/tests/applications/test_views.py
test/test_application.py

(feat) Use GitLab Developer permission to control access to preview

---

CHANGELOG.md
dataworkspace/proxy.py

(feat) More helpful logging

---

CHANGELOG.md
gitlab/Dockerfile

(feat) Bump gitlab

---

.envs/sample.env
CHANGELOG.md
Dockerfile
dataworkspace/start.sh
docker-compose-dev.yml

Use start script for docker-compose-dev

---

.envs/sample.env
CHANGELOG.md
Dockerfile
dataworkspace/start.sh
docker-compose-dev.yml

Reverts uktrade/data-workspace#647

Revert "Use start script for docker-compose-dev"

---

CHANGELOG.md
rstudio/Dockerfile

One of the visualisations uses it, and it seems fundamental/common enough
to include

(feat) Install RPostgres in the RStudio base image

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py

Remove client-side validation on short description

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/forms.py
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/visualisation_approvals.html
dataworkspace/dataworkspace/tests/applications/test_views.py

Allow users to unapprove visualisations

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/visualisation_approvals.html

Update text on data vis ui approvals page

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/datasets/views.py
dataworkspace/dataworkspace/apps/api_v1/views.py
dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/datasets/views.py
postgres/init-databases.sql
test/test_application.py

(feat) Attempt to address database connection usage by closing earlier on streaming responses

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/forms.py

Auto lowercase email for validation

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/core/utils.py

(feat) Don't give visualisations or tools access to deleted datasets

---

CHANGELOG.md
dataworkspace/proxy.py

(feat) Log the URL on the line that logs the current user email and ID

---

CHANGELOG.md
infra/ecs_main_admin.tf
infra/ecs_main_admin_container_definitions.json
infra/ecs_notebooks_dataexplorer.tf
infra/main.tf

(feat) Add Data Explorer as a hidden tool

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/views.py
dataworkspace/dataworkspace/apps/applications/spawner.py
dataworkspace/dataworkspace/apps/core/utils.py

So they can write some state if they need to

(feat) Pass user schema to tool as environment variable

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/accounts/admin.py
dataworkspace/dataworkspace/apps/applications/admin.py
dataworkspace/dataworkspace/apps/datasets/views.py

Serialize models to python when adding them as extras to an event log entry

Fix json serialization errors on event log

---

dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py

This may also be contributing factor to leaky db connections, if something couldn't get a lock, would it block forever?

(fix) Workaround for nothing seemingly being able to get a lock

---

CHANGELOG.md
dataworkspace/proxy.py

This is for maps in Superset (Although the maps still don't don't work since they seem to make external requests to api.mapbox.com, which are blocked).
* [~] Has the [CHANGELOG](https://github.com/uktrade/data-workspace/blob/master/CHANGELOG.md) been updated?

(feat) Allow workers to be made from blobs

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/running.html

Specifically to allow links with target="_blank"

(feat) Allow popups in wrapped visualisations

---

CHANGELOG.md
s3sync/start.sh

(feat) Upload all .git files on create to attempt to address corruption

---

CHANGELOG.md
infra/ecs_main_registry.tf

(feat) Fargate 1.3.0 -> 1.4.0 for Docker pull-through cache

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/spawner.py

(feat) Avoid creating a new task definition for every cpu/memory-specified launch

---

CHANGELOG.md
dataworkspace/proxy.py

(feat) Use same CSP on Superset as any application

---

CHANGELOG.md
dataworkspace/proxy.py

(feat) Superset behind the VPN

---

dataworkspace/dataworkspace/apps/applications/management/commands/sync_sources_and_permissions_to_quicksight.py

Simplify set-up by having a separate dataset per table in the DB, rather than trying to combine associated tables.

Separate dataset per sourcetable

---

dataworkspace/dataworkspace/apps/applications/management/commands/sync_sources_and_permissions_to_quicksight.py

Ignore empty/invalid tables

---

.envs/sample.env
.envs/test.env
CHANGELOG.md
dataworkspace/proxy.py
infra/ecs_main_admin.tf
infra/ecs_main_admin_container_definitions.json
infra/ecs_main_metabase_multiuser.tf
infra/ecs_main_metabase_multiuser_container_definitions.json
infra/main.tf
infra/route_53.tf
infra/security_groups.tf

This is
- Behind the VPN
- Behind SSO, but Metabase isn't right now aware of users. Each user must then sign into Metabase with a username/password

(feat) Multiuser Metabase

---

dataworkspace/dataworkspace/apps/applications/management/commands/sync_quicksight_user_datasources.py

Remove local testing snippet

---

.envs/sample.env
.envs/test.env
CHANGELOG.md
dataworkspace/proxy.py
infra/ecs_main_admin.tf
infra/ecs_main_admin_container_definitions.json
infra/ecs_main_metabase_multiuser.tf
infra/main.tf

(feat) Transparently create and login Metabase users

---

dataworkspace/dataworkspace/apps/applications/management/commands/sync_metabase_permissions.py

Fix Metabase sync permissions error if 'All users' don't have any dataset access

---

CHANGELOG.md
metrics/Dockerfile
metrics/metrics.py

(feat) Metrics for containers Fargate 1.4.0 compatible

---

dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py

(fix) Temporary fix since locks are not being released

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json
jupyterlab-python/Dockerfile

(feat) JupyterLab Python on Fargate 1.4.0

---

CHANGELOG.md
Dockerfile

(feat) Bump python

---

CHANGELOG.md
rstudio/Dockerfile
rstudio/rstudio-start.sh

(feat) RStudio Fargate 1.4.0 compatible

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json

(feat) Bump RStudio to Fargate 1.4.0

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json

(feat) Bump pgAdmin to Fargate 1.4.0

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json
jupyterlab-r/Dockerfile
jupyterlab-r/start.sh

(feat) JupyterLab R Fargate 1.4.0 compatible

---

docker-compose-dev.yml
docker-compose-test.yml

Add metabase to dev/test docker compose file

---

dataworkspace/proxy.py

Allow extra fonts/imgs/styles for GTM preview

---

dataworkspace/dataworkspace/apps/datasets/utils.py

Embed via the data-workspace quicksight user

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json

(feat) Bump JupyterLab R to Fargate 1.4.0

---

dataworkspace/dataworkspace/apps/applications/forms.py
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html
dataworkspace/dataworkspace/templates/visualisation_users_give_access.html
dataworkspace/dataworkspace/templates/visualisation_users_with_access.html
dataworkspace/dataworkspace/tests/applications/test_views.py
dataworkspace/dataworkspace/tests/datasets/test_views.py

Use user access type from vis catalogue item

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/core/templatetags/core_filters.py
dataworkspace/dataworkspace/tests/core/test_templatetags.py

Allow strong and linebreaks in markdown

---

dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/tests/datasets/test_views.py

Metabase dashboard ID should be an integer

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/dw_admin/migrations/0001_initial.py
dataworkspace/dataworkspace/settings/base.py

Enable redirect management in the site

---

dataworkspace/proxy.py
requirements.txt

(feat) Bump hawk-server-asyncio

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json
theia/Dockerfile
theia/start.sh

(feat) Theia on Fargate 1.4.0

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/running.html

(feat) Tweak visualisation header text

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/urls_visualisations.py
test/test_application.py

(feat) Allow foward slash in GitLab branch names

---

.github/dependabot.yml

(build) Update dependabot reviewers

---

CHANGELOG.md
infra/ecs_main_gitlab.tf

(feat) Reduce GitLab RDS instances

---

CHANGELOG.md
infra/ecs_main_gitlab.tf
infra/ecs_main_gitlab_container_definitions.json
infra/main.tf

(feat) Configurable GitLab size

---

.envs/sample.env
.envs/test.env

Point to aws quicksight source of truth for region

---

CHANGELOG.md
dataworkspace/proxy.py
test/test_application.py

Ticket: https://trello.com/c/sYyEn1Sl/499

Implement sentry on the proxy

---

dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/tests/applications/test_utils.py

Ignore missing users in quicksight

---

dataworkspace/proxy.py

e.g. https://sentry.ci.uktrade.digital/dit/data-workspace/issues/27793/events/1289719/

Ignore some more cancelled async task errors

---

CHANGELOG.md
s3sync/Dockerfile

(feat) Bump mobius3 to version that better supports EFS

---

dataworkspace/proxy.py

This was a quick attempt to ignore the CancelledErrors that get raised
in the proxy intermittently, but it hasn't worked and causes another
error that's slightly more confusing. So better to rip this out and look
at the root problem again.

Stop hiding CancelledErrors

---

CHANGELOG.md
infra/ecs_main_admin_container_definitions.json

feat: make Data Explorer visible

---

dataworkspace/dataworkspace/apps/applications/utils.py

fix: suppress 404 quicksight error

---

dataworkspace/dataworkspace/templates/tools.html
dataworkspace/dataworkspace/tests/core/test_views.py

fix: use appstream URL on tools page

---

dataworkspace/dataworkspace/templates/tools.html
dataworkspace/dataworkspace/tests/core/test_views.py

fix: show spss/state link based on permissions

---

dataworkspace/dataworkspace/static/data-workspace.css
dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py

Footer is updated to match the new design as per https://trello.com/c/00IJSmmr

footer is updated to match the new design

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/tests/datasets/test_views.py

- allow for searching by source tag name
- weight dataset name over short description and source tag name in search results

feat: search weighting  

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py
dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py

fix: eventlog including visualisation approvals

---

.github/pull_request_template.md

chore: remove README prod from PR template, since it's never ticked

---

dataworkspace/dataworkspace/apps/applications/views.py

Remove the dash as it isn't needed and looks confusing.

typo: remove dash from end of query param

---

dataworkspace/proxy.py

fix: POSTing forms since CSRF check would fail if Django thinks its on https

---

dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py

fix: ignore unspecified related objects

---

dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/templates/eligibility_criteria_not_met.html
dataworkspace/dataworkspace/templates/request_access.html
dataworkspace/dataworkspace/templates/request_access_success.html

fix: add govuk link styles to some missing links

---

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/templates/datasets/master_dataset.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html
dataworkspace/dataworkspace/templates/partials/code_snippets.html
dataworkspace/dataworkspace/templates/partials/contact.html
dataworkspace/dataworkspace/templates/partials/unauthorised_warning.html

Address some design inconsistencies between dataset pages.

Dataset page template updates

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/apps/explorer/urls.py
dataworkspace/dataworkspace/apps/explorer/views.py
dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/templates/explorer/_base.html
dataworkspace/dataworkspace/templates/explorer/index.html
dataworkspace/dataworkspace/templates/tools.html
dataworkspace/dataworkspace/tests/explorer/test_views.py
dataworkspace/dataworkspace/urls.py
dataworkspace/dataworkspace/utils.py
dataworkspace/proxy.py
test/test_application.py

In preparation for integrating the Data Explorer code with Data
Workspace, create a blank tool as a separate app using separate
templates with IP restrictions. This tool is hidden by a Django-Waffle
flag, allowing fine-grained control over who gets to see it.

feat: add blank tool to Data Workspace

---

dataworkspace/dataworkspace/apps/api_v1/views.py

fix: starting tools in some cases broken due to accidental comma

---

CHANGELOG.md
theia/requirements.in
theia/requirements.txt

The VSCode/Theia Python extension already had the Theia side of things. It just needed the Notebook side.

feat: support opening Jupyter notebooks in Theia

---

theia/requirements.in
theia/requirements.txt

So it can run the examples in the Datasets pages

feat: add Python SQL packages to Theia

---

CHANGELOG.md
dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html
dataworkspace/dataworkspace/tests/explorer/test_views.py

fix: hook up feedback link in data explorer

---

CHANGELOG.md
dataworkspace/dataworkspace/templates/partials/tool_section.html

fix: open tools in a new tab

---

pgadmin/pgadmin-config.py

We don't have internet access, and there is speculation it's related to failing to properly start
Briefly tested locally

feat: avoid unnecessary check for updates

---

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html

fixing variable error in template

fixing variable error in template

---

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html

This PR fixes related data, single dataset width fix because of old variable name

related data, single dataset width fix

---

dataworkspace/dataworkspace/apps/datasets/forms.py

Changing sort option labels as per discussions

changing sort option labels

---

Dockerfile

fix: add psycopg2 back to dockerfile

---

dataworkspace/start-celery.sh
dataworkspace/start-dev.sh
dataworkspace/start-test.sh
docker-compose-dev.yml
docker-compose.yml
test/test_application.py

This PR is the first step in moving Data Workspace celery workers to a separate service. It sets up a docker container, based on data-workspace image, for celery workers.

move celery workers into separate docker container

---

Jenkinsfile

fix: deployment clusters for staging_prod

---

dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/tests/datasets/test_views.py

This PR os to fix dataset search to make sure visualisation tags are matched

fixing dataset search to make sure visualisation tags are matched

---

Dockerfile

fix: up openssl version

---

dataworkspace/dataworkspace/apps/accounts/admin.py
dataworkspace/dataworkspace/apps/applications/admin.py

Useful admin tweaks

---

dataworkspace/dataworkspace/apps/applications/utils.py

Allow for managing tool query sync db task via waffle flags

fix: add switch to control db syncing

---

dataworkspace/dataworkspace/settings/base.py
dataworkspace/proxy.py
dataworkspace/sentry.py

fix: add more sentry integrations

---

Dockerfile

fix: update chromium version

---

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py
dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py

The datasets API endpoint can fail for a number of reasons:
1) No primary key on the table
2) The "table" is actually a view, and so doesn't have primary keys.
The latter example comes up because we're starting to deprecate some
tables that are named incorrectly, and we're changing them over to views
on the correctly-named tables.
We might want to make this endpoint work without primary keys at some
point, but this is simply so that we can more easily recognise the
actual problem in sentry for now, rather than simply getting an "invalid
sql" error.

fix: provide friendlier error messages for endpoint

---

dataworkspace/dataworkspace/apps/api_v1/datasets/views.py
dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py

fix: detect when table doesn't exist

---

dataworkspace/dataworkspace/apps/core/utils.py

This block of code is infrequently throwing 'tuple concurrently updated'
errors. The historical remediation for this has been to lock the
offending queries, so let's do that again.

fix: lock ddl trigger creation/setup

---

tools/pgadmin/Dockerfile

The user and group IDs were the wrong way round

fix: saving sql files in pgAdmin

---

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py
dataworkspace/dataworkspace/apps/api_v1/datasets/views.py
dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py

Part of the full text search firebreak task

feat: add source tables to the dataset api response

---

dataworkspace/dataworkspace/apps/applications/utils.py

The delete_unused_datasets_users task sometimes fails if the temporary user role has privileges. These need to be revoked before attempting to delete the role.
See https://sentry.ci.uktrade.digital/organizations/dit/issues/34154/ for an example error that this PR should fix

feature: revoke temporary user privileges so that DROP USER succeeds

---

dataworkspace/dataworkspace/apps/explorer/tasks.py

Do not log syntax errors generated by users to sentry.

fix: do not log syntaxy errors to sentry

---

dataworkspace/dataworkspace/apps/applications/utils.py

Fixes https://sentry.ci.uktrade.digital/organizations/dit/issues/35226/

fix: get the dataset db username from the db config in settings

---

dataworkspace/dataworkspace/apps/datasets/admin.py

Fix issue stopping users editing visualisations due to missing user on form init

fix: ensure user is added to vis admin form

---

Dockerfile
dataworkspace/dataworkspace/cel.py
dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/utils.py
dataworkspace/proxy.py
etc/nginx/nginx.conf
requirements-dev.txt
requirements.in
requirements.txt

Log from the proxy and Django in ECS format, which should make reading logs easier as 1) ELK can read them more easily, and 2) exceptions/multi-line logs won't be split across separate records.

ECS logging

---

dataworkspace/dataworkspace/templates/_base.html
dataworkspace/dataworkspace/tests/core/test_views.py
test/selenium/common.py
test/selenium/test_request_data.py
test/selenium/workspace_pages.py

fix: remove "request data" header link

---

dataworkspace/dataworkspace/apps/your_files/utils.py
dataworkspace/dataworkspace/apps/your_files/views.py

When triggering the data flow pipeline pass:
- The header name from the csv file
- The column for the new table
- The data type for the column
Also fixes naming of schema/table passed to data flow

fix: add header and new column names

---

dataworkspace/dataworkspace/templates/datasets/master_dataset.html

This PR is to fix code snippets details tag, so that the arrow changes direction on open/close.

fixing details css class override to fix arrow

---

dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/templates/files.html
dataworkspace/dataworkspace/templates/your_files/create-table.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

feat: add "create table" page to tablemaker flow

---

infra/main.tf
infra/s3_notebooks.tf

fix: allow multiple cors domains for notebooks s3 bucket

---

infra/ecs_main_admin.tf

fix: remove old unused store creds to s3 task

---

infra/ecs_main_admin.tf

Reverts uktrade/data-workspace#1218

Revert "fix: remove old unused store creds to s3 task"

---

dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html

Adding last updated date to visualisation details page

adding modified date to visualisation page

---

dataworkspace/dataworkspace/templates/partials/code_snippets.html

fix: open data explorer in new tab

---

dataworkspace/dataworkspace/templates/_base.html

fix: open data hub link in the same browser window

---

Jenkinsfile

feat: switch to ecr

---

dataworkspace/dataworkspace/templates/datasets/master_dataset.html
dataworkspace/dataworkspace/templates/partials/code_snippets.html

We don't need users to pull and initialise the script for every code snippet.

refactor: prevent duplicate scripts/initialisation

---

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/templates/datasets/master_dataset.html
dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html

fix: remove superuser text

---

dataworkspace/dataworkspace/apps/your_files/forms.py
dataworkspace/dataworkspace/apps/your_files/urls.py
dataworkspace/dataworkspace/apps/your_files/utils.py
dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/forms.py
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-name.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
dataworkspace/dataworkspace/templates/your_files/create-table-table-exists.html
dataworkspace/dataworkspace/templates/your_files/files.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

- If the table name is invalid, allow it to be corrected
- If the table already exists in their schema, confirm overwrite
- If the table does not exist, run the DAG
closes: https://trello.com/c/spFdGRVN/1391-csv-upload-choose-table-name-table-already-exists-page-4

feat: allow users to choose their own table name

---

dataworkspace/dataworkspace/templates/running_base.html

fix: add skip links to visualisation frame

---

dataworkspace/dataworkspace/templates/partials/tool_section.html

fix: provide context for tools "read more" links

---

dataworkspace/dataworkspace/templates/datasets/select.html

fix: associate label to select field correctly

---

gitlab/Dockerfile

feat: bump GitLab to latest 12

---

dataworkspace/dataworkspace/apps/your_files/constants.py
dataworkspace/dataworkspace/apps/your_files/forms.py
dataworkspace/dataworkspace/apps/your_files/templatetags/your_files_tags.py
dataworkspace/dataworkspace/apps/your_files/urls.py
dataworkspace/dataworkspace/apps/your_files/utils.py
dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/forms.py
dataworkspace/dataworkspace/templates/design_system/select.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-data-types.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-name.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

Adds a new step to the create table form to allow the user to select the data types for each column (with sane defaults).
Currently deployed to dev for ease of testing.

feat: allow for table column data type selection

---

dataworkspace/dataworkspace/templates/datasets/master_dataset.html

fix: setup copy after including copy JS

---

dataworkspace/dataworkspace/apps/your_files/forms.py
dataworkspace/dataworkspace/tests/your_files/test_views.py

Ensure table names are no longer than 42 chars

Ensure table name is no longer than 42 chars

---

dataworkspace/dataworkspace/apps/explorer/tasks.py

Log a warning rather than an exception when a users sql contains incorrect data (e.g. invalid casting)

fix: catch data errors in users sql

---

dataworkspace/dataworkspace/apps/datasets/views.py

Check that contacts exist before accessing their email addresses in notification emails.

fix: check contacts exist before displaying

---

dataworkspace/dataworkspace/apps/datasets/views.py

Check that the contact field is set before sending email

fix: check the contact is set before sending email

---

dataworkspace/dataworkspace/tests/your_files/test_views.py

fix: remove broken line from your_files test that's no longer needed

---

dataworkspace/dataworkspace/templates/about.html

updating about page content

---

dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/tests/your_files/test_views.py

Tiny fix and update of test to ensure submitted form data types are used

fix: ensure form data is sent to airflow task

---

infra/main.tf
infra/rds_admin.tf

AWS has updated this automatically so our TF is currently out of sync and trying to downgrade the DBs.

fix: upgrade default admin db version

---

mirrors-sync-cran-binary/Dockerfile

fix: non-buildable CRAN binary builder

---

mirrors-sync-cran-binary/Dockerfile
mirrors-sync-cran-binary/build.R

https://trello.com/c/sDDnhtCA/1650-add-flextable-openxlsx-and-formattable-to-the-cran-binary-mirror

feature: add flextable,formattable,openxlsx to the binary cran mirror

---

tools/theia/yarn.lock

feat: bump dependency to avoid vulnerability

---

tools/theia/package.json
tools/theia/yarn.lock

feat: bump js-yaml, and use 'resolutions' to persist bumped transitive dependencies

---

infra/elasticsearch_datasets.tf
infra/main.tf
infra/security_groups.tf

feat: add elasticsearch for datasets finder

---

s3sync/requirements.txt

Image has been built locally, pushed to dev, and tested on Theia by creating a symlink

feature: bump the mobius3 version to allow symlinks to work

---

dataworkspace/dataworkspace/templates/core/user-satisfaction-survey.html

Copy change requested at https://trello.com/c/1u78r6M9/1597-user-satisfaction-survey-form

fix: update copy on user satisfaction survey

---

dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/tests/datasets/test_utils.py

Fixes https://sentry.ci.uktrade.digital/organizations/dit/issues/37439

fix: connect to datasets db using connection alias, not database name

---

dataworkspace/dataworkspace/templates/core/support.html
dataworkspace/dataworkspace/templates/core/user-satisfaction-survey.html
dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/templates/datasets/source_table_column_details.html
dataworkspace/dataworkspace/templates/explorer/index.html
dataworkspace/dataworkspace/templates/finder/index.html
dataworkspace/dataworkspace/templates/request_data/check-answers.html
dataworkspace/dataworkspace/templates/request_data/confirmation-page.html
dataworkspace/dataworkspace/templates/request_data/data-description.html
dataworkspace/dataworkspace/templates/request_data/data-licence.html
dataworkspace/dataworkspace/templates/request_data/data-location.html
dataworkspace/dataworkspace/templates/request_data/data-owner-or-manager.html
dataworkspace/dataworkspace/templates/request_data/data-purpose.html
dataworkspace/dataworkspace/templates/request_data/index.html
dataworkspace/dataworkspace/templates/request_data/security-classification.html
dataworkspace/dataworkspace/templates/request_data/who-are-you.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-data-types.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-name.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
dataworkspace/dataworkspace/templates/your_files/create-table-failed.html
dataworkspace/dataworkspace/templates/your_files/create-table-processing.html
dataworkspace/dataworkspace/templates/your_files/create-table-success.html
dataworkspace/dataworkspace/templates/your_files/create-table-table-exists.html

https://trello.com/c/I5T41kKy/1438-page-title

fix: consistent page titles

---

Dockerfile

up openssl version

---

dataworkspace/dataworkspace/templates/partials/unauthorised_warning.html

This PR changes the message to show when user views a dataset catalogue page if they don't have access to it.

changing message shown when user doesn't have access to a dataset

---

dataworkspace/dataworkspace/apps/finder/elasticsearch.py

Sorting sort option to elastic search for consistency across search aggregation results and documents.

adding sort to dataset finder results for consistency

---

infra/s3_uploads.tf

Add versioning and logging to s3 buckets

fix: add versioning and logging to s3

---

infra/rds_admin.tf

We ran out of storage for the admin DB because of increased use. Let's
bump it.

fix: increase admin db storage

---

infra/elasticsearch_datasets.tf

fix: setup ES logs to cloudwatch

---

tools/python-setup.sh
tools/theia/Dockerfile

feat: ensure Python packages installed from mirror for consistency + nltk install

---

requirements-dev.txt
requirements.in
requirements.txt

feat: bump Django

---

tools/theia/package.json
tools/theia/yarn.lock

build(deps): bump is-svg

---

dataworkspace/dataworkspace/apps/explorer/admin.py

https://sentry.ci.uktrade.digital/organizations/dit/issues/37903

fix: only attempt user admin actions on user objects

---

dataworkspace/package-lock.json
dataworkspace/package.json

build(deps): bump packages to avoid SSRI vulnerability

---

tools/theia/package.json
tools/theia/yarn.lock

build(deps): bump y18n

---

dataworkspace/dataworkspace/templates/datasets/data_cut_preview.html

Change text as per PM's request for column filter.

change text as per PM request

---

superset/superset_config.py

- Role is assigned enough permissions to access the site without error
- Role is assigned access to all slices (datasources) on the site
- Role perms are refreshed on every login

feat: create new per-user role for public users

---

superset/superset_config.py

fix: stop Superset redirecting to HTTP, rather than HTTPS

---

superset/superset_config.py

Update logged in users permissions before redirect

fix: apply perms if the user is already logged in

---

dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/templates/partials/tool_section.html
dataworkspace/dataworkspace/templates/tools.html

- Adds superset to the top of the tools page with a "new" label
- Update button colours to match new designs
- Add in-page link to "how to request access"

feature: add superset to tools page

---

dataworkspace/dataworkspace/apps/applications/views.py
dataworkspace/dataworkspace/templates/superset_running.html

https://trello.com/c/GnJUMbk7/1710-step-5-superset-link-to-iframe-page

feature: open superset dashboard in iframe

---

.envs/sample.env

fixed a typo in sample.env which caused an issue when bootstrapping a new dev environment
* [ x] Have tests been added to cover any changes?

letter D was missing from DATA_FINDER_ES_HOST

---

dataworkspace/dataworkspace/templates/datasets/index.html
dataworkspace/dataworkspace/tests/datasets/test_views.py

Added role="status" to search results count span

update to search-results-count with accessible role + unit tests

---

dataworkspace/dataworkspace/apps/datasets/models.py
dataworkspace/dataworkspace/tests/test_models.py

get the actual value for a linked reference dataset record

fix: ensure correct value is used for linked field

---

dataworkspace/dataworkspace/apps/datasets/utils.py

Fixes https://sentry.ci.uktrade.digital/organizations/dit/issues/36794

fix: skip deleted visualisations when updating last_updated_date

---

tools/requirements.in
tools/requirements.txt
tools/requirements_v3.in
tools/requirements_v3.txt

build(deps): bump tensorflow and others to avoid vulnerabilities

---

tools/requirements.txt
tools/requirements_v3.txt

build(deps): Bump pyyaml to avoid vulnerability

---

superset/superset_config.py

Intercept requests to superset and update the Public user's permissions

feat: sync permissions per request for public users

---

requirements-dev.txt
requirements.in
requirements.txt

build(deps): bump django

---

requirements-dev.txt
requirements.in
requirements.txt

build(deps): bump DRF

---

dataworkspace/dataworkspace/templates/_base.html

`</html>` was missing from _base.html template

Fix closing html tag

---

superset/superset_config.py

- Adds a new user-level editor role
- For each request ensure users only have access to the datasets they created
- Clean up superset config to fix linter errors

feat: hide other users slices/datasources/dashboards

---

tools/theia/yarn.lock

build(deps): bump Theia dependencies

---

tools/theia/package.json
tools/theia/yarn.lock

build(deps): bump Theia deps

---

dataworkspace/package-lock.json

build(deps): bump package.json deps

---

requirements-dev.txt
requirements.txt
tools/requirements.txt
tools/requirements_v3.txt

bump(deps): bump Python deps

---

dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html

fix: use correct url signature

---

tools/requirements.in
tools/requirements.txt
tools/requirements_v3.in
tools/requirements_v3.txt

upgrading Tensorflow version to 2.5.0

upgrading Tensorflow version to 2.5.0

---

dataworkspace/dataworkspace/apps/finder/views.py
dataworkspace/dataworkspace/templates/finder/index.html
dataworkspace/dataworkspace/templates/finder/results.html
dataworkspace/dataworkspace/tests/finder/test_views.py

add dataset link to dataset finder detail page

add dataset link to dataset finder detail page

---

dataworkspace/dataworkspace/apps/applications/spawner.py

feat: bump time for spawner to make creds before failing

---

dataworkspace/dataworkspace/apps/core/utils.py

feat: ensure to release connection to the admin db when making creds

---

Dockerfile

build(deps): bump nginx

---

dataworkspace/dataworkspace/apps/applications/spawner.py
dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/apps/explorer/tasks.py

As recommended at https://github.com/jneight/django-db-geventpool#using-orm-when-not-serving-requests

feat: more closing of connections after celery tasks

---

dataworkspace/dataworkspace/apps/core/utils.py

refactor: consistent method of closing connections

---

dataworkspace/dataworkspace/apps/applications/spawner.py
dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/apps/explorer/tasks.py

Ensure all Django-made connections closed in Celery, out of paranoia

---

dataworkspace/dataworkspace/apps/core/utils.py

fix: ensure master user does have all required roles

---

dataworkspace/dataworkspace/apps/core/utils.py

fix: creds creation

---

dataworkspace/dataworkspace/apps/core/utils.py

feat: bump cache blocking timeout

---

dataworkspace/dataworkspace/apps/applications/utils.py

feat: no need to run revoke SQL on schemas for temporary user

---

dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/core/utils.py

feat: tweak lock timeouts and number of times locks are requested when deleting users

---

dataworkspace/dataworkspace/apps/applications/utils.py

Was overzelous in removing them: there are still some users with privileges left

feat: restore schema revoke

---

dataworkspace/dataworkspace/apps/applications/utils.py

feat: don't try to revoke on pg_tables

---

dataworkspace/dataworkspace/apps/applications/utils.py

feat: now schemas are revoked from temporary user, don't do it in job

---

dataworkspace/dataworkspace/apps/core/utils.py

fix: ensure master user has application role privilage

---

dataworkspace/dataworkspace/static/data-workspace.css
dataworkspace/dataworkspace/templates/case_studies/casestudy_detail.html

Allow for rich text in quote field

fix: mark quote text safe for case study

---

tools/requirements_v3.txt

bump pillow to 8.2.0 in requirements_v3

bump pillow to 8.2.0 in requirements_v3

---

requirements-dev.txt
requirements.txt
tools/requirements.txt
tools/requirements_v3.txt

bump urllib3 to 1.26.5

---

dataworkspace/dataworkspace/apps/applications/utils.py

fix: lower case quicksight user email when looking up DW user

---

dataworkspace/dataworkspace/apps/datasets/forms.py

fix: front page search filters on v2, currently behind a feature flag

---

postgres/entrypoint.sh

build: fix starting postgresl via docker-compose.yml

---

requirements-dev.in
requirements-dev.txt

build(deps): bump pyppeteer to avoid websockets vulnerability

---

dataworkspace/dataworkspace/apps/datasets/forms.py

Changing sub text on Dataset filtering page to GDS standard.

Changing sub text to GDS standard

---

dataworkspace/dataworkspace/apps/core/utils.py

fix: giving master user team role

---

dataworkspace/dataworkspace/apps/explorer/schema.py

perf: faster fetching of db schema in Data Explorer

---

dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/your_files/forms.py
dataworkspace/dataworkspace/apps/your_files/urls.py
dataworkspace/dataworkspace/apps/your_files/utils.py
dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-name.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm-schema.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

Adding an additional step to allow user to pick team schema while saving csv as a table into.

Your files team schema

---

dataworkspace/dataworkspace/apps/your_files/views.py

your files team schemas fix, back button and user schema.

fix for your files team schemas

---

dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

change text to suit recent team schema changes

change text to suit recent team schema changes

---

Dockerfile

Updated libxml-dev apt dependency in data-workspace Dockerfile

fix issue building dockerfile

---

dataworkspace/dataworkspace/apps/your_files/views.py

fix for create table when user is not in teams

fix for create table when user is not in teams

---

dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html

changing font to match other section of the page

changing font to match other section of the page

---

dataworkspace/dataworkspace/templates/quicksight_running.html

After some hacking locally, this _seemed_ to fix the issue

fix: attempt to fix sort popups disappearing QuickSight

---

rstudio/Dockerfile

Add libgdal-dev to RStudio base image

---

dataworkspace/dataworkspace/apps/datasets/views.py

feat: support vega-lite's 'data' being a dictionary

---

remote-desktop/Dockerfile
remote-desktop/org.qgis.qgis.desktop
remote-desktop/start.sh
s3sync/start.sh

The change to s3sync is to avoid syncing temporary files that break the remote

feat: add qgis to remote desktop

---

dataworkspace/dataworkspace/apps/applications/utils.py

feature: add dataset showing 10 most recent tool launch times

---

.envs/sample.env
.envs/superset-sample.env
.gitignore
README.md
docker-compose-superset-dev.yml
postgres/2-init-databases.sql
superset/Dockerfile
superset/gunicorn.dev.conf.py
superset/superset_config.py

WIP to attempt to get superset running nicely under docker compose.
If you are not rebuilding from scratch you will need to create a new database within the postgres container 
```
create database superset;
```
You should then be able to run 
```
docker-compose -f docker-compose-dev.yml -f docker-compose-superset-dev.yml up
```
And then visit http://superset-admin.dataworkspace.test:8001/

feature: allow for running superset locally

---

tools/jupyterlab-python/Dockerfile
tools/requirements.in
tools/requirements.txt

build(deps): add regex to Python-based tools

---

rstudio/Dockerfile
tools/jupyterlab-python/Dockerfile
tools/theia/Dockerfile

build(deps): add vim and emacs

---

superset/README.md

feature: add sql statements required to set up Editor role locally

---

dataworkspace/dataworkspace/apps/core/utils.py

fix: revert cursor name change

---

superset/superset_config.py

/superset/sqllab/history was previously returning 500 as it was trying to serialize a decimal to JSON. This adds a custom JSON encoder to get around this.

fix: use custom json encoder to allow superset query history to work

---

superset/superset_config.py

Fix issue with "always true" query on sql tables

fix: ensure user is given access to their own table only

---

dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py
dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
dataworkspace/dataworkspace/tests/factories.py

feat: ensure to serialize User when they are the related model in the event log

---

dataworkspace/dataworkspace/templates/about.html

New section on the about page with links to help centre roadmap

added roadmap section and removed embedded unicode NNBSP characters

---

remote-desktop/Dockerfile
remote-desktop/index.html
remote-desktop/nginx.conf
remote-desktop/start.sh

build(deps): bump to noVNC 1.2.0

---

dataworkspace/dataworkspace/templates/request_data/index.html

Update to the copy on the request access form

changes to request access text

---

superset/superset_config.py

Monkey patch the superset rest api "related owner" filters to filter out any users that are not "editors". This ensures editors can only share datasets/charts/dashboards with other editors.

fix: hide non-editor users from related api queries

---

dataworkspace/proxy.py
test/test_application.py

This is so visualisations can tailor content based on the current user

feat: pass SSO headers to visualisation

---

rstudio/Dockerfile

Follow some of the advice about minimising amount of data written to home directory in RStudio found here: https://support.rstudio.com/hc/en-us/articles/218417097-Filling-up-the-home-directory-with-RStudio-Workbench-RStudio-Server
Namely:
Turn off the session time out
Turn off the default save action

feature: minimise amount of data written to home directory in RStudio

---

dataworkspace/dataworkspace/static/data-grid.css
dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html

Applying GDS styles to ag-grid aka enhanced-grid

adding data-grid custom css

---

dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/query_results.html
dataworkspace/dataworkspace/apps/explorer/utils.py

This PR is to convert newlines to br, show indents and format json in query results

Convert newlines to <br>, show pretty json with double quotes and indent

---

test/selenium/explorer_pages.py

xpath query for the pre formatted text

---

dataworkspace/dataworkspace/apps/explorer/utils.py

fix: return all rows for data explorer queries

---

Dockerfile

fix: upgrade openssl

---

dataworkspace/dataworkspace/apps/request_access/views.py

fix: use standard zendesk process for non-gitlab vis

---

dataworkspace/dataworkspace/apps/request_access/views.py
dataworkspace/dataworkspace/templates/request_access/you_have_access.html
dataworkspace/dataworkspace/tests/request_access/test_views.py

fix: show appropriate message if user with access hits /request-access

---

dataworkspace/dataworkspace/apps/datasets/admin.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/templates/datasets/master_dataset.html

- Fix the DatasetVisulisation form to allow for deletions
- Only show non-deleted visualisations in the ui

fix: allow for soft deleting visualisations

---

dataworkspace/dataworkspace/apps/datasets/urls.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/templates/datasets/data_cut_source_detail.html

- A couple of fixes to allow (limited) downloads to source table data grids

fix: small tweaks to allow master dataset downloads

---

dataworkspace/dataworkspace/apps/explorer/forms.py
dataworkspace/dataworkspace/apps/explorer/tasks.py

This PR is to allow users use `EXPLAIN` for their queries in Data Explorer

Data explorer explain query

---

dataworkspace/dataworkspace/apps/explorer/forms.py
dataworkspace/dataworkspace/apps/explorer/tasks.py
dataworkspace/dataworkspace/tests/explorer/test_views.py

fix: update test to match error wording

---

dataworkspace/dataworkspace/apps/datasets/admin.py
dataworkspace/dataworkspace/apps/dw_admin/forms.py

Reduce the number of select options on the page by setting the user fields to autocomplete

fix: use autocomplete fields for user fields

---

dataworkspace/proxy.py

allow mirror access from the root domain

fix: allow mirror access from the root domain

---

dataworkspace/dataworkspace/apps/datasets/urls.py
dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/static/data-grid.js
dataworkspace/dataworkspace/templates/datasets/reference_dataset_grid.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_column_details.html
dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
dataworkspace/dataworkspace/tests/datasets/test_views.py

This PR:
Updates reference dataset catalogue page to new design
Adds columns and code snippets
adds new overflow columns page
adds new enhanced preview page
allows data download as both csv and json

Reference dataset catalogue page update

---

infra/elasticsearch_datasets.tf

feature: increase datasets finder elasticsearch instance count to 2

---

dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/templates/datasets/master_dataset.html

fix: hide unpublished related visualisation catalogue items

---

dataworkspace/dataworkspace/templates/partials/tool_section.html
dataworkspace/dataworkspace/templates/tools.html
dataworkspace/dataworkspace/tests/core/test_views.py

- Update tools page content to match suggested text (https://trello.com/c/cl9bL9vv/2178-request-process-instruction-update)
- Remove the requirements section at the bottom of the tools page
- Update request access to [tool] links to point to the "request access" form

feat: update tools page content

---

tools/requirements_v3.txt

updating sqlparse and pillow packages in tools

updating sqlparse and pillow packages in tools

---

tools/theia/package.json
tools/theia/yarn.lock

upgrade axios version

---

dataworkspace/dataworkspace/templates/finder/results.html

fix: add csrf token to finder page

---

dataworkspace/dataworkspace/apps/api_v1/core/views.py
dataworkspace/dataworkspace/apps/api_v1/views.py
dataworkspace/dataworkspace/apps/applications/utils.py
dataworkspace/dataworkspace/apps/explorer/tasks.py
dataworkspace/dataworkspace/apps/impersonation/urls.py
dataworkspace/dataworkspace/apps/impersonation/views.py
dataworkspace/dataworkspace/tests/api_v1/core/test_views.py
dataworkspace/dataworkspace/utils.py
dataworkspace/proxy.py

Return impersonated user credentials from the superset endpoint if we are in impersonation mode.

feat: add impersonation to superset

---

infra/main.tf
infra/route_53.tf
infra/security_groups.tf

refactor: remove unused registry components

---

infra/elasticsearch_datasets.tf
infra/main.tf

feat: make Dataset Finder Elasticsearch instance have a configurable number of instances

---

dataworkspace/dataworkspace/apps/datasets/forms.py
dataworkspace/dataworkspace/static/data-workspace.css
dataworkspace/dataworkspace/templates/datasets/scrolling_filter.html

Search icon and hint text for scrolling filter widget

fix: adding icon and hint text to scrolling filter widget

---

dataworkspace/dataworkspace/datasets_db.py

fix: filter out null dates from metadata

---

dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/datasets/models.py
dataworkspace/dataworkspace/apps/datasets/urls.py
dataworkspace/dataworkspace/apps/datasets/utils.py
dataworkspace/dataworkspace/apps/explorer/tasks.py
dataworkspace/dataworkspace/datasets_db.py
dataworkspace/dataworkspace/settings/base.py
dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
dataworkspace/dataworkspace/tests/conftest.py
dataworkspace/dataworkspace/tests/datasets/test_utils.py

https://trello.com/c/JcwHuNZC/2317-notifications-6-data-cut-dataset-log-structure-changes

feature: store datacut query structure changes in dataflow.metadata

---

dataworkspace/dataworkspace/apps/datasets/models.py

fix: pass CustomDatasetQuery object to get_changelog method and not id

---

dataworkspace/dataworkspace/apps/datasets/utils.py

fix: strip semicolons from CustomDatasetQuery sql when getting columns

---

tools/requirements.txt
tools/requirements_v3.txt

bump to tensorflow patch version to address dependabot alerts

fix: bump tensorflow in tools to address security

---

dataworkspace/dataworkspace/apps/datasets/utils.py

adding `if` statement to only update `visualisation_link.data_source_last_updated` when a value exists

fix: only update last_updated_date when value exists

---

dataworkspace/dataworkspace/apps/datasets/urls.py

fix: change changelog url pattern source_id from int to uuid

---

dataworkspace/dataworkspace/datasets_db.py

fix: return empty changelog if source table has no entry in metadata

---

dataworkspace/dataworkspace/apps/datasets/utils.py

feature: add more logging to email notification celery task

---

dataworkspace/dataworkspace/apps/datasets/utils.py

fix: continue when no changelog records found rather than return

---

Makefile
docker-compose-dev.yml

Add a command to `Makefile` to run code quality checks inside container

fix: run check commands inside docker container

---

dataworkspace/dataworkspace/apps/datasets/urls.py

Necessary as the id can be either an int of a uuid

fix: set id pattern to string for source table changelog

---

dataworkspace/dataworkspace/apps/accounts/admin.py

fix: pass the actual user that is being modified and not request.user

---

dataworkspace/dataworkspace/apps/api_v1/accounts/serializers.py
dataworkspace/dataworkspace/tests/api_v1/accounts/test_views.py

API user sso field is now in uuid format not hex

removes hex formatting for user sso uuid in API

---

dataworkspace/dataworkspace/apps/datasets/utils.py

Fix issue where soft deleted datasets were included in metadata sync

fix: do not save metadata for deleted ref datasets

---

dataworkspace/dataworkspace/datasets_db.py

fix: do not json load table structure if null

---

dataworkspace/dataworkspace/apps/datasets/utils.py

fix: continue if no columns have been added or removed

---

dataworkspace/dataworkspace/datasets_db.py

fix:only compare rows that have a table_structure when making changelog

---

dataworkspace/dataworkspace/apps/datasets/migrations/0104_referencedataset_is_draft.py

rename migration file to fix merge issue

---

dataworkspace/start-celery-dev.sh
dataworkspace/start-celery.sh
dataworkspace/start-dev.sh
dataworkspace/start-test.sh
dataworkspace/start.sh
requirements-dev.txt
requirements.txt

fix: update celery to fix CVE-2021-23727

---

tools/requirements.in
tools/requirements.txt
tools/requirements_v3.in
tools/requirements_v3.txt

fix: upgrade nltk to fix CVE-2021-3842

---

dataworkspace/dataworkspace/apps/api_v1/datasets/serializers.py
dataworkspace/dataworkspace/apps/api_v1/datasets/views.py
dataworkspace/dataworkspace/tests/api_v1/datasets/test_views.py

feature: edit api endpoints for reference field reporting

---

dataworkspace/dataworkspace/apps/datasets/models.py
dataworkspace/dataworkspace/apps/datasets/pipelines/utils.py
dataworkspace/dataworkspace/apps/datasets/pipelines/views.py
dataworkspace/dataworkspace/tests/datasets/test_pipelines.py

sync derived pipeline changes to Data Flow

sync derived pipeline changes to Data Flow

---

dataworkspace/dataworkspace/apps/your_files/views.py

Renamed the airflow task to correspond with the new name.

fix: renamed airflow task

---

dataworkspace/dataworkspace/templates/about.html

New content added to the Data Workspace 'about page' on ```about.html```
~* [ ]~ Have tests been added to cover any changes?

feat: update about page on data workspace

---

tools/jupyterlab-python/Dockerfile
tools/rstudio/Dockerfile
tools/theia/Dockerfile

After e830aecd969369c5141bfa77e93826d80e0b7aea has been running for a bit in prod, and announced, this should be able to be deployed

feat: remove apt/apt-get from sudoers

---

dataworkspace/dataworkspace/apps/datasets/pipelines/urls.py
dataworkspace/dataworkspace/apps/datasets/pipelines/utils.py
dataworkspace/dataworkspace/apps/datasets/pipelines/views.py
dataworkspace/dataworkspace/templates/datasets/pipelines/list.html
dataworkspace/dataworkspace/tests/datasets/test_pipelines.py

Add logic to the run button.
- Trigger the dag on airflow
- Pass the users name to be logged on the airflow side

fix: run pipeline on airflow by clicking the run button

---

dataworkspace/dataworkspace/apps/your_files/utils.py

Add mapping for schema to our own field names

translate number to numeric

---

requirements-dev.txt

fix: upgrade ipython

---

requirements-dev.txt
requirements.txt

build(deps): bump sentry-sdk

---

tools/requirements.txt

build(deps): bump ipython

---

dataworkspace/dataworkspace/apps/core/utils.py
dataworkspace/dataworkspace/apps/your_files/forms.py
dataworkspace/dataworkspace/apps/your_files/urls.py
dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/templates/your_files/create-schema.html
dataworkspace/dataworkspace/templates/your_files/create-table-confirm.html
dataworkspace/dataworkspace/tests/your_files/test_views.py

https://trello.com/c/hc0mOvWf/2453-data-uploader-show-all-schemas
https://trello.com/c/hKUxm0FX/2454-data-uploader-create-new-schema

feature: show all schemas and create new schema when creating table in your files

---

dataworkspace/dataworkspace/apps/datasets/pipelines/views.py
dataworkspace/dataworkspace/templates/datasets/pipelines/logs.html

Success message shows a big green box with a raw sucess message when viewing derived pipeline logs

fixes problem with displaying error messages logs template

---

tools/jupyterlab-python/Dockerfile

fix: restore 'python' to JupyterLab

---

gitlab/Dockerfile

There are more recent versions, but this has to be done in stages

build(deps): bump GitLab

---

dataworkspace/dataworkspace/apps/your_files/views.py
dataworkspace/dataworkspace/tests/your_files/test_views.py

Passing db_role results in the DataFlow import pipeline swap_dataset_tables task attempts to grant a role with the same name as the schema to the user. This crashes for public schemas as this role doesn't exist and it is not needed for public schemas anyway.

fix: don't pass db_role when triggering dag public schema in your files

---

remote-desktop/Dockerfile
remote-desktop/lxqt/lxqt-config-appearance.conf
remote-desktop/lxqt/lxqt-powermanagement.conf
remote-desktop/lxqt/lxqt.conf
remote-desktop/lxqt/panel.conf
remote-desktop/lxqt/session.conf
remote-desktop/nginx.conf
remote-desktop/start.sh

feat: nicer remote desktop, and move to Debian Bullseye

---

dataworkspace/dataworkspace/templates/datasets/subscriptions/step_4_confirm.html
dataworkspace/dataworkspace/templates/datasets/subscriptions/unsubscribe_confirm.html

Content updated for ```step_4_confirm.html``` and ```unsubscribe_confirm.html```

fix: notification subscription content 

---

dataworkspace/dataworkspace/apps/your_files/views.py

fix: pass full date time when triggering restore table dag

---

dataworkspace/dataworkspace/apps/datasets/pipelines/forms.py
dataworkspace/dataworkspace/tests/datasets/test_pipelines.py

This adds validation to ensure that:
- query is valid sql
- query is a single statement only
- query is not a CREATE or DROP statement
- query doesn't contain duplicate column names

feature: validate pipeline sql when creating / editing derived pipelines

---

infra/ecs_main_superset.tf
infra/ecs_main_superset_container_definitions.json
superset/requirements.in
superset/requirements.txt
superset/superset_config.py

feat: add sentry to superset

---

dataworkspace/dataworkspace/static/search-v2.js

Added back a missing line of code.

fix: self variable was missing from LiveSearch object

---

dataworkspace/dataworkspace/static/js/chart-builder/package-lock.json
dataworkspace/dataworkspace/static/js/chart-builder/package.json

fix: chart builder - patch various vulnerabilities

---

dataworkspace/dataworkspace/static/js/chart-builder/package-lock.json
dataworkspace/dataworkspace/static/js/chart-builder/package.json

fix: upgrade glob-parent and node-fetch

---

dataworkspace/dataworkspace/apps/datasets/views.py
dataworkspace/dataworkspace/tests/datasets/test_views.py

https://trello.com/c/2WsiOKE5/2513-search-by-table-name

feature: support search by master dataset source table name

---

dataworkspace/dataworkspace/apps/datasets/utils.py

Add extra logging to `send_notifications` to help troubleshoot production issues

fix: extra logging to send_notifications
