uktrade/data-workspace-frontend

app/proxy.py
The main aim of these is to try to avoid the 401s that occasionally happen. Suspect multiple concurrent requests that create new sessions.
=> Proxy tweaks

Dockerfile, Dockerfile-with-jupyterlab, app/start.sh, prometheus/Dockerfile, prometheus/start.sh
There are multiple processes inside containers: before this PR if one exited then the container would carry on, and _not_ be replaced by Fargate. This PR uses GNU parallel to ensure that if one process exits, the rest are killed, the container itself will stop and be replaced by Fargate
=> (feat) More robust containers

app/app/shared.py, app/app/views_application.py, prometheus/fetch_targets.py
If an application is in SPAWNING state for more than two hours, kill it.
Applications are only set to RUNNING on a request from the browser, so if the browser is closed before it's RUNNING, then the application will be SPAWNING forever.
The metrics are not technically required for shutting down the SPAWNING servers, but gives a bit more visibility to what's happening in Grafana
----
Background design decisions:
- The distinction between SPAWNING and RUNNING is to show different things to the user if a connection can't be made to the application. If a connection can't be made to a  SPAWNING server, the HTML page shown to the user is a nice "Starting" page. If this happens to a RUNNING application, an error page is shown. This may need to be refined/changed in future
- Some applications …
=> (feat) Shutdown spawning servers

app/app/admin.py
This adds filtering for data sets admin list view by data grouping.
How to test:
- Go to http://localapps.com:8000/admin/app/dataset/
- Check filter by grouping visible, and working
https://trello.com/c/CbbxYKO8/124-admin-view-add-filter-for-data-sets-by-data-grouping
=> Adds list filter for data sets by data grouping

app/app/migrations/0035_sourcelink_link_type.py, app/app/migrations/0038_alter_link_type_and_fill_with_defaults.py
Fix migration failure when running on db with data.
=> Make link_type nullable - fill with default - make not null

registry/Dockerfile
Fixes
panic: unable to configure authorization (htpasswd): failed to open
htpasswd path open /etc/registry: permission denied
=> (fix) Registry launch error

registry/Dockerfile
The latest version appears to need authentication set, which doesn't
work in Fargate (at least, not without a bit of faff). However, we are
happy without any auth since the registry is only accessible from inside
the application VPC.
=> (fix) Fix registry for Fargate: no auth

infra/ecs_main_admin.tf
This means that
- Just after releasing a new task definition, that deletes the old one,
launching containers won't break
- It is more friendly to having a release process for the user-launched
containers, since only a new task definition needs to be released, and
not both a task definition and a release of the main application.
Note that each environment has its own family, so this doesn't increase
a risk of deploying non production containers into production.
=> (feat) Always launch latest task definition for user-launched containers

dataworkspace/dataworkspace/apps/applications/admin.py
This would make it easier to determine if orphan Fargate containers can
be stopped, since running ones will be able to be matched with
information shown in spawner_application_instance_id
=> (feat) More visibility on launched applications

dataworkspace/dataworkspace/apps/applications/admin.py
This is to help debugging, and suspect will be used in the initial
stages of users creating their own applications
=> (feat) Allow delete of application instances

dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/catalogue/views.py, dataworkspace/dataworkspace/templates/root.html
Stopping was only allowed when an application instance has a task_arn, which meant there was a bit of a delay from when spawning was initiated to when  the "Stop" button appeared in the UI. Now, an application can be stopped as soon as the spawning process begins, so things feel a bit more expected.
This is done as a step towards user-provided applications for visualisation, so stopping of spawning visualisation apps can be done as soon as they start. It is expected that there will probably be a bit of a repeated refinement process for these apps when developing, with multiple starts/stops of them, so making this process feel smooth and robust I suspect is important.
=> (feat) Allow immediate stop of spawning tools

.pre-commit-config.yaml, dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/catalogue/views.py, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/ecs_user_provided.tf, infra/ecs_user_provided_container_definitions.json, infra/main.tf, infra/rds_admin.tf
Provides a bare minimum of functionality to start applications that are defined at runtime.
- An admin/ops has to push a Docker container to the Docker repo with a certain tag in the form `<some-text>-<sso-user-id>`
- That user can then start the application by going to `<some-text>-<sso-user-id>.mydomain.com/`
- The application will close after 2 hours of inactivity, or until an an admin closes it
There is deliberately no administration screen at the moment to avoid building something that we don't know is the right thing/will be useful.
The launched application does not have access to the users folder in S3: until there is a need, treating it as a bit too dangerous, e.g. it would be a bit too easy for the user to delete all their files
However, the application does have database access …
=> (feat) User provided apps

s3sync/start.sh
We don't sync any _bigdata directory in either direction
- S3 -> Container to not use the 4GB space
- Container -> S3, since files that are not local would result in the
files deleted from S3.
At the moment _any_ folder called _bigdata will not be synced for
flexibility, although it is suspected that the root _bigdata will be the
one initially encouraged.
=> (feat) Don't sync _bigdata/ directories

s3sync/start.sh
The underscore is ordered after capital letters, so if we want the bigdata directory at the top, will need to have some manual code. Given we (might) want it at the top and will need manual code, then may as well have a more user-friendly name.
=> (feat) No underscore in bigdata directory

infra/s3_notebooks.tf
This does mean that an upload cannot take more than 7 days. I suspect
this is reasonable.
=> (feat) Automatically cleanup incomplete multipart uploads after 7 days

dataworkspace/dataworkspace/settings/prod.py
The datasets db is a Aurora PostgreSQL db.r5.large which supports up to
1000 connections. The value changed here is for a single application
instance, of which there are two currently.
Bumping since, unlike queries to the main admin db, queries to the
datasets dbs can be long lasting, e.g. to download tables with GBs of
data.
Not bumping crazy high to allow for scaling of the application
instances, and noting that connections to the datasets dbs are performed
from the tools
=> (feat) Bump datasets max connections

s3sync/Dockerfile
This is to better support nested directories
https://github.com/uktrade/mobius3/commit/d745454724df61dcd4b2b1b71294e1283582e6ba.
There is a plan to use git inside the notebooks, so this would be
important if the .git directory is to be synced.
=> (feat) Bump mobius3

dataworkspace/dataworkspace/apps/catalogue/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/templates/root.html
Technically the files page is still accessible if you know its path and are on the VPN, but in production the access to the bucket has been disabled, so you can't do anything if you get there
=> (feat) Put your files behind a feature flag

dataworkspace/dataworkspace/apps/applications/admin.py, dataworkspace/dataworkspace/templates/admin/application_instance_report_change_list.html
Order rows with runtime as those above those without.
I don't think there is a perfect way to deal with the lack of
information of runtime of existing applications, but without this, rows
that have NULL as their total runtime are always above those that have
some values. Suspect there will still need to be tweaks, but this change
gives a more reasonable order with the minimum of code.
=> (fix) Admin report order

jupyterlab/jupyter_notebook_config.py
It's enabled in rStudio, and equivalent behaviour can be done in Python
notebooks by prefixing commands with `!`, so may as well allow a more
regular terminal.
=> (feat) Enable terminal in JupyterLab

dataworkspace/dataworkspace/templates/spawning.html
Seeing what we can do in terms of faster/more consistent startup times. In the meantime...
=> (feat) Nicer slow container message

rstudio/Dockerfile, rstudio/rstudio-start.sh
The Rocker image does some user/permissions tinkering on startup, which
I suspect causes a race condition with the s3sync sidecar container that
means when it attempts to write to the home directory it doesn't have
permissions to do so, and exits.
We could have put some logic in there to retry. However, managing our
own image is probably good in the long run, for example to minimise the
image size.
=> (feat) Own RStudio image

infra/ecs_main_registry.tf
It's a bit of a stab in the dark, but seeing if increasing the cluster
size of the docker registries would avoid the issue where multiple
concurrent container starts at the same time are slow.
=> (feat) Bump registry cluster size

jupyterlab/Dockerfile
Some packages, e.g. tensorflow==2.0.0rc2, won't install with the
previous pip. Suspect it's related to the note about manylinux at
https://github.com/pypa/manylinux
> can be installed with pip 19.0 and later.
=> (feat) Bump installed pip

jupyterlab/Dockerfile
When installing tensorflow 2.0.0rc2 there are errors:
ERROR: thinc 6.10.3 has requirement wrapt<1.11.0,>=1.10.0, but you'll have wrapt 1.11.1 which is incompatible.
ERROR: spacy 2.0.12 has requirement regex==2017.4.5, but you'll have regex 2017.11.9 which is incompatible.
(Although I don't think they prevent tensorflow from installing, they do look scary)
=> (feat) Bump dependencies to not conflict with tensorflow==2.0.0rc2

Jenkinsfile
Adds a pipeline definition for running dev -> staging -> prod release
jobs with manual approval.
This ties together all recent releases to all data-workspace
environments within a single interface and would allow promoting
a specific release version between dev, staging and prod.
Approval steps take place within a "before agent" expression so that
they don't tie up an executor while waiting for user input. The inputs
are also surrounded by milestones so that previous releases are
automatically cancelled if a newer one proceeds to the next stage.
=> Add a Jenkins release promotion pipeline for data-workspace

Makefile
This is a bit hacky that the unit tests depend on the integration tests.
But quickest/easiest thing to get the tests running.
=> Run integration tests first so migrations are run

dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
For joint reference datasets Instead of displaying the linked field description this changes makes it so  the description of the field on the referenced table is displayed instead.
To test
- View any Joint reference dataset
- Check field definitions
- Check linked field descriptions
Before:
After:
=> Set field definition description of linked dataset field description

dataworkspace/dataworkspace/templates/datagroup.html
This change adds a description below the declaration of the Joint reference datasets.
Before:
After:
Note. PR contains 2 commits the first fixes the indents as the file had a mix of both tabs and spaces. 
Actual change in the second commit
=> Added joint reference datasets description

dataworkspace/dataworkspace/static/data-workspace-admin.css, dataworkspace/dataworkspace/templates/admin/reference_dataset_edit_record.html
This change just adds a go back button when editing a reference dataset record in the admin.
Before:
After:
To test:
- Go to the admin pages
- Select a Reference dataset 
- Click edit a record
- Click Go back and make sure you are taken back to the selected reference dataset edit page
=> Add go back button for edit reference dataset record

dataworkspace/dataworkspace/templates/files.html
Suspect that it's better for read_csv to do the `read`ing to avoid
duplicating the data in memory: important for things that are meant to
be large.
=> (feat) Shorter and more memory efficient suggested use of bigdata

dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/static/data-workspace-admin.js, dataworkspace/dataworkspace/tests/test_admin.py
This change makes reference dataset column names read only once created.
To test
- In admin
- Add a reference dataset
- Add a field specifying the column name
- Save
- Re-edit dataset
- Try and edit column name
- Add a new field 
- Save
=> Make column names readonly after initial creation

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/tests/test_views.py
Include materialized views in checks for whether a view exists in the database or not
=> Allow for the downloading of materialized views

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/test_admin.py, dataworkspace/dataworkspace/tests/test_models.py
This fix allows for source links to be deleted even if they don't have an associated file on s3.
We have had a couple of instances on production where a SourceLink was duplicated by an admin. When they deleted one of the duplicates the file was deleted from s3. When they then tried to download the remaining file they found that it did not exist (as it was deleted when the duplicate was removed). Deleting the remaining file would then fail because the file didn't exist in s3.
=> Allow SourceLink deletion when the associated file does not exist on s3

dataworkspace/dataworkspace/zendesk.py
Having a link ready to DIT people search in the ticket saves a bit
of time on a common task.
It's not clear if Ticket.description supports HTML (like .html_body
does), so I'm adding a plain text link that Zendesk should recognize
as URL for now.
=> Add a People Finder search link to Zendesk access request tickets

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/datasets/test_models.py, dataworkspace/dataworkspace/tests/factories.py
Using the recommended Django approach of duplicating a model instance this creates a coy of the dataset and any related tables, view, links etc.
There are a few packages available that add a general clone model mixin, but none appear to be widely used and since a general case is much more complex I'm going with a solution that hard-codes copied related objects for now.
https://docs.djangoproject.com/en/2.2/topics/db/queries/#copying-model-instances
This adds an action to the drop-down admin menu.
=> Add a dataset admin action to clone selected datasets

dataworkspace/dataworkspace/apps/datasets/models.py
Cloning and then immediately publishing a dataset raises an error
when trying to access either the clone or the original dataset page
since the unmodified slugs are conflicting.
We want a user to assign a new slug to a cloned dataset, so this is
clearing the slug on a cloned dataset object. This works from within
Django itself, but trying to edit or publish the dataset through the
admin interface would require the user to set a new slug.
Since this can create unpublished datasets with the same slug (which is
fine since unpublished datasets don't have a public page) we want to add
a constraint for published datasets to have unique slugs in the future.
=> Clear cloned dataset slug to avoid conflicts

dataworkspace/dataworkspace/apps/core/utils.py
Write the utf-8 BOM to csv outputs - this is the only way to make excel open a file with the correct encoding by default.
=> Gently nudge excel to open CSVs in utf8

CHANGELOG.md, dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/static/data-workspace-admin.css
Set overflow to allow scrolling of long dataset names on the user datasets form
=> Scroll on dataset selector overflow

dataworkspace/dataworkspace/apps/catalogue/views.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/tests/catalogue/test_views.py
Adds a preview of the dataset fields to help users make an informed
decision about requesting access.
The field list is derived from the dataset tables, view or custom query
and so should match the columns in a download CSV.
For master datasets containing one or multiple tables the table columns
are prefixed with the table name.
The fields are currently only visible to admin users and the section is
skipped if it failed to retrieve columns from the datasets DB.
Will be completed once we've validated the approach with admin users.
=> Display list of data fields on the dataset page

dataworkspace/dataworkspace/apps/datasets/models.py
Quick fix so admins can see source table ids (and use them when making api calls)
=> Add id to source table name shown on admin inline form

CHANGELOG.md, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html
After testing data fields queries with existing datasets we can
enable it for all users.
Since the list of fields can be quite long and we're not sure all
users are interested in it we're displaying it as a details component
that can be expanded.
=> Display data fields for all users in a details component

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
pgadmin creates a table and then immediately issues and ALTER TABLE
query setting the owner of the table to the current temporary database
user, rather that the real-world-user's permanent role. Which means the
sequence of events was:
From pgadmin:
CREATE TABLE
From the existing trigger:
ALTER TABLE setting the owner of the table to the permanent role
From pgadmin:
ALTER TABLE resetting the owner back to the temporary user
This commit then ensures that after any ALTER TABLE, and specifically
the ones from pgadmin the role is always set to the correct permanent role.
Potentially there are small race conditions since I don't think these
queries are atomic, but the only issue would be if a user tried to
access a table between these queries they might see an error.
Potentially also if the …
=> (fix) Owner of tables created in pgadmin

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/admin.py
Add source column to admin listing and allow for filtering by source tags
=> Allow for filtering by source tag on dataset admin listing pages

CHANGELOG.md, rstudio/Dockerfile
Adding the R packages data.table to the R Studio image
The mirror isn't regularly updated at the moment, hence the addition of -o Acquire::Check-Valid-Until=false
=> (feat) Include R package data.table

dataworkspace/proxy.py
Fix duplicate query string parameters being received by the admin application. Usually, this doesn't make a difference. However, on endpoint users `getlist`, which is sensitive to duplicate parameters, and its behaviour breaks
=> (fix) Duplicate query string params being received

CHANGELOG.md, s3sync/Dockerfile
The recent changes in mobius3, specifically https://github.com/uktrade/mobius3/commit/872deeeb879d8ae8696ba2fda0e64ed96563365f and https://github.com/uktrade/mobius3/commit/c0d576864f06cdb8989217d576e9a43367790b6c better support download and delete of nested directories. This is expected to be helpful / borderline necessary, when .git directories are created and synced to each user's area in S3.
~*[ ] Has the README been updated (if needed)?~
=> (feat) Bump mobius3, for changes for nested directories, e.g. for git

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Datasets that aren't published and deleted reference datasets shouldn't be displayed in the search results.
Displays first, last and current page number surrounded by 2 next/ previous pages.
=> Add pagination links to search results

CHANGELOG.md, infra/security_groups.tf
The connections from Redis and RDS to Cloudwatch are apparently not
controllable through our security groups, so no need for these.
~* [ ] Have tests been added to cover any changes? ~
=> (feat) Remove unused security group rules

CHANGELOG.md, dataworkspace/dataworkspace/apps/accounts/admin.py
Make authorised datasets fields optional to allow for creation of users using the standard form
=> Fix issue where admins were unable to create new users

CHANGELOG.md, s3sync/start.sh
For the upcoming connection via SSH from tools to gitlab, this will be
via a public/private key pair. It would be expected that you wouldn't
have to regenerate this every time a tool starts.
Note that for now, mobius3 does not store the mode of files, so there is
likely work needed there: otherwise SSH will complain about the private
key being too open.
=> (feat) Sync .ssh directory from tools

CHANGELOG.md, s3sync/Dockerfile, s3sync/start.sh
It looks like no IN_CLOSE_WRITE event is received for .pack or .idx
files. I suspect they are created via
- a separate temporary file, with name like tmp_pack_hBV4Alz, being
created, modified and, closed;
- a _hard_ link is created to this file, with the final .pack name;
- the original tmp_pack_hBV4Alz name is deleted.
So after a repository is cloned, because there is no IN_CLOSE_WRITE
event, the upload of these files is never queued, and after a few
minutes, the sync notices these files are not in the bucket, and thinks
that these files must have been removed, and then decides to delete them
locally.
This change is somewhat hacky/brittle. If git changes the location of
these files for example, this fix would break.
~* [ ] Has the …
=> (feat) Upload pack files on create

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/static/search.js, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/about.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/urls.py
New header layout with Home / Tools / About links, hidden behind the datasets-search feature flag.
Tools link in header and footer is only visible to users that have tools access while the page itself is being redesigned.
Page is public, but is only linked from the header when the search feature flag is active.
If a search page has an alternative URL (e.g. as the home page), we still want any search requests go to the canonical /datatsets/ URL, so live search JS needs to use the form action URL instead of the current page URL as a base path.
=> New header and about page

requirements.txt
To avoid the error
TypeError("unhashable type: 'Redis'")
~* [ ] Has the [CHANGELOG](https://github.com/uktrade/data-workspace/blob/master/CHANGELOG.md) been updated?~
=> (fix) Pin Redis to previous working version

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
Up the gevent queue put timeout to 1 minute to try to curb queue Full errors causing failed downloads.
=> Update download queue timeout to 60 seconds

requirements.txt
I don't think we're using StringAgg directly, but it's possible that
some of the dependencies are.
=> Update Django to address CVE-2020-7471

CHANGELOG.md, infra/main.tf
We could have some sort of per-visualisation configuration, but for now,
probably not worth it.
Bumping to the same amount of memory/CPU as the tools, which is 1 CPU,
and the maximum amount of memory for that CPU, 8GB.
I suspect for a lot of visualisations, such as one that has just been
setup for testing, their data will just be loaded into memory. Not
bumping memory higher for now to have a bit of visibilty on the sorts of
amounts that are needed.
=> (feat) Give more memory and CPU to visualisations

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
Fixed trigger when a user creates tables in their own schema using CREATE TABLE AS, so they are accessible in other tools
=> (fix) Permissions on tables created via CREATE TABLE AS

CHANGELOG.md, rstudio/Dockerfile
Added retries when fetching dependencies when building the RStudio image. The S3 mirror is surprisingly flaky.
=> (build) Retry failed apt-get downloads. S3 seems to fail quite often

CHANGELOG.md, jupyterlab-python/Dockerfile, jupyterlab-r/Dockerfile
Change which debian repository is used in JupyterLab R and Python, to our mirror, so packages can be installed from inside them
=> (feat) JupyterLab uses our debian mirror, so packages can be installed

dataworkspace/proxy.py
Since we don't have a DEBUG flag for the app at the moment the least
disruptive way to stop CSP protocol upgrades in local dev is to check
for the development root_domain.
=> Exclude local dev domain from CSP HTTP->HTTPS upgrade

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
Change streaming download queue timeout to 2 minutes
=> Double queue timeout to 2 minutes for streaming downloads

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py
Allow visualisations, without s3sync, to have environment variables for database credentials
=> (fix) Allow visualisations, without s3sync, to have environment variables for database credentials

CHANGELOG.md, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/spawning.html
We find that users have low levels of confidence that their tool is
loading properly when everything on the page is static. By adding a
dynamic spinner we hope to increase confidence that 'work is being
done'.
This solution is lifted from conversation on the GOV.UK Design System
repo: https://github.com/alphagov/govuk-design-system-backlog/issues/28
Ticket: https://trello.com/c/ODpRBsdj/828
It looks a bit jarring in the gif, but it moves smoothly in reality...
=> Add spinner to 'tool loading' page

CHANGELOG.md, dataworkspace/proxy.py
Changed the CSP header to explicitly allow Websocket requests by named domain: required for Safari since 'self' does not seem to work
=> (fix) Fix WebSockets in Safari

CHANGELOG.md, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html
Do not show created date on data sources as users assume it is the date the data was updated when it is actually the date the source was created in django.
=> Remove source created date from data listings

CHANGELOG.md, README.md
Fixed link/port in readme when developing locally to match the default dev configuration
=> (docs) Minor fix to port in README

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/factories.py, dataworkspace/dataworkspace/tests/test_admin.py
This allows viewing / modifying users that have access to a dataset
from the dataset admin page, similar to how a list of dataset
permissions for each user can be edited on the user page.
If the permissions are modified, an admin log event is written. The
event is associated with the user object, since that's how we record
permission changes currently.
This only applies to master datasets and data cuts, since reference
data currently doesn't require access requests.
=> Add user access editing to dataset admin page

CHANGELOG.md, dataworkspace/proxy.py, infra/main.tf, infra/security_groups.tf
Allow the port of an application to be overridden, and open 9000. This means that, for example, in JupyterLab, a user can start their own webserver on port 9000 and develop on it, opening up
jupyterlab-[sso-id]--9000.domain.com
to view their in-progress application.
=> (feat) Allow the port of an application to be overridden

CHANGELOG.md, infra/ecs_main_admin_container_definitions.json
Separate JupyterLab config directories
Suspect will be syncing them via the home folder, so this should avoid
strange conflicts due to different JupyterLabs running via the same
directory.
=> (feat) Separate JupyterLab config directories

CHANGELOG.md, infra/ecs_main_admin_container_definitions.json
A follow-up to c0f6074794c309d0a7e4b4c37891ff872373aca4, separating more
JupyterLab directories between the R and Python instances, to avoid
issues when they are synced to and from S3.
=> (feat) Separate JupyterLab R and Python directories

dataworkspace/dataworkspace/templates/tools.html
It was/is a slight hack anyway, but at least now it's a hack that gives
slightly neater output.
New version:
Old version:
~*[ ] Has the README been updated (if needed)?~
=> (feat) Tweak launch button widths for better alignment

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisations.html
- The visualisations page shows a message asking the user to visit GitLab if they haven't already.
- The visualisations page asks the user to contact support if they have no access to any projects.
- The visualisations page shows all internal visualisations if the user hasn't yet visited GitLab, or all the visualisations visible projects if they have.
=> (feat) Visualisations pages messages and tweaking of what projects to show

CHANGELOG.md, jupyterlab-python/Dockerfile, jupyterlab-r/Dockerfile
Moving the ipython config/history directory out from the home directory, to avoid sqllite errors like "attempt to write a readonly database"
Also bumping openssh-client: the build was complaining about attempting
to downgrade.
=> (fix) IPython sqllite errors

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisations.html
Fix GitLab link in template and remove duplicated word
=> (fix) GitLab link in template and remove duplicated word

CHANGELOG.md, dataworkspace/dataworkspace/context_processors.py
Remove the permissions check for showing the Visualisations tab to try to reduce the chance of running out database connections / getting to 100% CPU
=> (fix) Avoid database query during page render to try to avoid recent issues of 100% CPU + running out of DB connections

dataworkspace/dataworkspace/apps/applications/views.py
The main Django CSP is blocking the script which monitors whether or not
the application has spawned and redirects the user to the tool. By
exempting this view we can give the proxy full control over the CSP
header returned.
=> Defer to proxy for CSP on spawning page

CHANGELOG.md, dataworkspace/dataworkspace/static/data-workspace.css
Changing the position of the Menu button in the menu on mobile from
to
(I'm going to be doing a series of front end changes, and this keeps catching my eye...)
=> (feat) Tweak location of Menu button

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisations.html
This is more of a check on the API, as well as seeing how many GitLab
API requests we can do in production per page load before it gets too
slow.
=> (feat) Fetch and display if the user is a developer on each project

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/tests/test_security.py
We use CKEditor to render rich text fields on the add/change admin pages
for reference datasets. Our latest CSP update was too strict, leading to
the text field no longer working as an inline script injected by CK
Editor is no longer executed by the browser.
This script is dynamically built by the ckeditor javascript and it
doesn't appear possible to update the CSP headers with a hash of the
script contents or pass in our CSP nonce, so we will have to settle with
downgrading the CSP security on this page for the time being.
=> Loosen up CSP on reference dataset admin page

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/admin.py, dataworkspace/dataworkspace/apps/applications/utils.py
'name' is a strange field whose purpose can be covered by one of:
id: unique and unchanging identifier for the application
nice_name: Human friendly name
(In one case, the name field wasn't being used, so removed it from the dictionary it was in)
In a later PR, will likely remove the name field
Doing this now, because the upcoming visualisations deployment code will
make the app model more complex, so simplyifying things before that.
=> (refactor) Reduce usage of application 'name'

dataworkspace/dataworkspace/apps/datasets/admin.py
Django complains if DataSetUserPermission objects are created before
the dataset has been persisted, which only happens when you try to
create a dataset and assign some users to it in the same edit.
This doesn't happen when editing permissions from the users page
since we don't create users in the admin UI.
=> Allow creating a dataset and assigning permissions at the same time

dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/test_admin.py, dataworkspace/dataworkspace/tests/test_security.py
Make sure that if SME users change SQL queries after they've been reviewed by a superuser, they need to be reviewed again.
=> Un-review SQL queries if changed after review

CHANGELOG.md, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/partials/contact.html
Moves the contact section to the bottom of the dataset detail view. Also adds proper GOV.UK styling to the email address link.
~~* [ ] Have tests been added to cover any changes?~~
~~* [ ] Has the README been updated (if needed)?~~
=> Move contact section to bottom of page

CHANGELOG.md, dataworkspace/dataworkspace/settings/base.py
This adds the ability to add clickable links to reference dataset descriptions
- Updating the description
- Add link menu
- Frontend
=> Clickable links in reference dataset descriptions

CHANGELOG.md, dataworkspace/proxy.py
Right now my-app-name--9000.domain.com routes to port 9000 on an
applications. I suspect for previewing applications will want something
like my-app-name--commitid--9000, so we need to use rpartition rather
than partition to find the port number.
=> (feat) Support double hyphens in hosts

CHANGELOG.md, dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py
For visualisations, there are two slightly unnecessary generalisations
to convert the host to a docker tag:
- Application.host_pattern that converted the host into some arbitrary
dictionary
- Application.spawner_options.CONTAINER_TAG that then converted from
this dictionary to a docker tag
However for visualisations the only transformation that is ever made was to
convert the exact value of public_host to the docker tag. There isn't a
plan to change this, and even if there were, I suspect will want to do
this from code for all visualisations, so it will be awkward to do this
for all visualisations if it involved their config.
=> (refactor) Un-generalise public_host -> docker tag for visualisations

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/management/commands/ensure_application_template_models.py
... since otherwise, routing to tools will break
Suspect will be moving away from tools auto-populated by environment
variables, but for now, they are, so should try to make sure they don't
break.
=> (feat) Ensure application doesn't start if no host_exact for tools

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Adds some warning text under the "Data links" header when the data link is hosted externally (i.e. not on Data Workspace).
=> Show "external link" warning

CHANGELOG.md, infra/ecs_main_gitlab.tf, infra/ecs_notebooks_notebook.tf, infra/main.tf, infra/security_groups.tf
The GitLab runner runs in the same VPC and subnets as the notebooks to avoid it having any direct internet access: they will run essentially untrusted code: the Dockerfiles of visualisations.
=> (feat) GitLab runner to run visualisation docker builds

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py
When determining the spawner status, take GitLab pipeline status and time into account, otherwise the spawner is marked as stopped because it takes too long for the task to be created
*~ [ ] Have tests been added to cover any changes?~
=> (feat) Take GitLab pipeline into account when checking spawner status

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
There was a logic error in the "You have access" filter, which meant
that if _anyone_ had been granted access to the dataset then it would
appear. It was also resulting in each dataset appearing multiple times
in the results. This should fix these problems.
=> Make sure they really do have access

dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
I tried to fix this before in
https://github.com/uktrade/data-workspace/pull/530 but hadn't understood
the problem properly.
When a user filters for access as well as use (but not reference
datasets), then we get multiple instances of each dataset returned if
that dataset doesn't require authorisation but has multiple people
specifically authorised to use it.
This fix adds proper querying on public datasets to ensure that only one
instance is returned, and also changes the context passed into templates
to a list of dicts, rather than a list of dataset objects, which is
consistent with what's passed in when "reference" datasets are filtered
for.
=> Actually de-duplicate datasets properly

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/forms.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/core/support.html, dataworkspace/dataworkspace/templates/partials/form_field.html, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/urls.py
Add a link to 'support and feedback' to the heaader/footer, and update
the content on the page to help users understand what the form is for.
Ticket: https://trello.com/c/HYMb3J4Z/908
I know that putting HTML in the Python form is not great, but given this is the sole ask for this kind of formatted text I don't think it's worth going down other routes right now. Open to being challenged on this though.
=> Update support and feedback links/content

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py
Data Workspace now has GITLAB_URL set as a private domain to allow it to resolve to a private domain, i.e. gitlab.jupyterhub. This won't work from the public internet.
=> (fix) Link to GitLab on visualisations page

dataworkspace/dataworkspace/apps/core/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/zendesk.py
If a support form is filled following a search results "data request" link the resulting Zendesk ticket is tagged with "data_request".
The tag query parameter is checked against a list of allowed tags.
=> Search results guidance

CHANGELOG.md, mirrors-sync/Dockerfile, mirrors-sync/mirrors-sync.py
It was skipping _all_ files that already existed, so the index files weren't being updated.
=> (fix) Debian mirror (and bump http library)

CHANGELOG.md, infra/ecs_main_gitlab.tf, infra/main.tf, infra/security_groups.tf, infra/vpc.tf
Also opens up port 80 between the admin application and GitLab for the
API: so the communication doesn't go via the NAT/public internet, and so
we don't have to open up the GitLab load balancer to the address of the
NAT instance.
=> (feat) GitLab behind VPN

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/gitlab.py, dataworkspace/dataworkspace/apps/applications/urls_visualisations.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/visualisation_branch.html, dataworkspace/dataworkspace/templates/visualisations.html
The page to navigate visualisations: (When to show what links, and what to do if they can't be shown, is still being decided. Also would like something more descriptive than "Manage", but can't seem to think of anything that isn't really clunky)
The manage visualisation page itself:
The side `nav` at the moment is in the `main` element of the page. To change this, it will need a more hefty change to the base template, so leaving that until later.
The commit ID does have quite a bit of prominence. This is a bit... technical/meaningless, and so it change later, but for now, it's in 3 places (in addition to GitLab)
- In the visualisation management page
- The starting page when starting a preview visualisations by ID
- The URL of the preview visualisation (in the host name)
Not quite sure …
=> (feat) Page per visualisation

CHANGELOG.md, dataworkspace/dataworkspace/templates/_base.html
The base href is set to `/` on the root domain, partially to make links on the spawning and error pages, which are on other domains, work as expected. However, this means that links with just a #fragment will always go to the #fragment on the root path of the root domain, unless prefixed by the path of the current page.
=> (fix) 'Skip to main content' link

CHANGELOG.md, dataworkspace/dataworkspace/settings/base.py
This change updates the preview panel on ref datasets to show 1000 rows. 
This is because the feedback we have had from users is that they don't understand the panel is a preview and expect to see the full dataset. Setting the value to 1000 will be greater than any current ref dataset so will in turn end up showing the full dataset.
=> Update the number of rows shown in  preview panel for a ref dataset

CHANGELOG.md, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/_main.html, dataworkspace/dataworkspace/templates/about.html, dataworkspace/dataworkspace/templates/appstream.html, dataworkspace/dataworkspace/templates/appstream_admin.html, dataworkspace/dataworkspace/templates/core/support.html, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/eligibility_criteria.html, dataworkspace/dataworkspace/templates/eligibility_criteria_not_met.html, dataworkspace/dataworkspace/templates/error_403.html, dataworkspace/dataworkspace/templates/error_404.html, dataworkspace/dataworkspace/templates/error_500.html, dataworkspace/dataworkspace/templates/files.html, dataworkspace/dataworkspace/templates/partials/messages.html, dataworkspace/dataworkspace/templates/request_access.html, dataworkspace/dataworkspace/templates/request_access_success.html, dataworkspace/dataworkspace/templates/spawning.html, dataworkspace/dataworkspace/templates/tools.html, dataworkspace/dataworkspace/templates/visualisation_branch.html, dataworkspace/dataworkspace/templates/visualisations.html
Refactor to add intermediate template in chain to support the visualisations side navigation not being inside the `main` html element
=> (refactor) Intermediate template

dataworkspace/dataworkspace/urls.py, docker-compose-dev.yml
We were using Django test server when running Data Workspace locally,
but it has some differences in how it behaves compared to production,
for example in the way it handles interrupted chunked responses for
data downloads (gunicorn correctly fails the response while Django
doesn't).
To save some time debugging these in the future this switches dev
server to use gunicorn with auto-reload. This should behave the
same way django test server does when python/html or asset files
are changed on disk.
=> Use gunicorn for local dev server

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
They each still have to be individually enabled for Google Data Studio access
=> (feat) Allow Data Studio access to unpublished data sets

CHANGELOG.md, dataworkspace/proxy.py, jupyterlab-python/Dockerfile, jupyterlab-python/jupyterlab_database_access/package.json, jupyterlab-python/jupyterlab_database_access/plugin.js, jupyterlab-python/jupyterlab_database_access/styles.css, jupyterlab-r/Dockerfile, jupyterlab-r/jupyterlab_database_access/package.json, jupyterlab-r/jupyterlab_database_access/plugin.js, jupyterlab-r/jupyterlab_database_access/styles.css
Upgrade to JupyterLab 2.0.0
Notes:
* We update git/git-man/sudo apt packages as the old ones are no longer available, looks like removed due to vulnerabilities.
* Remove `-s` option from `conda clean` as it's been deprecated. Not replaced it with anything as it's there to clean up source files from the image build, but the new process is `conda build --clean-sources`, which isn't available by default, i.e. requires installing a new package. Doesn't feel necessary to do.
* We allow `blob:` in img-src for CSP as it seems matplotlib now manages these as blobs rather than as `data:`.
* Add custom styling to the database access button for the JupyterLab plugin. As part of the upgrade, icons were reworked and it became transparent due to jupyterlab styling. This style simply overrides it and …
=> Upgdrade JupyterLab (Python, R) to v2.0.0

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_models.py
Updating an existing record in a ReferenceDataset does not change the last updated column on the data links table.
This is because when using QuerySet.update(), DateTime fields with auto_now are not updated to the current time and therefore this field needs to be passed explicitly as a keyword argument. See https://code.djangoproject.com/ticket/26239
=> Explicitly pass updated_date to ReferenceDataset records.update()

CHANGELOG.md, test/test_application.py
Done by converting the fixed-length sleeps to polling the healthcheck endpoint until it returns a success response.
There are still some sleeps waiting for tools/visualisations to load, but leaving them until later.
=> (tests) Make integration tests faster and a touch less flakey

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py
Some of them compile lots of R packages. Suspect will still need some nicer way to abort builds, but leaving that until later.
=> (feat) Bump timeout for visualisation build

CHANGELOG.md, dataworkspace/dataworkspace/templates/_visualisation.html
=> (feat) Handle long branch names a bit better, style-wise

dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/urls.py, requirements-dev.txt
The debug toolbar adds some nice profiling info (e.g. sql queries for
the page, load time, headers/settings, etc) which can be handy in a dev
environment.
We only load the middleware if we're in debug mode and the library is
available, and we only add the library to the dev requirements, so it
should never be available in a production (even dev/staging)
environment.
=> Instrument Django-Debug-Toolbar, if installed

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/tools-unauthorised.html, dataworkspace/dataworkspace/tests/core/test_views.py
We want to allow non-tool users to understand what tools are for, so
that they can self-assess whether it's something that might be useful
for them and also have a clear path to requesting access.
Ticket: https://trello.com/b/NHmVWCYp/data-workspace
=> Add tools page for non-tool-authorised users

CHANGELOG.md, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html
Bo pointed out recently that the "no access" warning has been dropped
down into the wrong section. This patch moves it back up. It also
addresses a further design point that the link should be styled like an
action button.
=> Move "no access" warning into first section

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/visualisation_branch.html, dataworkspace/dataworkspace/templates/visualisations.html
I've already found it a bit annoying having to flit back and forth. It does look a bit bland/empty right now, but more will go in it later.
=> (feat) Move link to production visualisation to master branch page

CHANGELOG.md, Dockerfile, dataworkspace/dataworkspace/settings/base.py, requirements.txt
Reverts uktrade/data-workspace#582
Looks like APM is no longer available in dev and that the changes by webops have been rolled back out.
They intend to change the port APM is available on in the next few days, so I'll roll this out until that happens and then put this back up for the last time with updated config.
=> Take APM out again

dataworkspace/dataworkspace/apps/accounts/utils.py
Our main wrapper for almost all views, `_login_required`, wasn't
wrapping the decorated functions in a way that allowed APM to properly
understand what view was being called - so almost all page hits were
being logged as `_login_required`. By setting this as a wrapper, it will
properly log which page has been viewed.
=> Fix method attribution for APM

CHANGELOG.md, dataworkspace/dataworkspace/templates/tools-unauthorised.html
We no longer require users to have SC before we are able to grant tools
access.
Ticket: https://trello.com/c/tN8BtoaD/964
=> Remove reference to SC clearance

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/visualisation_branch.html, infra/ecr.tf, infra/ecs_main_admin.tf
Initial version of button. Slightly awkward to have to preview first, but better than me releasing it every time
=> (feat) Release to production button

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py
They weren't able to be dropped since the users privileges on the
schemas were not removed.
This should reduce some of the exceptions that make it to Sentry, since
each time a user couldn't be dropped, an exception was sent to Sentry.
=> (fix) Allow removal of users with privileges on schemas without tables

dataworkspace/dataworkspace/settings/base.py
Elastic APM has some defaults that still try to send metrics even if `ELASTIC_APM` is not configured, leading to errors in `Demo` and `CatalogueDev` envs where they're trying to send to `localhost:8200`.
We'll probably instrument those environments later, but this feels OK to put in for now.
=> Only install elasticapm if config set

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisation_users_with_access.html
Not sure what would be good text for the success message. All options seem clunky to me
=> (feat) The ability to remove access from a visualisation

CHANGELOG.md, dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/settings/base.py, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json
This would also allow the removal of common options in the various tools environment variables, but leaving that until later.
=> (feat) Avoid copy and paste of common spawner options for visualisations

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/models.py, dataworkspace/dataworkspace/apps/datasets/constants.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/templates/partials/unpublished_banner.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
Adds the catalogue detail page for visualisations.
Ticket: https://trello.com/c/GX0ULwT1/945
=> Add visualisation catalogue detail page

CHANGELOG.md, rstudio/rstudio-start.sh
Shiny apps will access the database using the credentials in the
environment, so making it easier to develop them from RStudio
=> (feat) Make database credentials available in R Studio as environment variables

CHANGELOG.md, infra/ecs_main_admin_container_definitions.json, rstudio/Dockerfile
It's a bit of a gotcha that it doesn't already: firing up the docker image using its default CMD locally wouldn't have run the same thing as in production
=> (refactor) Use RStudio CMD from Dockerfile

CHANGELOG.md, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/partials/messages.html
I realised it was a bit odd when a field in the form is autofocused: the alert is skipped and page scrolls down past it.
So now (all in common with the GDS error alert):
- It has `role="alert"`
- It autofocuses on page start (which means later elements in the page are _not_ autofocused)
- It's _not_ in the keyboard tab order of the page,  i.e. it is only focused on page load, or click from what I can tell. This is a bit odd to me, since it doesn't seem that getting the focus back on the element is possible with just keyboard navigation, but it is consistent with the GDS error alert.
- It has a yellow outline when focused [the yellow==focused is in common with GDS, although depending on element, sometimes the yellow is an outline, and sometimes a background]
There are lots of options + …
=> (feat) Success alert more similar to error alert

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py
This removes the requirement for an admin to move projects into the
visualisations group, since users can add topics to their own projects.
I realise that the endpoint is paginated, and the query does not follow
the pagination. However, it already wasn't, so this change doesn't go
backwards in this respect. In fact, mitigating the issue for now by
bumping the page size from the default 20 to 100. Following the
pagination is left until later.
It does seem that there isn't a way to query for projects with a
specific topic: this has to be done as a manual filter of the results.
However, since we can use min_access_level for the current user, I think
this is still acceptable.
=> (feat) Use visualisation topic rather than a group to search visualisations

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py
Recent changes seem to have fixed "tuple concurrently updated" when GRANTing on the database, but the error now occurs later in the granting process.
At the moment, these permissions are created synchronously on starting an application, so the locking would slow down this request. However, treating that as better than erroring. Ideally they would be created as part of the subsequent background task that runs when starting an application, but leaving that until later.
=> (feat) More grant locking

dataworkspace/proxy.py
Use the full path and query string when authenticating hawk requests.
Clients using pagination on the api currently have to remove the query string from the url when creating their hawk sender header. This is because data workspace was using the path only and not the path and query string as is required. In practice this meant that you would have to create a hawk token with one url (without query string) and then make a request to a different url (full url with query string) which is not ideal.
Effectively we've gone from 
```
sender = mohawk.Sender(
credentials=credentials,
url=url.split('?')[0],
)
response = requests.get(url, headers={'Authorization': sender.request_header})
```
to
```
sender = mohawk.Sender(
credentials=credentials,
url=url,
)
response = requests.get(url, …
```
=> Use full request path when authenticating hawk requests

CHANGELOG.md, dataworkspace/dataworkspace/templates/datasets/master_dataset.html
A lot of the schema names have dots in them, so if used in SQL, they
need to be wrapped in double quotes. I've not seen table names with dots in them, but adding quotes around the table name for consistency/just in case.
The identifier will also (probably) be in the Datasets page in the Visualisation UI, with the double quotes, so doing this for consistency with that page.
=> (feat) Wrap dataset identifier schema and table in double quotes

dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/apps/applications/urls_visualisations.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/partials/govuk_single_checkbox_field.html, dataworkspace/dataworkspace/templates/visualisation_approvals.html, dataworkspace/dataworkspace/tests/applications/test_views.py
Add a page where visualisation users/creators can approve other people's
visualisations (or potentially their own, hence we require two
approvals).
Ticket: https://trello.com/c/zzdmPLu7/979
=> Add approvals page for visualisations

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/gitlab.py, dataworkspace/dataworkspace/tests/applications/test_gitlab.py, requirements-dev.txt
We have a permission that manages user access to unpublished catalogue
items. This patch automatically gives the permission to visualisation
creators as they browse the visualisation UI,by piggy-backing on
`gitlab_has_developer_access`, which is used to check whether a user has
developer+ access to a given visualisation.
The django-side permissions is global, so they are granted the ability
to see *all* unpublished visualisations. This is fine - and possibly
even preferrable - so that creators can see/crib from other people's
work.
Ticket: https://trello.com/c/0ZvQ3jK4/1012
=> Automatically grant vis creators the management perm

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/templatetags/core_tags.py, dataworkspace/dataworkspace/templates/visualisation_datasets.html, dataworkspace/dataworkspace/tests/applications/test_gitlab.py, test/test_application.py
From
to
Ideally this would be done in CSS, but there doesn't seem to be a CSS-only way of telling the browser that underscores, that are often part of schema and table names, are not parts of words.
=> (feat) Slightly nicer presentation of long schema and table names

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py, dataworkspace/dataworkspace/apps/applications/utils.py
It's a bit of a stab in the dark, but adding a few ms to celery tasks should be fairly safe from a UX point of view.
=> (feat) Close connections after celery tasks as attempt to address db connection usage

CHANGELOG.md, dataworkspace/dataworkspace/apps/api_v1/views.py
If two parallel requests are received to start an application, the second of these would error. Instead, we silently "succeed" by returning the response as though the user successfully started to start the application.
This is likely to be more likely as visualisations get more popular, since multiple people can start the same visualisation at the same time.
=> (feat) Avoid surfacing IntegrityError when starting an application

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/templates/partials/bullet_list_split_array_widget.html, dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html
Let data vis creators edit the eligibility criteria for their
visualisation. This is whole-heartedly an MVP design.
Ticket: https://trello.com/c/BehUXL2e/1011
=> Add eligibility criteria to data vis UI

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/admin.py, dataworkspace/dataworkspace/apps/applications/models.py, dataworkspace/dataworkspace/apps/applications/urls_visualisations.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/visualisation_publish.html, test/test_application.py
Adds a page to the Data Vis UI that allows a data vis creator to
publish/unpublish both the production visualisation URL, and the
catalogue item. These respectively control whether the visualisation
can accessed at its prod URL, and whether other users can discover the
visualisation exists at all in the Data Workspace catalogue.
Ticket: https://trello.com/c/FJLZZZAP/980
=> Add publishing page to data vis UI

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py
The try/except and transaction were the wrong way round, i.e. if two people added the same user at the exact same time, at the end of the transaction one of them would raise IntegrityError and result in a 500.
=> (feat) Slightly better handling of concurrent adding of visualisation access

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/visualisation_datasets.html, test/dataset_server.py, test/test_application.py
I did attempt to mirror the Users pages "Give access" and "With access", but it felt really awkward/clunky, as well as being seemingly impossible to come up with some reasonable names for those pages.
Also removed the text that is displayed when there are no datasets: there are always some datasets in the list in production (and also couldn't think of anything that seemed both accurate and concise in this this were to happen).
=> (feat) Edit visualisation datasets access

dataworkspace/dataworkspace/templates/visualisation_publish.html
The publish vis/catalogue buttons in the data vis UI were styled as
disabled, but not actually disabled, when their conditions weren't met.
This fixes that.
=> Actually disable button

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/api_v1/test_api.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
Adds the filter name label based on the dataset type to each result.
We add the type to the reference datasets by making Django ORM generate a `SELECT ..., 0 as "type"` query.
Django orders model fields before any additional fields like annotations in generated SQL statement which means doing a UNION between a model field in one query and an extra field in another results in different columns getting connected into a single result one (which sometimes leads to a type error and sometimes succeeds with values ending up in the wrong place). To avoid this, we alias model field `type` with `.annotate` in the datasets query, making sure it's added to the end of SELECT field list.
Visualisation follow the same rules as datasets:
* they are filtered by text query
* Access filter only displays …
=> Add visualisations to catalogue search results

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/forms.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/_visualisation.html, dataworkspace/dataworkspace/templates/visualisation_catalogue_item.html, dataworkspace/dataworkspace/tests/applications/test_views.py
Adds a checkbox to the "catalogue item" page in the data vis UI for data vis creators to set whether the vis is available to all logged-in users, or just to a set of explicitly-authorised people.
If it's open for all logged-in users, creators don't need to provide eligibility criteria or manage users with access - so we hide both those sections.
=> Auth checkbox on data vis UI

CHANGELOG.md, theia/Dockerfile
Running `sudo apt-get update` from Theia showed errors since it was trying to contact deb.nodesource.com.
=> (feat) Nicer apt-get update from Theia

CHANGELOG.md, dataworkspace/proxy.py
Use correct endpoint when checking for hawk auth in the proxy.
This was fixed a while ago but was inadvertently reverted (by me)
=> Fix bug where proxy was checking for incorrect accounts url

CHANGELOG.md, infra/ecs_main_admin.tf, infra/ecs_main_superset_multiuser.tf, infra/main.tf, infra/route_53.tf, infra/security_groups.tf
Unfortunately, an Application Load Balancer, even an internal Application Load Balancer like the one in front of Superset, with an HTTP listener apparently overrides x-forwarded-proto with `http`, which makes Superset think it's on HTTP rather than HTTPS, and Superset returns redirects to HTTP URLs, which browsers block due to the recently added CSP.
We could use a Network Load Balancer which will pass through the x-forwarded-proto header unchanged, but since target instances are in ECS/Fargate, they have to be added to the target group "by ip". This then results in the fact that from the point of view of the Superset service security group, they are connected to from the internal IP(s) of the network load balancer. These IPs are not fixed, and there is no way to attach a security group …
=> (fix) Pass x-forwarded-proto as https to Superset to fix redirects

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py, infra/ecr.tf, infra/security_groups.tf
Not actually enabling for anything for now, since there are issues with
volume permissions and sudo. Specifically shared volumes between
containers end up owned by root, and also sudo fails, which means not
even starting the container as root and changing ownership will work. We
might be able to run as root, but will treat that as a last resort.
So, currently adding in the ability to switch between platform versions
in order to be able to switch to, and rollback from, any change without
a deployment.
For tools or visualisations on 1.4.0, this will:
- Bump the amount of space in user's home directories from 4GB to
(20GB - docker image size)
- Eventually allow EFS mounts, so maybe could bump it even more, and
move away from S3 for home directories
Note that not specifying the platform …
=> (feat) Ability to run tools or visualisations on Fargate 1.4.0

CHANGELOG.md, dataworkspace/dataworkspace/static/explorer-v1.js
Attempting to upload large numbers of files at once results in the AWS SDK attempting to initiate at least one connection per file. This means:
- Because the browser limits how many open connections to a server at once there can be, the later files don't actually start uploading soon enough, and they timeout.
- The browser also apparently limits how many connections can be queued: e.g. attempting to upload 2000 files at once in Chrome results in net::ERR_INSUFFICIENT_RESOURCES in the console, and NetworkError exposed to the user
This was reported by a user attempting to upload 500 files at once, so attempting to behave with 2000 files at once I think is reasonable.
=> (feat) Avoid TimeoutError and NetworkError when uploading lots of files

.envs/sample.env, .envs/test.env, CHANGELOG.md, dataworkspace/dataworkspace/apps/api_v1/datasets/views.py, dataworkspace/dataworkspace/apps/applications/management/commands/sync_sources_and_permissions_to_quicksight.py, dataworkspace/dataworkspace/settings/base.py, infra/ecs_main_admin.tf
Rudimentary implementation of a management command which can be used to
sync datasets and associated user permissions to AWS QuickSight so that
we can test out whether the tool might be a good fit for us. This is
purposefully a bit shonky because it's only for prototyping.
Some infrastructure changes are needed in order to allow QuickSight to
connect to the Data Workspace datasets DB - these have been/will be
created manually in AWS console for now.
Ticket: https://trello.com/c/gRDNW4YS/1064
The plan is to run this manually via AWS Console for each environment via `django-admin` using existing container overrides to change the start command from `./start.sh` to something like `django-admin sync_sources_and_permissions_to_quicksight`.
=> Trial syncing datasets/permissions to QuickSight

dataworkspace/dataworkspace/apps/applications/management/commands/sync_sources_and_permissions_to_quicksight.py, infra/ecs_main_admin.tf
The previous permission was too restrictive - prevented some API calls. For prototyping I think it's OK to open this up  rather than pinning down the exact perm/resource pairing.
=> Don't restrict resources for quicksight

.envs/sample.env, .envs/test.env, CHANGELOG.md, README.md, docker-compose.yml
Not connected to any database other than the ephemeral one it would load
up in its container, but enough to test a bit of code in the proxy.
=> (dev) Ability to load up Metabase locally

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/management/commands/sync_quicksight_user_datasources.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py
The current test for quicksight has a central datasource which owns all of the datasets, then shares those datasets with each user individually. This doesn't allow users to create analyses using multiple tables, as they don't have access to the datasource to do custom joins.
This new model creates a persistent Data Workspace DB user per quicksight user and enforces the permissions model at the DB level. It doesn't handle dataset permissions being added dynamically (would need to re-run the sync tool), or removed at all (they will retain access in QuickSight). This should be OK for testing purposes. This means each user fully owns their own datasource connection, so they can join together whatever tables they like, which should be closer to what we want users to be able to do.
The 'delete …
=> Alternative datasource model for quicksight

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py
AFAIK no issues have been reported by the visualisations manually set to be wrapped in an iframe
=> (feat) Visualisations are wrapped in full height iframe by default

CHANGELOG.md, s3sync/Dockerfile, s3sync/start.sh
s3sync is a sidecar container running alongside tools: they share a volume to both write to and read from.
Fargate 1.3.0, seems to preserve the ownership from the containers, the s3sync user and group. However, in 1.4.0, it seems to now be owned by root. To write to the volume, there seems to be little alternative than to start the container as root.
However, we do this to change ownership of the files in the volume and then run the s3sync proper as the lower-privilege s3sync user.
=> (feat) s3sync is Fargate 1.4.0 compatible

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/admin.py
Add an export selection option to the datacut query admin page. This is necessary to allow us to find queries that need tables renaming and incorrect sectors in use.
=> Add datacut query export from admin listing page

CHANGELOG.md, infra/ecs_main_admin_container_definitions.json, jupyterlab-python/Dockerfile, jupyterlab-python/start.sh
Since the volume shared between containers in Fargate 1.4.0 ends up being owned by root, we have to start JupyterLab as root and change the permission of the home directory, and then start up JupyterLab as a lower privileged user.
The ability to run sudo was very recently added to Fargate 1.4.0 (without even a minor version bump).
=> (feat) JupyterLab Python Fargate 1.4.0 compatible

CHANGELOG.md, jupyterlab-python/Dockerfile
There was a default secure_path in the sudoers file, so overwriting the
entire file.
=> (fix) Preserve PATH in JupyterLab

CHANGELOG.md, rstudio/rstudio-start.sh
It would keep old credentials/paths, and then (for example) attempting
to talk to to S3 would fail.
=> (fix) Ensure to clear previous R environment on RStudio launch

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/datasets/test_models.py
Data flow can now upload .zip files, so we can't just generate .csv
file names any more (or the download will have the wrong extension,
which will confuse some users and programs).
For source links, therefore, we will grab the extension from the URL
(for the given case it'll be an S3 URI) and apply that to the filename.
=> Update source links to support different file types

CHANGELOG.md, dataworkspace/dataworkspace/templates/running.html
The `allow-downloads` sandbox attribute is not documented at
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
But it seems to be a recent addition in Chrome
https://www.chromestatus.com/feature/5706745674465280. The error in
Chrome 83 without this is:
Download is disallowed. The frame initiating or instantiating the
download is sandboxed, but the flag ‘allow-downloads’ is not set.
=> (feat) Allow downloads from visualisations

CHANGELOG.md, infra/ecs_main_metabase_multiuser.tf
After contact with AWS Support, /etc/hosts is now writable in Fargate
1.4.0. This means that start.sh can take the value from
/proc/sys/kernel/hostname, write it to /etc/hosts as 127.0.0.1
... which means that Metabase, which during startup attempts to resolve
the value from /proc/sys/kernel/hostname to an IP address, can indeed
startup
=> (feat) Bump Metabase to Fargate 1.4.0

dataworkspace/proxy.py
Debi is doing some work with GTM on visualisations and needs this domain in order to develop/test her analytics via the GTM preview panel.
=> Allow tagmanager preview panel domain

dataworkspace/proxy.py
In order to embed Metabase dashboards in a Data Workspace page we
need to allow iframes from main Data Workspace domain.
This would only apply to Metabase /embed/ pages, since Metabase has
its own CSP header that disables frame-ancestors on all other pages.
=> Allow embedding Metabase pages from the root domain

CHANGELOG.md, dataworkspace/dataworkspace/templates/tools.html
From
to
Screenshots taken from Chrome on Mac OS. The change behaves similarly in Firefox (although the dropdowns to my eye look a more ugly in Firefox, they are equally ugly, but at least better aligned)
=> (fix) Tools buttons/dropdown alignment

dataworkspace/dataworkspace/apps/applications/management/commands/sync_quicksight_user_datasources.py
When syncing data sources/permissions from Data Workspace to QuickSight,
we only want to do it for authors. Readers and users created to view
embedded dashboards - we don't want to (and QuickSight won't let us)
grant them datasoruce permissions.
=> Ignore quicksight reader users

infra/ecs_main_admin.tf
The dashboard role gives the admin run task role permission to assume it, but not vice versa, so this patch allows the admin run task role to assume the dashboard role.
=> Allow admin task to assume quicksight role

dataworkspace/dataworkspace/apps/applications/utils.py
This caused the function to fail if it successfully registered a new user, as later parts of the function continued to expect `user` to be a model instance rather than the response from registering a user with QuickSight.
=> Don't overwrite user variable

CHANGELOG.md, Dockerfile, etc/nginx/nginx.conf
The `server_tokens off;` turned off the nginx version from the server header, but it was still sent as `nginx`, and it comes up in ITHCs that we shouldn't be exposing the underlying server in headers.
=> (feat) Override the server header

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py
From the user's point of view, this is a refactor...
... but is a step towards EFS. For home directories. For each user to
have a different mount location in EFS, this has to be specified in the
task defintion. The location can't be specified in the overrides passed
to run_task [this has been confirmed with contact with AWS Support]. So
we create a task definition per launch.
So far, there doesn't seem to be an issue doing this for visualisation
previews, but extending this behaviour to tools, and releasing ahead of
actually moving to EFS, just in case there is some unexpected behaviour
that means we have to re-evaluate/plan the move to EFS.
=> (feat) Create a new task definition per tool launch

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py
We are getting regularly errors where our unused-user cleanup task fails
to acquire redis locks in order to drop users. It's hard to investigate
what's going on - knowing which locks are failing _may_ give us more
information and/or narrow things down slightly.
=> Add more logging around redis cache lock failures

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py
We are regularly seeing errors where we're unable to acquire a lock
quickly enough, which we believe means it has become stuck. This patch
will give the lock a TTL of 3 minutes, and it will automatically be
available for re-locking after that time, which should reduce any need
for us to bump the lock version.
=> Bump cache lock version and auto-expire

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py, requirements-dev.txt
We've had some sentry errors about being unable to delete users because
they don't exist that is attributed to multiple instances of this task
running at the same time. By adding a lock around the inner-workings of
the job we can ensure only one instance is running the task at a time,
which should prevent these errors. Any instances that fail to get the
lock can just die silently.
=> Lock the "delete users" task

dataworkspace/proxy.py
This removes any /embed/ Metabase URLs from the VPN check, allowing
all Data Workspace users to access them
=> Allow access to Metabase embeded dashboards without VPN

dataworkspace/proxy.py
Since embedded Metabase dashboards are not static HTML pages, apart
from the iframe URL itself we also need to exclude JS and CSS asset
URLs and embed API endpoints from the VPN check.
=> Exclude Metabase embed resources from VPN requirement

CHANGELOG.md, dataworkspace/dataworkspace/apps/accounts/backends.py, dataworkspace/dataworkspace/tests/common.py, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/proxy.py, test/test_application.py
People tend to be identified by their contact_email in SSO, rather than their email (which sometimes isn't changed because it can break things AFAIK).
This might need to be followed up be a job/management command to run to change the email without users having to visit Data Workspace to do it.
=> (feat) Use SSO contact_email as primary email

CHANGELOG.md, theia/Dockerfile
We allow users to run apt-get to install packages from our Debian mirror, but only via sudo. This should have been possible already in Theia, but there was a blind copy+paste from the RStudio image.
=> (fix) Allow Theia user to run apt-get via sudo

CHANGELOG.md, rstudio/Dockerfile, rstudio/rstudio-start.sh
I actually thought APP_SCHEMA was already in the RStudio environment, but not sure how it could have been without this change...
=> (feat) Populate APP_SCHEMA in RStudio environment

CHANGELOG.md, dataworkspace/proxy.py
We can't talk to GA from the browser in visualisations, so doing so from the server
=> (feat) Send to Google Analytics from the proxy for visualisations

CHANGELOG.md, dataworkspace/dataworkspace/templates/tools-unauthorised.html
Civil Service Learning website is changing, apparently, and this is the
new link to the course that users will need to complete.
=> Update link for responsible for info course

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/test_models.py
Fixes issue where setting an "auto id" field as the sort field on a reference dataset caused a 500 due to a missing table.
=> Sort by model id when "auto id" field is set as sort field

CHANGELOG.md, theia/Dockerfile, theia/requirements.in, theia/requirements.txt
Full disclosure: for some reason the latest Pylint is not installable from our mirror. I don't know what happened here. However, given usage of Theia (almost zero) and the consequences of going back a patch version are likely minor, am fine with it.
=> (feat) Install more useful Python packages in Theia

CHANGELOG.md, Dockerfile
The Python 3 version available in alpine 3.10 has been updated to
address CVE-2020-14422, which means our container no longer builds as
3.7.7-r0 is no longer available. This patch bumps us  to 3.7.7-r1.
https://git.alpinelinux.org/aports/commit/?id=21a5b7dd0924932b20512155471ee45dada0abf4
=> Bump Python version for data-workspace

CHANGELOG.md, infra/ecs_main_dnsmaq.tf
The subnet in which tools and visualisations run does not use AWS's DNS resolver, and instead our own, that conditionally forwards requests to AWS's DNS resolver. This is so we can filter outgoing DNS requests to only DNS servers we control or trust.
EFS use the concept of "mount target": essentially a hostname that resolves to an IP address for one availability zone, which each EFS client uses to mount the filesystem. Each of these only resolves in a single AZ, and so for this to resolve in the AZ that the DNS resolver is in, the DNS resolver must in that same AZ. So here we fix the AZ to later be able to create the mount target in a fixed AZ.
Potentially we could have a mount target per AZ. However, we would always want tools to use the mount target for the AZ they are launched in, and …
=> (feat) Run DNS resolver in fixed single subnet for upcoming EFS home directories

CHANGELOG.md, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/templates/partials/gtm_head.html, dataworkspace/dataworkspace/tests/datasets/test_download_views.py
A recent patch split the GTM head/body scripts into files that were
included into templates, rather than using blocks directly. The head GTM
snippet had a nested block that provided a hook to inject initial GTM
events. When this was switched over to use includes rather than blocks,
the injected events were no longer rendered to the page. This patch adds
a block above the head snippet that provides a point at which these
initial events can be injected again.
Ticket: https://trello.com/c/7TU1vgTH/562
=> Fix GTM initial setup

CHANGELOG.md, dataworkspace/dataworkspace/apps/accounts/admin.py
Access to master datasets can also be granted to users on the user admin
form, so we should sync permissions if any permissions are changed from
that view as well.
=> Sync quicksight perms from user form

CHANGELOG.md, dataworkspace/dataworkspace/apps/accounts/management/commands/store_db_creds_in_s3.py, dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py, test/test_utils.py
At the moment we have a static DB user for quicksight and whenever we
grant new permissions we re-generate credentials for the same username
and push those to QuickSight. However, we didn't have an implementation
for revoking permissions. After a little time looking at adding more
thorough grant/revoke to the single mutable user, it felt easier to
instead go for immutable users that grant all the right permissions as a
one-off and then we simply discard that user and generate a new one if
we need a different set of permissions.
Our immutable quicksight users last 7 days rather than 31 for tool
users. This is for a few reasons:
1) We re-sync permissions for all QuickSight users every night, so
really they are unlikely to be used after 24 hours. 7 days gives us some
grace if this nightly …
=> Use immutable DB users for quicksight

.circleci/config.yml, Dockerfile
Split out unit and functional tests so that they run in parallel
Cache the docker layers for data-workspace-test, as a significant
portion of the test runner time is building the docker image - which
will be similar if not identical in the majority of cases.
In testing:
* Linting results come back in about 20 seconds with cache hits and 60-80 with cache misses. Previously they would come back in about 60-80 seconds.
* Unit tests come back in about 2 minutes with full cache hits and 7 minutes with full cache misses. Previously they would come back in about 12 minutes (bundled with integration tests).
* Integration tests come back in about 7 minutes with full cache hits and 11 minutes with full cache misses. Previously they would come back in about 12 minutes (bundled with unit tests).
=> Optimise circleci tests for speed

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/spawner.py
Some of our visualisation pipelines take a long time to build -
especially R-based ones. Let's give them 45 minutes now rather than 30
minutes.
=> Allow more time for GitLab pipelines to complete

CHANGELOG.md, dataworkspace/dataworkspace/templates/admin/reference_dataset_changeform.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
Trello card: https://trello.com/c/Uk5Shu5p/480-improve-loading-time-on-reference-dataset-pages
Get reference dataset fields via the reference dataset model rather than through the record itself when looping through records. This was causing extra queries on each record (thousands in total) when looping through a recordset.
Before:
After:
=> Loop over fields via reference dataset rather than record.

dataworkspace/proxy.py
It's possible that the earlier "try" block will bail before we get
around to defining `downstream_ws`. In that case just bail.
https://sentry.ci.uktrade.digital/dit/data-workspace/issues/27876/
=> Suppress UnboundLocalError

CHANGELOG.md, dataworkspace/dataworkspace/settings/base.py, dataworkspace/proxy.py, dataworkspace/sentry.py
Move the sentry setup code from Django settings and the proxy to a
separate file so that we can share code/config.
Group CancelledErrors together so that we only have a single event for
them in Sentry, making them less noisy and easier to handle. Same for
ConnectionResetError, which is also fairly prolific in the proxy and
pops up in various places with the same outcome.
=> Centralise sentry config

CHANGELOG.md, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/tests/core/test_views.py
The help centre looks visually similar to Data Workspace and we believe
some users are finding it hard to navigate when taken away from our
services into the help centre.
Let's open the help centre in a new tab, with some extra content to help
screenreading users understand what navigation is happening.
Ticket: https://trello.com/c/kwX9SnKz/534
=> Open help centre in new tab

dataworkspace/dataworkspace/templates/partials/form_field.html
An accessibility check picked up that field labels were not set on https://data.trade.gov.uk/support-and-feedback/:
Before:
After:
=> Use "id_for_label" when rendering label element instead of "id"

.envs/sample.env, .envs/test.env, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
For the initial release, we want QuickSight authors to focus on creating
dashboards with Data Workspace data as opposed to arbitrary other data.
QuickSight now lets us apply custom permissions to users so that we can
lock down creating data sources, so let's apply that permission and
enforce it as part of the regular sync.
Ticket: https://trello.com/c/YFHckT4L/664-prevent-authors-creating-data-sources-in-quicksight
=> Stop authors creating quicksight data sources

dataworkspace/dataworkspace/apps/api_v1/views.py
When a user accesses tools for the first time, IAM credentials need to be created but as the various IAM operations are eventually consistent, this may fail. This is currently attempted 3 times but it will be useful to add a sleep for 5 seconds in between attempts to reduce the chance of this failing.
Sentry error where this was picked up: https://sentry.ci.uktrade.digital/dit/data-workspace/issues/28536/
=> Sleep when attempting to create new IAM credentials for running tools

dataworkspace/dataworkspace/templates/files.html
The wave tool has picked up an empty table header cell as an accessibility error, this PR replaces the `<th>` with a `<td>`
=> Use <td> for empty table cell instead of <th>

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
Removes the BOM write
- GDS data standards require removal of BOM
- In this instance writing the BOM had no effect anyway
=> Remove unnecessary utf8 BOM write from csv downloads

CHANGELOG.md, dataworkspace/dataworkspace/static/explorer-v1.js, dataworkspace/dataworkspace/templates/files.html
This is to make the Your Files page more reasonable when CSS is disabled. Note that the modal HTML is there is Javascript is disabled, since the ng-if will remove elements using Javascript, but in this case, the whole interface won't work anyway.
There is some duplication here, but given the number of modals, the current uncertainty regarding the page, and the fact that to address this I suspect will have to do a lot of faffing with templates and/or transclusion that can get a bit complicated, suspect not worth it.
=> Keep Your Files modal HTML out of the DOM until it's needed

requirements-dev.txt
We use these dependencies in our pre-commit hooks so they should be in
our dev requirements.
=> dev: add pylint dependencies

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/urls.py, dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/tests/applications/test_utils.py, dataworkspace/dataworkspace/tests/applications/test_views.py, dataworkspace/dataworkspace/tests/common.py, dataworkspace/dataworkspace/tests/core/test_views.py
Users have to create their own accounts for QuickSight, which they do through a DIT SSO journey we can't easily hook into. This means that we aren't able to configure their QuickSight account the moment it's created. As a slight workaround to this, we change the 'Launch QuickSight' button on the tools page to go to an intermediate page on Data Workspace, where we can kick off a background job that polls for their account to be created in QuickSight, before redirecting them to the QuickSight SSO login flow. This background job will check once a second for 5 minutes for the user account to be created, and when it is, it will create their data source and apply our custom permissions. We hypothesis that this should catch the majority of users, as the only sign-up step when you get to …
=> Polling sync for quicksight on launch

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/datasets/data_cut_preview.html
design changes:
- back button on preview page instead of breadcrumbs
- no vertical scrollbar for 10 or less preview records
- truncate preview results if more then 100 chars
=> fix: preview design updates

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/static/app-filter-show-more.js, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/datasets/filter.html, dataworkspace/dataworkspace/templates/datasets/filter_option.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/core/test_views.py, dataworkspace/dataworkspace/tests/datasets/test_forms.py
Add some clearer explanatory text around our filters and search box to
help users understand what they are for. Also update the source filter
choice field to only render 10 sources initially, with an option for the
user to reveal more if needed.
=> feat: update home page text and filters

dataworkspace/dataworkspace/apps/core/utils.py
The string replace fails when the access_point_id is None, which would be the case for literally everyone when this is deployed.
The alternative would be to make the field not be nullable. However, since everyone won't have an access_point_id, this means we would have to remove the unique constraint from the DB. Choosing to avoid that since users accidentally being assigned the same access point ID would be very bad.
=> Fix loading tools with None as access_point_id

dataworkspace/dataworkspace/apps/accounts/admin.py
The default is a blank string, which causes unique constraint errors (that we want to keep to mitigate risk of a user getting access to the another's home directory). Instead, the Postgres `NULL` is desired, which is derived from the Python `None`.
Note that trying to set on the model:
> unique=True, blank=True and null=True
as suggested at https://docs.djangoproject.com/en/dev/ref/models/fields/#null doesn't address the issue, since the field in Django admin is a manually added one, rather than automatically generated from the model, which is the case where the documentation applies.
=> fix: saving of user's Django admin page

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/views.py
Tested via manual deploy to analysisworkspace using an IE11 VM.
Dashboard embedding is broken in IE11. The latest update from support
suggesed using their AWS QuickSight JS embedding SDK, which we tried,
but ironically that doesn't support IE11 right now (syntax error:
awslabs/amazon-quicksight-embedding-sdk#50).
The "non-recommended" alternative was to append this query parameter
manually, which we'll now do in order to bring IE11 support back
immediately.
=> fix: add query param to support embedding in ie11

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/tests/datasets/test_models.py, requirements.txt
This PR uses the https://github.com/alculquicondor/psqlparse library to parse the sql query on the CustomDatasetQuery model. 
The parser uses the Postgres source code to parse the query so it doesn't need to connect to the database or run any additional queries. 
The parser generates a list of database tables derived from a query's FROM clause and these are exposed on the CustomDatasetQuery model as a property called `parsed_query_tables`. 
For now this is only displayed on the admin screen as a readonly field as shown below but will be shown on the front end eventually:
It was decided to do this parsing dynamically rather than on save to avoid having to migrate all of the existing queries on production. We should probably re-evaluate this once we are happy with the quality and accuracy …
=> feature: parse datacut sql queries and display queried tables on admin screen

CHANGELOG.md, dataworkspace/dataworkspace/apps/applications/utils.py
QuickSight user creation is eventually consistent, so after the
CreateUser call returns 200, when we call CreateGroupMembership, the
user might not have synced yet so it may return a
ResourceNotFoundException. Add some retries with increasing delays to
help offset this.
Addresses a recent sentry error I encountered in Staging.
=> fix: add retries to address eventual consistency

dataworkspace/proxy.py
The styles on the Tools loading page depends on the <base> tag having the correct URI, including https://. However, the admin application thinks it's on HTTP and generates it with http://.
=> fix: unstyled Tools loading page

CHANGELOG.md, infra/ecs_main_admin_container_definitions.json
It tries to bind EFS when the version of Fargate doesn't support it, and it raises PlatformTaskDefinitionIncompatibilityException.
Once this is done, we could probably make Fargate 1.4.0 the default, but for now, baby steps. There are some subtle differences with volumes, users, /etc/hosts that means 1.3.0 -> 1.4.0 may break things.
=> fix: Data Explorer when a user has an EFS access point

CHANGELOG.md, Dockerfile, dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/app-filter-show-more.js, dataworkspace/dataworkspace/static/search.js, dataworkspace/dataworkspace/templates/datasets/filter.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/common.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, docker-compose-test.yml, requirements-dev.txt, test/pages.py, test/test_application.py
Appends search result numbers to the filters on the homepage, showing users how many results will be available if that filter option is toggled on/off.
Adds a functional test using `pyppeteer` to launch chromium and interact with the site. This is the first browser-based test we have, so would be interesting to get some feedback on implementation/choice as this could be expanded/reused for any smoke tests we want to run on the live service. The test itself is quite specific in order to test variations of filters against datasets - open to ways to increase the flexibility and range of the test.
Includes a minor HTML semantic fix to make sure that filter hints have unique IDs rather than a strangely-hardcoded one, and another fix to properly filter unpublished datasets for admin users. …
=> Preview filter numbers

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Two regressions slipped into the search filters feature.
1) Datasets would be counted twice if they required explicit access and
multiple users, including the current user, were granted access, due
to the query grouping on all values including `has_access`, which
with multiple permissions would return one row saying the user has
access and another saying it doesn't. These two are now aggregated
with `bool_or` to return one true row if any of the user permissions
confirm access.
2) Visualisations would be counted multiple times in the search filter
counts, once for every user with explicit permission grants, due to a
join that wasn't aggregated properly.
Adds a test that should prevent duplicate regressions.
=> Fix data vis count

dataworkspace/dataworkspace/apps/datasets/migrations/0053_set_custom_dataset_query_tables.py, dataworkspace/dataworkspace/apps/dw_admin/forms.py, dataworkspace/dataworkspace/tests/test_admin.py
The create temporary view statement fails if the inner query has a semicolon so this PR strips it out.
=> fix: strip ';' from end of CustomDatasetQuery when creating temp view

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/tests/conftest.py, dataworkspace/dataworkspace/tests/datasets/test_download_views.py, dataworkspace/dataworkspace/tests/datasets/test_models.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py, test/test_application.py
Closes: https://trello.com/c/U2f069TH/779-spike-show-last-updated-date-and-time-against-data-cuts-and-master-datasets
- Query the new data flow metadata table for master dataset and query last update date
- Query s3 for data cut source link last updated date
=> feat: add last updated time to data cut and master dataset pages

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
This is an attempt to avoid holding locks that prevents data-flow from swapping tables.
=> feat: timeout long statements and idle transactions

CHANGELOG.md, infra/ecs_main_gitlab.tf, infra/main.tf
The default is apparently 30gb, which is a bit small given usage and the frequency of running out of space.
=> Bump gitlab runner volume size

requirements.txt
Greenlet has just released a new version, 0.4.17, that is currently
breaking our deploys. This is a transitive dependency of gevent, and at
the moment we don't pin sub-dependencies, so the latest release is
getting pulled in. Let's pin this temporarily while we address that
problem more widely.
=> fix: pin greenlet temporarily

CHANGELOG.md, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
The tool-based Data Explorer is a single-tenant solution, and we want to
maintain the existing design/implementation as we move across to the
integrated version.
This patch accordingly hides other users queries and makes them
inaccessible.
=> feat: hide other users queries

dataworkspace/dataworkspace/apps/explorer/tasks.py, dataworkspace/dataworkspace/settings/base.py
* Only schedule the data explorer schema tasks when we have enabled them
in the settings.
* Use the main Data Workspace celery app to schedule the tasks.
=> fix: data explorer celery async tasks

CHANGELOG.md, dataworkspace/dataworkspace/apps/core/utils.py
For the TAP/TARIC dataset that we manually pg_dumped-in, apparently the tables are not really useful, but the views that came with it are. We could convert the views to tables, but leaving them as views so they can be tweaked more easily if necessary.
This would be the first case of a master dataset being a view, but I'm tempted to treat this a bit of an investigation. I think we might want _all_ master datasets to be views, since they _might_ offer more mechanisms to swap data while being used
=> feat: allow master datasets to be views

CHANGELOG.md, dataworkspace/dataworkspace/apps/api_v1/views.py
It fails to start, since the task definition of visualisation is not written with a volume. However, it shouldn't bind to the EFS access point of the person that happened to start the visualisation.
=> fix: don't attempt to bind to EFS when starting a visualisation

dataworkspace/dataworkspace/templates/tools.html
Update the Data Explorer feature flag to hide the existing Data Explorer
tools-based application when the integrated tool is visible. This won't
affect the ability to access the tools-based version by hitting the URL
directly.
=> feat: flag to switch Data Explorer versions

CHANGELOG.md, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
Entering non-numeric values results in a form error. These fields are not properly part of the form due to historical implementation, so this is the simplest fix (we also don't have a design for how these fields would look in an error state, so leaving that for now).
https://trello.com/c/nS5Gcpta/941
=> fix: suppress invalid pagination input

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/static/explorer_schema.js
We've had an issue lately where the schema search panel doesn't fully
initialise its GOV.UK Design System accordion sections. After
investigating (with the kind help of the GDS Design System team ...)
this is an incompatibility with list.js, which was also building the
dynamic search for the schema panel at the same time. By instead
initialising GOV.UK Frontend first, and then when that's complete kick
off the search indexing, we can avoid this issue.
=> fix: init GOV.UK frontend before schema search

CHANGELOG.md, dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py, dataworkspace/dataworkspace/templates/partials/code_snippets.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Add a link on master dataset pages to launch a basic query of that one
of that dataset's tables in Data Explorer. For now, this is behind the
same flag that controls whether or not a user can use the integrated
Data Explorer, so that people with the tools-based version don't see
this and think it doesn't work.
=> feat: launch dataset in data explorer

dataworkspace/dataworkspace/templates/admin/reference_data_delete_record.html, dataworkspace/dataworkspace/templates/admin/reference_dataset_edit_record.html
Remove missing `admin.css` staticfiles from 2 Django-Admin templates. This file has been missing for a while, but the recently-integrated Data Explorer now raises errors when trying to lookup the file.
=> fix: remove unused admin.css static file references

.envs/test.env
Running make docker-test-unit locally fails as the env var is quoted when it shouldn't be: https://dev.to/tvanantwerp/don-t-quote-environment-variables-in-docker-268h
=> fix: remove quotes around explorer connections

.envs/sample.env, .envs/test.env, CHANGELOG.md, Makefile, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/entrypoint.sh, dataworkspace/proxy.py, dataworkspace/proxy_session.py, docker-compose-test.yml, test/test_application.py
The previous change worked fine if the user already had the path-specific cookie from visiting a visualisation. However, for a new user, they would get sent to SSO and then back, and then back to SSO, in an infinite loop. This was due to the proxy initially setting a `SameSite=Lax` cookie on the first visit inside the iframe which redirects to SSO. This means that it _won't_ be used when it comes back from SSO, and sends the user to SSO again.
This is fixed by ensuring we have a `SameSite=None` cookie, restricted to the path `/__redirect_from_sso` initially sent along with the redirect to SSO. This allows the browser to use it when it comes back from SSO in the iframe.
Debug mode is now disabled in tests, since django-csp doesn't set the CSP for 404s in debug mode, which is one of the …
=> fix: login sso-cycle from iframes

.envs/sample.env, .envs/test.env, Makefile, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/entrypoint.sh, dataworkspace/proxy.py, dataworkspace/proxy_session.py, docker-compose-test.yml, test/test_application.py
This reverts commit 1c88ad375e4a137555d820137652c2673eef12e7.
The recent change to allow embedding visualisaitons in iframes I think
caused apparent occasional infinite loops round to SSO. Suspect this is
due to multiple cookies of the same name in some cases during login on
the /__redirect_from_sso path
Reverting as nothing in production depends on this behaviour yet.
=> Revert "fix: login sso-cycle from iframes"

CHANGELOG.md, theia/Dockerfile, theia/package.json, theia/yarn.lock
Note that this is _not_ the latest version of vscode, as it seems to not be compatible with the latest Theia version. The latest throws
> Promise rejection not handled in one second: TypeError: Cannot read property 'activeNotebookEditor' of undefined , reason: TypeError: Cannot read property 'activeNotebookEditor' of undefined
=> feat: bump Theia and vscode-python to support notebooks

CHANGELOG.md, theia/Dockerfile
pip would try to install into /usr/local/lib/, but it wasn't writable
In addition to using home directory less space, this means executables end up in the path, and so are easier to run. This is more consistent with JupyterLab Python.
=> feat: by default install Python packages in standard location, not in home directory

CHANGELOG.md, jupyterlab-python/Dockerfile, theia/Dockerfile
This would result in both smaller Docker images, and so a faster start, and use less disk space. And, I suspect less likely things would go wrong down the line if some of the packages do something environment-specific like compiling.
From https://pip.pypa.io/en/stable/user_guide/, to _enable_ the boolean option `--no-cache-dir` you have to specify a falsey value.
=> feat: don't cache pip packages

visualisation-base-r/Dockerfile
=> fix: add missing quote marks in cran repo name

CHANGELOG.md, s3sync/Dockerfile
Bump mobius3 (used in the s3sync) to behave better when on EFS and there are existing files: use less memory and be faster on start, and don't delete files that exist locally until it's sure they're not on S3.
=> feat: bump mobius3 to be more EFS-friendly

CHANGELOG.md, dataworkspace/dataworkspace/apps/explorer/templates/explorer/query.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/query_list.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/querylog_list.html, dataworkspace/dataworkspace/apps/explorer/templatetags/explorer_tags.py, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/settings/base.py, dataworkspace/dataworkspace/static/explorer_custom.css, dataworkspace/dataworkspace/tests/explorer/test_tags.py, dataworkspace/dataworkspace/tests/explorer/test_views.py, test/selenium/test_selenium.py
Minor updates to the Data Explorer saved queries and query log pages in line with new design by Bo.
=> Data explorer logs redesign

CHANGELOG.md, dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/static/explorer_query.js
As part of Firebreak, this is an attempt to update autocomplete to include schema, table names that the user has access to.
=> adding table names into autocomplete list

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/query.html, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
At the moment, in Data Explorer, we pass SQL queries and related data
through query params until the user does a final POST to create a query
object. This presents a couple of problems:
1) Long queries (e.g. over 2000 chars) may be truncated or corrupted by
some browsers which have low limits on the length of URLs/query
params.
2) There could potentially be data protection issues with sending
queries in the URL, as it may contain sensitive information that
would end up being logged/retained for longer than necessary.
Let's use POST to move SQL query data between pages. This addresses the
above concerns but does introduce a few others:
* Back/forward browser navigation is not as clean - users are likely to
see 'resubmit form'-style warnings if they navigate back, because we're
showing a …
=> fix: use POST not GET for dialog/saving queries

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/query.html, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
Reverts uktrade/data-workspace#1023
Going to install a temporary query model so that we:
1) use post-redirect-get to avoid back/forward navigation prompting the user to resubmit the form
2) ensure that SQL is preserved even when using backlinks from the 'save query' dialog page.
=> Revert "fix: use POST not GET for dialog/saving queries"

docker-compose-dev.yml
When running Data Workspace through docker-compose-dev, we may want to
be able to connect to other Data Infrastructure services such as
data-flow or data-store-service. Not aware of a current use-case for
this, but there are for other of our services to talk together, so doing
this to be consistent.
=> feat: use shared data infrastructure dev network

jupyterlab-python/Dockerfile, jupyterlab-r/Dockerfile, mirrors-sync-cran-binary/Dockerfile, rstudio/Dockerfile, visualisation-base-r/Dockerfile, visualisation-base/Dockerfile
As we are using a custom debian mirrror we currently disable the check which verifies expired digital signatures.
This PR moves this option to the apt config rather than setting it every time we call apt-get commands.
The docker images affected were all built successfully on my local machine after making the change.
=> Move signature check to config

dataworkspace/dataworkspace/apps/explorer/templates/explorer/query.html, dataworkspace/dataworkspace/apps/explorer/views.py
* only show 'query logs' link when viewing a query (not when
editing/saving an update to a query).
* move the query logs link onto it's own line and give it slightly
clearer content.
* increase the size of the title on the query detail page
* don't show backlink on query detail page
=> Tweak Data Explorer query detail page

rstudio/Dockerfile
This needs to be set in Rprofile.site in addition to setting it in repos.conf to support both RStudio environment sessions and normal sessions
=> fix: set the cran mirror repos in Rprofile.site

dataworkspace/dataworkspace/static/explorer_query.js
At the moment the SQL box of the Data Explorer is limited strictly to 10
rows. Let's allow this to grow dynamically as user's type in longer
queries - up to 75 lines max - as the limited height of the box has been
raised as a pain point by some of our current users.
=> feat: allow sql query box to grow in height

CHANGELOG.md, pgadmin/Dockerfile, pgadmin/pgadmin-config.py
This is done to fix the error
> DOMException: Blocked a frame with origin [...] from accessing a cross-origin frame
that prevents pgAdmin from fully loading when started in a new tab.
Suspect it's due to https://github.com/postgres/pgadmin4/blob/REL-4_8/web/pgadmin/browser/static/js/layout.js#L77 which raises an exception when window.opener is present, but from a different domain.
This appears fixed in recent version of pgAdmin, since the code that throws the exception is wrapped in a try/except block
https://github.com/postgres/pgadmin4/blob/80ab5969920b1b258c4bb52020badbc67cf805ab/web/pgadmin/static/js/window.js#L14,
It was investigated to use `rel="noopener"` on the `form` element, but this only works on `a` elements. In a future version, we may be able to use `a` elements that have …
=> feat: bump pgAdmin to 4.27

.envs/test.env, dataworkspace/dataworkspace/settings/base.py, dataworkspace/start.py
We use the `debug` Django setting to configure Django for running
locally, but it should be possible to run the app not in debug mode when
running it locally. This patch separates out the setting for running in
debug mode from a setting that confirms we're running locally, so that
various settings can be tied to the correct semantic check.
=> fix: semantic separation between debug and local

dataworkspace/dataworkspace/templates/tools.html
Remove the 'alternative to pgadmin' phrase, as we want Data Explorer to
be the primary use with pgadmin as an alternative.
=> fix: update content for data explorer

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR enables the catalogue page to show related master datasets for a given datacut. Custom queries are the only datacuts dealt with for the moment. Source views, Source tables and Source links need a different implementation and will be dealt with in subsequent tasks.
If there is one master dataset, it will be shown in two-thirds format. 
If there are more, then 3 are shown in each row.
=> Related data custom queries

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR fixes a bug where duplicate master datasets may appear in some situations where a datacut is made up of custom sql that queries two tables, and then a master dataset provides both of those two tables.
=> Duplicate related masters fix

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/apps/eventlog/models.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Add entries to our event log when users view (quicksight and datastudio)
visualisations so that we can understand how users are interacting with
our catalogue and which visualisations are popular/not. The eventlog is
automatically scraped by data-flow and returned to workspace as a master
dataset, so no further action needed for this.
=> feat: log when users view visualisations

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/tests/applications/test_utils.py
At the moment, the full overnight QuickSight sync is only running
against the first page of user results, and we now have well over 100
users (albeit mostly readers that this sync task will ignore). This
update adds pagination to the task so that all users are properly
synced. This is not overly urgent, because when users launch QuickSight
via Data Workspace we kick off an individual sync just for them, but
still feels like something we should fix.
=> fix: paginate through all users for quicksight sync

mirrors-sync-cran-binary/Dockerfile, mirrors-sync-cran-binary/build.R
Adds compilation and storage for the following packages that are being
used by new visualisations:
DBI
DT
bizdays
countrycode
flexdashboard
janitor
jsonlite
kableExtra
leaflet
lubridate
plotly
quantmod
readxl
rgdal
rmapshaper
rworldmap
scales
sf
stringr
tmap
tmaptools
zoo
=> feat: add more packages to cran-binary

dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/tests/datasets/test_download_views.py
This fix ensures a 404 is returned if an invalid uuid is provided in a url. Without this fix a validation error is thrown.
E.g. https://sentry.ci.uktrade.digital/dit/data-workspace/issues/27049/activity/
=> fix: match uuids in url paths for catalogue views

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR hides unpublished master datasets in related data section of datacuts.
=> hide unpublished master datasets in related data

dataworkspace/dataworkspace/apps/api_v1/eventlog/serializers.py, dataworkspace/dataworkspace/tests/api_v1/eventlog/test_views.py
The events API wasn't correctly serializing the id/name/type of the related object for VisualisationLinks because I hadn't added a serializer for that object type. So here is one.
=> fix: add serializer for view visualisation events

dataworkspace/dataworkspace/apps/explorer/models.py, dataworkspace/dataworkspace/apps/explorer/views.py
Creating and saving a query results in multiple calls to `save`, which
ends up logging multiple events for a single query save. Instead of
hooking into that method, let's explicitly log events at specific points
in the request.
=> fix: log events explicitly

dataworkspace/dataworkspace/apps/applications/utils.py
The sync sso task is currently failing to complete due to bad SSO data causing the creation of DW users to fail. This is now caught and logged to sentry instead.
=> fix: catch IntegrityError when trying to create users from sso

dataworkspace/dataworkspace/apps/dw_admin/forms.py
Adding a reference dataset without any fields results in a 500 at the moment. This returns the validation errors if any of the inline forms have errors. 
There is already a unit test for this, not really sure how it was passing but this was tested manually and it works.
=> fix: show validation error for reference datasets if no fields present

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Show catalogue item published status for unpublished items:
https://trello.com/c/yu426OCN/1049-admins-can-identify-unpublished-catalogue-items-in-search-results
=> feature: show catalogue item published status for unpublished items

jupyterlab-python/Dockerfile, jupyterlab-python/start.sh
Remove Conda from JupyterLab-Python in order to have a simpler and faster build that is more consistent with our other tools.
Leaving JupyterLab-R for now, as we intend to retire that shortly given the limited uptake and the availability of an alternative tool, RStudio.
=> Remove conda

.circleci/config.yml, Makefile
Sometimes developers (or at least, me) forget to run `django-admin
makemigrations` for minor model changes. Let's use our CI to check that
there aren't any pending model migrations that need to be generated so
that this is less likely to get merged into master.
=> test: check no migrations are missing in CI

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/datasets/select.html, dataworkspace/dataworkspace/templates/datasets/select_option.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR adds datasets search/filter page, the capability to sort by the following:
- `Relevance`: '-search_rank,name', 
- `Newest first`: '-published_at',
- `Oldest first`: 'published_at',
- `Alphabetical (A to Z)`: 'name'
=> Adding sort feature to dataset browser

dataworkspace/dataworkspace/templates/datasets/select.html
missed out the spacing between label and select dropdown as per the design
=> spacing between label and select dropdown

pgadmin/Dockerfile
At the moment users are able to open files but not save them. This chowns the home directory to allow the pgadmin user to write to it.
https://trello.com/c/KhaR4dMw/1084-allow-save-of-sql-queries-in-pgadmin
=> feature: chown pgadmin home directory to allow tool to save sql files

dataworkspace/dataworkspace/apps/api_v1/views.py
At the moment launching a tool uses the default of 1GB cpu and 8GB memory if the user hasnt got a configuration saved for the tool. This logic is incorrect for visualisations as it needs to use the default cpu and memory specified for that visualisation regardless of the user's configuration.
=> fix: use application template specific defaults when non-tool launched

pgadmin/Dockerfile, pgadmin/start.sh
Saving files in pgadmin requires write access to the home directory, but the /home/jovyan directory doesn't exist when the Docker image is built (it is created by terraform) so it needs to be chowned when the tool is started.
=> fix: chown pgadmin home directory in start.sh and not Dockerfile

Dockerfile, requirements-dev.txt, requirements.in, requirements.txt
Rather than singling out psycopg2 for installation via the Dockerfile,
add it to our standard requirements.in tracking file for Python
requirements.
=> fix: move psycopg2 to requirements file

infra/ecs_pgadmin.tf, pgadmin/Dockerfile, pgadmin/start.sh
The pgAdmin user has to have the same ID as the user in s3sync, 4536, for the syncing to work properly (and the group ID is just for consistency)
Before this, if the pgAdmin users has a different ID to that in s3sync, there is a race condition between the s3sync container, and pgAdmin. If pgAdmin starts first, chowns the shared directory, then s3sync will exit shortly after launch since it won't have enough permissions to create files. Since S3 sync is essential, pgAdmin will also then exit. If s3sync starts first, pgAdmin will start and stay running fine (albeit without permission to save files).
The change to make the shared directory /home/pgadmin is not vital, but it means that the correct directory is chosen by the UI in pgAdmin by default.
=> fix: not being able to save files in pgAdmin, and fix exiting after start

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR adds a new checkbox, for users with appropriate access, for showing unpublished datasets. By default unpublished are hidden.
* [ x] Have tests been added to cover any changes?
=> show unpublished checkbox

Jenkinsfile, infra/ecs_main_admin.tf
Adds a separate ECS service to run celery workers for Data Workspace. **Commit-by-commit review probably easiest.**
This re-uses a lot of resources from the admin service, as it runs the same code and in theory needs almost all of the same access to external resources (e.g. redis, database, gitlab, etc). The notable exception is that the admin service SG allows HTTP/S in, which we theoretically would not want for celery. The celery service receives no public IP and so should not be routable from the Internet. I feel like adding a new security group with separate controls might increase the risk of not keeping the celery workers in sync with the main application in terms of access to external resources, potentially breaking a future release if the security group is only updated for the …
=> Celery ECS service

dataworkspace/dataworkspace/apps/datasets/forms.py
This PR fixes the label of unpublished checkbox to `Include` rather than `Show`
=> changing unpublished checkbox label

infra/ecs_main_admin.tf
Data Workspace adds the revision to tool tasks by itself, so we should
not include these in the tag.
=> fix: remove revision from pgadmin/rstudio

dataworkspace/start.sh
This PR is the third step of moving celery out of main data workspace instance. This removes celery worker from start.sh so that main instance doesn't spin them any more. They are now part of separate celery instance.
=> remove celery worker from start.sh

postgres/entrypoint.sh
Turn session logging off for pgaudit. This reduces the noise created by tools like pgadmin that query the catalog heavily.
=> feat: turn off pgaudit session logging to reduce noise

dataworkspace/dataworkspace/apps/explorer/templates/explorer/query_list.html, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
This PR is to help ignore SQL validation when saving queries in Data Explorer. This will help users to work with queries in parts, they don't have to be fully validated while they are still working on it.
This also removes `Download CSV` link in `Saved queries` section of Data Explorer. As we can't run queries confidently. And with this link you can only download first 1000 rows, if you have more. So it was decided that we should remove this link.
=> Data explorer: ignore sql validation when saving

dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/tests/test_admin.py
This PR is to reset user credentials that are cached when master dataset permissions are changed.
=> reset data explorer creds when changing master dataset permissions

Dockerfile
Jenkins builds are failing due to missing lxml version.
=> fix: bump lxml-dev version

dataworkspace/dataworkspace/apps/accounts/admin.py
The connection_schema_cache_key method relies on a user profile existing and this won't be there when creating a new user in the admin
=> fix: don't attempt to clear schema cache when adding new user

dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/tests/core/test_views.py
=> feat: add data hub link to header

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/urls.py, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/apps/explorer/views.py, dataworkspace/dataworkspace/tests/explorer/test_models.py, dataworkspace/dataworkspace/tests/explorer/test_utils.py, dataworkspace/dataworkspace/tests/explorer/test_views.py
Users sometimes write very long queries, which they shoule be able to
download. Our Data Workspace proxy, using aiohttp, only supports quite
short HTTP headers/params and often 500s if a very long query is
submitted using GET parameters. Let's switch to using much shorter URLs,
taking advantage of our query logging, to fetch the desired SQL from the
database rather than from the client.
=> fix: don't use query params for download SQL

dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/tests/explorer/test_utils.py
Fix bug in total row count introduced after storing query results in table and fetching from there
=> fix: return total row count of original query in data explorer

dataworkspace/dataworkspace/apps/datasets/models.py
As it was the refernece dataset uploader was expecting dates in the
format %m-%d-%Y so uploads were failing. This allows some common formats
for what is seemingly a very seldom use data type.
=> fix: expect uk date format when uploading ref data

dataworkspace/dataworkspace/apps/explorer/tasks.py, dataworkspace/dataworkspace/tests/explorer/factories.py, dataworkspace/dataworkspace/tests/explorer/test_tasks.py, dataworkspace/start-celery-dev.sh, docker-compose-dev.yml
We are getting errors in Sentry (e.g. https://sentry.ci.uktrade.digital/organizations/dit/issues/34632/?project=144&statsPeriod=14d) when trying to clear up temporary Data Explorer tables with permission denied.
Brucey bonus: update the local dev celery worker to reload automatically on Python file changes.
=> Fix permission denied

dataworkspace/dataworkspace/apps/datasets/admin.py
Add space after comma for tool query log related datasets
=> fix: add comma after related dataset link

dataworkspace/dataworkspace/apps/explorer/tasks.py, dataworkspace/dataworkspace/tests/explorer/test_tasks.py
The server database user can't directly grant itself access to the
schema, but it can grant the role to itself, which includes access to
the schema. So let's do that instead.
=> fix: grant correct permissions

dataworkspace/dataworkspace/apps/accounts/backends.py, dataworkspace/proxy.py
Make sentry errors easier to read by using the native user logging
features. This doesn't make any new information available in Sentry, as
this data is already tracked through HTTP headers. It just makes it
easier to read and trace.
=> feat: annotate sentry errors with user info

dataworkspace/dataworkspace/settings/base.py
The current crontab is incorrect and is running once a minute between 12am and 1am. It should just be run once.
=> fix: update the crontab entry for explorer cleanup to run once a day

dataworkspace/proxy.py
Shiny visualisation go grey after 1 minute of inactivity and they currently need a workaround in the visualisation R code to keep the connection alive.
This can instead be fixed in the proxy by passing a heartbeat parameter when creating the downsteam websocket which makes the server send a ping request to the client, thereby keeping the connection alive.
Example of a working visualisation: https://hello-shiny.data.trade.staging.uktrade.digital/
https://trello.com/c/RAvdLbwY/510-prevent-shiny-visualisations-from-stopping-after-1-minute-of-idleness
=> feature: send ping from server to client to keep websocket connection alive

dataworkspace/dataworkspace/apps/applications/utils.py
REASSIGN OWNED requires privileges on both the source role(s) and the target role. Related to https://github.com/uktrade/data-workspace/pull/1167
=> fix: REASSIGN requires privileges on both source and target

Dockerfile
The Dockerfile build is failing because the chromium and chromium-driver versions have been retired in Debian. As this has already been upgraded in the past it's probably best to stop pinning a specific version and always install the latest
=> fix: install latest chromium and chromium-driver apt packages

dataworkspace/dataworkspace/apps/applications/utils.py
See if we can stop the throttling issues by using boto's standard retry mode with some extra retry attempts.
Will attempt 10 times with a maximum backoff of 20 seconds.
=> fix: up the number of retries when hit by throttling exception

dataworkspace/sentry.py
Remove any reference to database_data/password before sending to sentry
=> fix: scrub `database_data` from sentry event

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/dw_admin/forms.py
This PR is to disable `authorized_users` and `requires_authorization` fields on django admin for dataset pages, when the user doesn't have appropriate permission.
Unfortunately, for `authorized_users`, form field's `disable` isn't working as expected for `ModelMultipleChoiceField`. That is to disable both parts of the control. It only disables left side select control leaving the right on operational. Although user will not be able save the changes, it is not intended experience for the user. 
After few deliberations, had to resort to changing the widget to `SelectMultiple` and disable it instead, to counter this possible bug in Django.
=> disable authorized_users when user doesn't have permission

tools/jupyterlab-python/Dockerfile
The python package dash installs into /usr/local. We already attempted to make all of it writable by the user, but it wasn't done quite right. Some files/folders were still owned by root since they were added in the Dockerfile as root.
=> Tweak ownership to make dash installable

dataworkspace/dataworkspace/apps/api_v1/views.py, dataworkspace/dataworkspace/apps/applications/spawner.py
At the moment we create the DB credentials for the tool/visualisation
within the initiail request/response of the tool creation POST. This
step can take a little while though, so it would make sense to push it
into the background where the rest of the tool is setup so that the user
more quickly lands on the "tool loading" page with a spinner rather than
sitting for a second or so before anything even loads onto the page.
=> fix: create db creds in background

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/partials/alpha_banner.html, dataworkspace/dataworkspace/templates/running.html
Update the visualisation header to match the design provided https://9f0gap.axshare.com/#id=kqc7tc&p=data_page-header_and_footer_for_preview_page-dit_w_1.
**Before**
**After**
=> feat: update vis header to match new design

dataworkspace/dataworkspace/templates/running_base.html
Make the visualisation header full screen
=> fix: Make the visualisation header full width

dataworkspace/dataworkspace/templates/running_base.html
Removed alpha banner due to user complaints about screen real estate for visualisations.
=> feat: remove alpha banner from running visualisation

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/app-copy.js, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/partials/code_snippets.html, dataworkspace/dataworkspace/tests/datasets/test_utils.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
This PR is to show code snippets for each table within dataset page in data workspace.
=> show code snippets for each source table on dataset page

infra/ecs_main_admin.tf, infra/main.tf
At the moment we allow 300 seconds in all environments for ALB targets
to be deregistered. This allows in-flight requests to complete safely
before the targets are killed, but also increases deployment time
significantly as we have to wait for both dev and staging to have this
300s dereg delay each. It would be nice to have a lower (or nil)
deregistration delay in these environments so that deployments from
build to prod can be faster. There are often few/no requests in
dev+staging, and even if they are, it's probably OK for AWS to kill them
after a much shorter delay as they're only for testing.
=> fix: allow configuration of ALB dereg delay

infra/security_groups.tf
Allow all private-without-egress subnets to talk to dns-rewrite-proxy.
=> fix: allow all private-without-egress subnets in dns-rewrite-proxy SG

dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
If this is removed, GTM breaks and live search also breaks and fails to
push state changes to the window history.
=> fix: GTM expects span around the number of results

gitlab/start.sh, infra/ec2.tf, infra/ecs_main_gitlab.tf, infra/main.tf
Users have previously reported issues checking out larger git repos from GitLab, and investigation by Michal led to a number of git config settings that alleviated the issue. These were previously issued as one-off commands on the instance, but now we should persist them so they can be applied to any future releases of the gitlab instance.
As part of this change we're moving from an individual's SSH key on the gitlab core instances to a shared one that has been stored in passman. TF PR is separate.
=> Persist git settings for GitLab

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/settings/base.py
Sometimes we want to grant thousands of users access to a dataset.
Django forms end up sending one form field for each user. The default
limit on # form fields submitted per POST is 1000. This means that at
the moment, there's (roughly) an upper limit of 1000 users that can be
granted access to a dataset - existing users must be sent as well, so
it's not as if we can continuously grant 1000 users new access in each
request.
This bumps the limit to 10,000 form fields, which should be more than good
enough for a fair while - ideally until a better solution is available,
e.g. granting datasets to a group that contains multiple users.
We also tweak the quicksight sync code so that it does a bulk refresh
rather than a user-by-user refresh if we're adding/removing a lot of
users at once - this …
=> fix: allow more form fields in POST

infra/ecs_main_admin.tf
A slightly more conservative version of https://github.com/uktrade/data-workspace/pull/1218, which leaves the policies in tact, as these are still required by the standard tool spinup.
=> refactor: remove unused store db creds admin task

dataworkspace/dataworkspace/static/search-v2.js
HTML5 inputs with a 'search' type get a little "x" automatically added
in some browsers. Clicking this clears the search input but doesn't
refresh the results on Data Workspace's search page. We can hook into
this by recognising a form change on the 'search' event.
=> fix: refresh results when clearing search input

healthcheck/Dockerfile, infra/ecr.tf, infra/ecs_main_admin.tf, infra/ecs_main_dns_rewrite_proxy.tf, infra/ecs_main_gitlab.tf, infra/ecs_main_healthcheck.tf, infra/ecs_main_prometheus.tf, infra/ecs_main_sentryproxy.tf, infra/ecs_notebooks_jupyterlab_python.tf, infra/ecs_notebooks_jupyterlab_r.tf, infra/ecs_notebooks_notebook.tf, infra/ecs_notebooks_pgweb.tf, infra/ecs_notebooks_remote_desktop.tf, infra/ecs_notebooks_superset.tf, infra/ecs_notebooks_theia.tf, infra/ecs_pgadmin.tf, infra/ecs_rstudio.tf, infra/ecs_user_provided.tf, infra/main.tf, infra/security_groups.tf, s3sync/Dockerfile, s3sync/requirements.txt, sentryproxy/Dockerfile
Almost everything that is currently used moved to ECR.
An exception is JupyterLab R: we agreed to remove it a while back, so doing it now (usage is virtually non-existant). I have hidden it from production.
Another exception is the mirrors sync, which can be done in less of a rush
Although remotedeskop isn't being used, maintaining that just in case so we can run desktop applications if we need to.
Some of the unused tools are partially modified: s3sync and metrics images have been changed to get the terraform to work, but the their images are not in ECR. Leaving tidy up to later.
=> Move to ECR

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/explorer/templatetags/explorer_tags.py, dataworkspace/dataworkspace/apps/your_files/urls.py, dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/apps/your_files/views.py, dataworkspace/dataworkspace/static/your-files-create-table.js, dataworkspace/dataworkspace/templates/your_files/create-table-base.html, dataworkspace/dataworkspace/templates/your_files/create-table-failed.html, dataworkspace/dataworkspace/templates/your_files/create-table-ingesting.html, dataworkspace/dataworkspace/templates/your_files/create-table-success.html, dataworkspace/dataworkspace/templates/your_files/create-table-validating.html, dataworkspace/dataworkspace/templates/your_files/files.html, dataworkspace/dataworkspace/tests/your_files/test_views.py
- Adds new templates for each step - validate, ingest, success, fail
- Validate waits for dag status to be "running" or "success" and redirects to ingest when it gets a match
- Ingest waits for dag status to be "success" and redirects to success when it gets a match
- If either step gets an http error or a dag status of "failed" it will redirect to the failure template.
=> feat: create table validate -> ingest -> success

dataworkspace/dataworkspace/apps/your_files/utils.py
In theory, users could have uploaded CSV files with very long first line
and that could drain significant memory on the server, potentially
bringing it down. So let's only process the first 100KiB of the file and
trust that this should be sufficient to read at least the first 10 lines
or so.
=> fix: prevent DOS from processing long lines

dataworkspace/dataworkspace/apps/your_files/utils.py, dataworkspace/dataworkspace/tests/your_files/test_views.py
The execution date airflow returns is not the execution date you can use to query the task via the api. You need to remove the timzone info from it. Undocumented so a good couple of hours spent looking for this :disappointed:
=> fix: remove timezone info from execution date

Jenkinsfile
Now that we've migrated to ECR, we can cache the layers of
data-workspace images in order to speed up our deployment pipeline. We
also add some flags to Kaniko so that it only builds our target stage
from the Dockerfile and ignores unused stages (so no longer needs to
build the test stage, which pulls in node and some other dependencies).
In tests this has taken builds from 7-10 minutes to 1-2 minutes.
=> cicd: cache build layers for faster deployments

dataworkspace/dataworkspace/templates/tools.html
At the moment, we have an h1 for 'Tools' page followed by an 'h3' for
each individual tool, then followed by an 'h2' for access requirements.
Access requirements feels like a separate thing from individual tools,
so to address this gap rather than raising each tool to an h2 we'll add
a visually-hidden h2 above the tool instances that provides a semantic
grouping for them.
=> fix: include h2 for screenreaders on tools page

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/explorer/_base.html
Better aria descriptions for search result pagination links
GOV.UK Design System currently has the aria-label for the header
navigation on a `<ul>` element within a naked `<nav>` element. This came
up in discussion recently on x-gov slack and they seem to have
recognised this isn't ideal, and are planning to move it onto the nav
element for a future release of the Design System. So let's also do the
same.
=> Fix duplicate landmarks 1

dataworkspace/dataworkspace/static/search-v2.js, dataworkspace/dataworkspace/templates/datasets/index.html
* Ensure that search results count is read out after live search results
are loaded in via appropraite use of aria/role attributes.
* Restore focus on the focused element after search results are swapped
in.
=> fix: make search more accessible to screenreaders

infra/ecr.tf, infra/ecs_main_mirrors_sync.tf, infra/main.tf
Change mirrors-sync and mirrors-sync-cran-binary tasks to use ECR images instead of quay.io.
Also adds a missing aws_cloudwatch_event_target for the debian mirror and fixes a typo in the nltk mirror target.
Related terraform-data-workspace PR is number 20
=> feature: change mirrors sync to use ecr repo

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/forms.py, dataworkspace/dataworkspace/templates/request_access.html
Disable HTML5 validation as per GOV.UK Design System recommendation and
include an error summary at the top of the page linking to the form
field being validated.
We have to do some slight hacks to fill the dynamically-generated label
and hint text for this page by reaching into the widget's custom context
and manually overwriting that as well. This is some small tech debt from
the Design System form/fields implementation to work with Django's form
system.
=> fix: use error summary for validation errors

dataworkspace/dataworkspace/templates/running_base.html
Remove the `<main>` wrapper which has caused the height of the
visualisation to decrease significantly. We probably don't need this
element if we just put a role=main on the div and point the skip link at
that instead.
=> fix: tweak skip to main content target

infra/ecs_main_mirrors_sync.tf
There is currenly one rule that runs at 4am with 5 scheduled tasks attached to it but there should be 6. There is a hard limit of 5 tasks per rule and therefore running `terraform apply` results in the following error:
`Error: Updating CloudWatch Event Target failed: LimitExceededException: The requested resource exceeds the maximum number allowed.`
This PR creates an additional rule and places the 6th scheduled task there to get around this.
=> feature: spread scheduled tasks out as there is a limit of 5 per rule

infra/ecs_main_gitlab.tf
The gitlab-runner ec2 instance runs out of disk space when there are too many docker images and this causes visualisation builds to fail. This PR adds a crontab entry to run a docker image prune once a day to delete images more than 24 hours old.
https://trello.com/c/SQRttjsg/605-reduce-chance-of-visualisation-build-failures-do-something-about-running-out-of-space-in-the-gitlab-runner
This has been tested on dev.
=> feature: delete unreferenced docker images on the gitlab-runner ec2

infra/vpc.tf
This opens up the public_whitelisted_ingress subnet to more ports, but the only thing in that subnet is the AWS load balancer, which only has listeners on 22 and 443, so realistically no new ports are opened up on any bit of infrastructure.
This is to work-around the limit on the number of rules in an NACL, we can add more IPs to the allow-list. We can't do this indefinitely, but for now, it's the quickest/easiest thing to be able to add a few more IPs to the list.
=> refactor: use fewer NACL rules

dataworkspace/dataworkspace/templates/quicksight_running.html
Enable QuickSight's dashboard to automatically set the height of the 
visualisation based on the content, rather than fitting the window and 
scrolling within the iframe.
=> fix: use responsive dashboard height

mirrors-sync-cran-binary/Dockerfile, mirrors-sync-cran-binary/build.R
Installing gifski from source in RStudio requires internet access so this needs to be pre-compiled and available in the cran-binary mirror
=> feature: add gifski R package to cran-binary mirror

dataworkspace/dataworkspace/static/explorer-ie11-compat.js
Clicking on the backdrop during a file upload cancels the upload and this isn't made clear to the user. As each modal has a cancel button there is no need to close the modal when the user clicks on the backdrop.
https://trello.com/c/gSJh9fMv/502-your-files-clicking-outside-of-upload-window-closes-up-and-stops-upload
=> feature: stop Your Files modals from closing when clicking on backdrop

dataworkspace/dataworkspace/templates/_base.html
Make it look the same as the "switch to Data Workspace" link on Data Hub.
=> fix: styling on switch to data hub link

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
We were missing a `.live()` call on the VisualisationCatalogueItem
queryset on the dataset search page, so deleted items could still show
up in results. This fixes that and brings it in line with the other
three kinds of dataset.
=> fix: do not show deleted visualisations in search

rstudio/Dockerfile, tools/jupyterlab-python/Dockerfile, tools/jupyterlab-r/Dockerfile, tools/theia/Dockerfile
We're currently using `buster-slim` as the base image for our
docker-based tools (e.g. theia, jupyterlab). After a chat with the devs
we don't really have a good reason for this. Our images are already
pretty gargantuan - around 4GB, so the difference between `buster` and
`buster-slim` is insignificant in comparison.
The `-slim` variant specifically excludes man pages from the build, so
in some tools we've had to hack this exclusion to re-introduce them, and
after doing that we're still missing some manpages for common tools,
e.g. grep. So since size isn't a concern, let's go back to using the
"full-fat" `buster` base image. Then we can remove our hacks and benefit
from a more complete man-db with no extra work.
=> feat: stop using `slim` buster variant in tools

dataworkspace/dataworkspace/apps/explorer/templates/explorer/partials/query_results.html, dataworkspace/dataworkspace/static/data-workspace.css, dataworkspace/dataworkspace/static/explorer_custom.css, dataworkspace/dataworkspace/templates/datasets/dataset_preview.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html
Makes sure that the tables for master/reference dataset previews, and Data Explorer results, can be tabbed into and scrolled using the keyboard. It also adds a GOV.UK Design System-style focus on the tables, with some padding added by default to ensure that the table doesn't jump around slightly when the focus border is added.
=> fix: allow tables to be focused and scrolled

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/templates/visualisation_branch.html
Currently application logs can only be downloaded for previewed/production visualisations on the master branch. This PR allows the user to download logs on any branch as long as the visualisation has been previewed.
https://trello.com/c/s6kQ3Vah/1442-link-to-visualisation-application-logs-for-any-branch-not-just-deployed-master
=> feature: allow user to download logs for visualisations in any branch

dataworkspace/dataworkspace/templates/quicksight_running.html
IE11 doesn't like es6 style functions so revert back to function() for the quicksight "show modal" event callback
=> fix: use old school function as callback

dataworkspace/dataworkspace/apps/datasets/templatetags/datasets_tags.py, dataworkspace/dataworkspace/datasets_db.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/referencedataset_detail.html, dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html, dataworkspace/dataworkspace/tests/datasets/test_models.py, dataworkspace/dataworkspace/tests/datasets/test_tags.py
Adds GMT offset to catalogue item last updated dates. E.g.
- `2020-01-01 11:40` will be displayed as `Jan 1, 2020, 11:40am, GMT`
- `2020-07-16 11:40` will be displayed as `Jul 16, 2020, 12:40pm, GMT+1`
**Master dataset**
**Data cut dataset**
**Reference dataset**
**Visualisation**
=> feat: format last update date with timezone

dataworkspace/dataworkspace/apps/applications/utils.py
Temporary database users created for quicksight users currently have access to a different schema to the one used in DW tools. This PR fixes that, allowing quicksight visualisations to access tables in the user's private schema.
https://trello.com/c/bsp6tZjL/1452-your-files-csv-upload-available-in-quicksight
=> feature: give quicksight db user access to the user's DW schema

dataworkspace/proxy.py, test/test_application.py
~~Send `Accept-Encoding` header as `identity` for requests from the proxy to SSO endpoints.~~
Do not send an Accept-Encoding header to sso endpoints
=> fix: do not send "Accept-Encoding" header to SSO

dataworkspace/dataworkspace/templates/datasets/visualisation_catalogue_item.html
Use `|safe` for visualisation description text to match the other dataset types
~~* [ ] Have tests been added to cover any changes?~~
=> fix: mark vis description as safe html

dataworkspace/dataworkspace/apps/api_v1/pagination.py
There are 11,000,000 query log records that to be synced every night and the current page size of 100 rows will probably take some time. So, allow the client to specify the page size - up to a limit of 10k.
=> fix: allow client to specify page size

dataworkspace/dataworkspace/apps/datasets/utils.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/static/app-tabs.css, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/tests/datasets/test_download_views.py, dataworkspace/dataworkspace/tests/datasets/test_utils.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Show code snippets for Datacut catalogue page SQL queries. This PR also removes the 'fields' key from the datacut view context data as it wasn't being used in the template.
https://trello.com/c/nqGh0b0V/1592-franks-favourite-card-data-cut-query-on-data-cut-page
=> feature: show code snippets for custom SQL queries on datacut catalogue pages

dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/tests/test_admin.py
Incorrect indentation meant that only the most recent user in the for loop gets their schema info cache cleared.
=> fix: ensure all users get their schema info cache cleared

dataworkspace/dataworkspace/apps/finder/elasticsearch.py, dataworkspace/dataworkspace/templates/finder/index.html, requirements-dev.txt, requirements.in, requirements.txt
When deployed to ECS, the credentials retrieved by boto have a session
token that expires after a certain amount of time. Therefore for each
request we need to check, before sending, whether the credentials need
to be refreshed. This is handled by the `BotoAWSRequestsAuth` here.
=> fix: use refreshable AWS credentials

dataworkspace/dataworkspace/apps/finder/elasticsearch.py, dataworkspace/dataworkspace/apps/finder/views.py
For dataset finder, we search across index aliases for nearly every
source table in Data Workspace. This can be quite a lot of indexes. The
request to ES is rejected if the body is too large, and this seems to
happen around ~400 source tables. Let's send multiple ES requests and
batch up the index aliases into groups of roughly 200 to avoid this
issue.
We do this rather than query every index in ES and do all of the
filtering in Data Workspace, because if any indexes are being written to
by Elasticsearch at the time, and we query them, it can introduce
significant delays. All of the indexes we query are effectively
read-only at the time, and so should have slightly better search speeds.
=> fix: dataset finder 413 from Elasticsearch

dataworkspace/dataworkspace/apps/accounts/admin.py, dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/apps/explorer/utils.py, dataworkspace/dataworkspace/tests/test_admin.py
When a user is granted or revoked access to a dataset, their data explorer cached credentials should be cleared to ensure their database permissions are valid.
Also, when a dataset's user_access_type is changed, all unauthorized users should have their credentials cleared as well. This ensures that users who couldn't access a now "public" dataset get access, and users who had access to a now "private" dataset lose access.
https://trello.com/c/gUDVTJ9n/1591-people-really-get-data-explorer-credentials-when-they-are-granted-clear-cached-data-explorer-credentials-on-permissions-change
=> feature: clear data explorer cached credentials if permissions change

dataworkspace/dataworkspace/static/explorer_custom.css
**Before**
**After**
https://trello.com/c/GiLeKBIT/1599-data-explorer-auto-fill-enhancement
=> feature:increase explorer autocomplete width to allow long table names

dataworkspace/dataworkspace/apps/datasets/forms.py, dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/_base.html, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/index.html, dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/datasets/related_data.html, dataworkspace/dataworkspace/templates/partials/related_data.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
Adds a "related data" section to master catalogue pages, showing links
to any data cuts that make use of tables in the master dataset. On the
dataset detail page, this is limited to 4 entries, after which it shows
a "display all" link that leads to a separate page.
This new design is also applied to the existing datacut related data
section.
https://data-workspace-prototypes.herokuapp.com/ece/data-workspace/data-related-II
=> Related datacuts

dataworkspace/dataworkspace/apps/finder/elasticsearch.py
The current "match_phrase" query type means that terms must appear in the same order as they do in the document for a match to occur. Using the "match" query type will get around this but it doesn't seem to support searching for an exact phrase which a user may want to do.
Using "simple_query_string" appears to support both, meaning that searching for terms in any order will still return the correct results, i.e "United Kingdom" and "Kingdom United" will return a similar number of results. However, if a user wants to search for an exact phrase they can still do so by wrapping the phrase in double quotes.
See https://trello.com/c/KRB21anx/1604-dataset-finder-evaluation-of-performance-and-results-and-suggest-improvements for more details
=> feature: use simple_query_string for finder search queries

dataworkspace/dataworkspace/templates/finder/results.html
This is to fix dataset finder results page, not to show paging when no documents available for indexed table.
=> don't show paging when there are no documents available

dataworkspace/dataworkspace/apps/applications/utils.py
Following on from f656f27092388f688d681e1917afa5844408c772, "other_emails" may not contain the primary email, so in some cases existing users are not found.
=> fix: creation of users not finding existing ones

tools/theia/package.json, tools/theia/yarn.lock
This is due to a vulnerability. Slightly unfortunately this is a transitive dependency, and the intermediate dependencies seem to depend on earlier that the fixed version. Have only done a brief bit of testing, but looking in the changlog of SSRI, while there _have_ been breaking changes, SSRI's API hasn't changed completely, so I think a reasonable chance the breaking bits weren't being used.
=> feat: bump SSRI

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_preview.html
This PR allows columns to be filtered before downloading. from data cut query preview pages. This change will have to be rolled out separately for source links.
=> allow columns to be filtered before downloading

dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/apps/datasets/admin.py, dataworkspace/dataworkspace/tests/api_v1/core/test_views.py, dataworkspace/dataworkspace/tests/test_admin.py
- Delete / invalidate superset cached db credentials/permitted dashboards when a visualisation catalogue item is saved
- Set the credentials_version_key to never expire, otherwise invalid cached credentials that haven't been deleted yet may be used
=> fix: invalidate and clear superset cache when saving visualisation

dataworkspace/dataworkspace/apps/api_v1/core/views.py, dataworkspace/dataworkspace/apps/explorer/utils.py
Set the explorer_credentials_version key to never expire, otherwise invalid cached credentials that haven't been deleted yet may be used
=> fix: set explorer_credentials_version to never expire

infra/ecs_notebooks_jupyterlab_python.tf, infra/ecs_notebooks_jupyterlab_r.tf, infra/ecs_notebooks_notebook.tf, infra/ecs_notebooks_pgweb.tf, infra/ecs_notebooks_remote_desktop.tf, infra/ecs_notebooks_superset.tf, infra/ecs_notebooks_theia.tf, infra/ecs_user_provided.tf, infra/main.tf
This is so we can send exceptions to a different Sentry project, to then send them to a different Slack channe
=> feat: allow tools and visualisations to have different Sentry DSN

dataworkspace/dataworkspace/templates/partials/tool_section.html, dataworkspace/dataworkspace/tests/core/test_views.py
Link to the "request tool access" help page rather than the support page.
Ticket: https://trello.com/c/FNBAqVso/1778-request-access-link-update-on-tools-page
=> fix: link to tool access help page

Makefile, README.md, docker-compose-test-local.yml
Reduce the need to constantly rebuild containers when testing locally.
- Add a new docker compose file `docker-compose-test-local.yml` that mounts `/dataworkspace` and `/test`
- Add new local test commands to `Makefile`
- `make docker-test-unit-local`
- `make docker-test-integration-local`
- `make docker-test-local`
- Update readme
~~* [ ] Have tests been added to cover any changes?~~
=> feat: add local test makefile commands

dataworkspace/dataworkspace/apps/explorer/templates/explorer/base.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html, dataworkspace/dataworkspace/apps/explorer/templates/explorer/query_list.html, dataworkspace/dataworkspace/static/explorer_custom.css, test/selenium/explorer_pages.py, test/selenium/test_explorer.py
Change data explorer to be 95% of browser width at more than 1024px width by overriding GDS `govuk-width-container`
Changed footer links to stack horizintally
Removed redundant  duplicate text from within the tabs
=> made dataexplorer 95% of browser width for desktop

dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
when a master dataset is in authentication mode (Each user must be individually authorized to access the data) and if at least one user (other than yourself) has given access using authorized users section, then `You have access` filter is not showing the dataset. Fixed this by correcting the access filter queryset conditions.
=> attempt to fix access filter issue

dataworkspace/dataworkspace/apps/explorer/templates/explorer/query.html
removed div with class `govuk-width-container` which was adding extra padding to the query edit. This wouldn't have been a bug until i changed `max-width` to 95% in a previous update
=> removed duplicate govuk-width-container

dataworkspace/dataworkspace/apps/datasets/models.py, dataworkspace/dataworkspace/apps/datasets/urls.py, dataworkspace/dataworkspace/apps/datasets/views.py, dataworkspace/dataworkspace/templates/datasets/data_cut_dataset.html, dataworkspace/dataworkspace/templates/datasets/data_cut_usage_history.html, dataworkspace/dataworkspace/tests/datasets/test_views.py, dataworkspace/dataworkspace/tests/factories.py
Adds a link to the Datacut catalogue page which shows the 100 most recent download events related to the dataset grouped by date, user and query name:
https://trello.com/c/FklLZGPB/1802-step-1-show-usage-history-for-data-cuts
=> feature: show datacut source link and custom sql download usage history

dataworkspace/dataworkspace/templates/datasets/master_dataset.html, dataworkspace/dataworkspace/templates/partials/unauthorised_warning.html, dataworkspace/dataworkspace/tests/datasets/test_views.py
https://trello.com/c/67gCf7PJ/773-automated-tools-message-on-master-dataset-catalogue-pages
Request access messages only displays tools section for master dataset pages
=> request access message to only show 'tools' section for master datasets

dataworkspace/dataworkspace/apps/datasets/models.py
download link was visible for superusers.
=> fix: remove download link from master datasets

dns-rewrite-proxy/Dockerfile, dns-rewrite-proxy/nameserver.py, infra/ecs_main_dns_rewrite_proxy.tf, infra/ecs_main_dns_rewrite_proxy_new.tf
Change healthcheck from TCP to HTTP and attempt DNS query to determine service health. This is to avoid the situation where the DNS proxy is not working but the service is healthy as far as the load balancer is concerned. 
The new healtcheck Is currently set up on dev.
https://trello.com/c/0yRyrLDF/1643-dns-resolver-healthcheck-should-make-a-dns-query
=> feature: attempt dns query in dns-rewrite-proxy lb healtcheck

tools/requirements.in, tools/requirements.txt
Bump the notebook package to 6.1.5 to fix vulnerability [GHSA-c7vm-f5p4-8fqh](https://github.com/advisories/GHSA-c7vm-f5p4-8fqh)
=> fix: bump notebook to 6.1.5 to fix GHSA-c7vm-f5p4-8fqh

tools/theia/package.json, tools/theia/yarn.lock
Fixes security vulnerability GHSA-6fc8-4gx4-v693 which affects versions >= 5.0.0, < 7.4.6
=> Force ws package to minimum version of 7.4.6

dataworkspace/dataworkspace/apps/applications/utils.py, dataworkspace/dataworkspace/apps/core/utils.py
The main aim of this is to speed up db creds creation, to make Data Explorer and Docker-based tools starting feel nicer and be more robust. It's also a step toward the db proxy if we want to go that way, since it means each user has a permanent db role (which would be the case if we were to use a proxy). If the datasets db is slow for example, things should still not be too slow in starting up (with minimal writes)
---
This should eventually be followed by other changes:
- Have the creation of the role + its perms done even earlier than when credentials requested (in this PR, the first request would still be a bit slow I suspect, especially if the user has access to a lot of tables)
- Simplify the user cleanup tasks. They won't have any permissions, so no need for them to be revoked.
=> feat: associate credentials with a permanent role to speed up db creds creation

dataworkspace/dataworkspace/templates/case_studies/casestudy_list.html
Remove intro text from case study listing page until copy has been decided on.
=> fix: remove intro text from case study list page

test/pages.py
Suspect that sometimes the navigation had already happened by the time `waitForNavigation` was called
=> test: attempt to fix race condition when navigating

dataworkspace/dataworkspace/apps/core/utils.py
This is so the master user can call has_table_privilege/has_schema_privilege as needed on the schema owned by the team.
=> fix: creation of db creds when there are teams that the master user is not yet granted on

superset/superset_config.py
When the SQLLAB_BACKEND_PERSISTENCE feature flag is enabled no query data are stored within localstorage.
The metadata is stored in the backend SQLALCHEMY database. 
No query data is persisted to the postgres SQLALCHEMY db
=> Superset disable localstorage

tools/theia/Dockerfile, tools/theia/package.json, tools/theia/yarn.lock
Fixes CVE-2021-29060
- Update Dockerfile nodejs version to 12 - fixes out of memory issues when building locally
- Force yarn to resolve color-string to version 1.5.5 or newer to fix vulnerability
=> fix: update nodejs and force color-string to 1.5.5

dataworkspace/dataworkspace/apps/applications/views.py, dataworkspace/dataworkspace/tests/datasets/test_views.py
Currently if a user accesses a visualisation link directly without having permissions to access the catalogue item then they get a 403 page. Instead they should be redirected to the catalogue item's request access page.
=> feature: redirect to visualisation request access page if unauthorised

dataworkspace/dataworkspace/apps/explorer/templates/explorer/home.html
=> feature: add links to help articles on the Data Explorer homepage

dataworkspace/dataworkspace/utils.py
Add `uuid[]` to column types and map to string in the ui to stop them looking like `UUID(xxxx-xxxx...)`
=> fix: display uuid[] as text[] in data explorer output

dataworkspace/dataworkspace/apps/core/utils.py, dataworkspace/start.py
This is to try to get psycopg2 methods getting instrumented... suspect that our db connection pool imports variables before they are instrumented https://github.com/jneight/django-db-geventpool/blob/master/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py#L23
Suspect the instrumentation monkey-patching isn't perfect: it seems to have converted keyword arguments to positional: hence the change in stream_query_as_csv_to_queue
Screenshot from staging showing that SQL on the admin db appears to be instrumented with this change:
=> feat: try to turn on APM's instrumentation earlier to instrument queries on the admin db
